// Auto-generated by tools/generate_odin_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.)
// Do not edit by hand.
package situation

import "core:c"

foreign import situation "../../build/dll/situation_opengl.lib"

foreign situation {
    // [GL+VK] Prepare the backend for a new frame of rendering commands.
    SituationAcquireFrameCommandBuffer :: proc() -> Situation_Error ---

    // Adds multiple dependencies for a single dependent job.
    SituationAddJobDependencies :: proc(pool: ^Situation_Thread_Pool, prerequisites: ^Situation_Job_Id, count: c.int, dependent_job: Situation_Job_Id) -> Situation_Error ---

    // Adds a dependency between two jobs (prereq -> dependent).
    SituationAddJobDependency :: proc(pool: ^Situation_Thread_Pool, prerequisite_job: Situation_Job_Id, dependent_job: Situation_Job_Id) -> Situation_Error ---

    // Manually apply the appropriate window state profile based on current focus.
    SituationApplyCurrentProfileWindowState :: proc() -> Situation_Error ---

    // Attach a custom DSP processor to a sound's effect chain.
    SituationAttachAudioProcessor :: proc(sound: ^Situation_Sound, processor: Situation_Audio_Processor_Callback, user_data: rawptr) -> Situation_Error ---

    // Convenience: auto-select first available MIDI input. Equivalent to EnableMidiControl(..., -1).
    SituationAutoConnectMidi :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Upload bitmap_data as a NEAREST-filtered grid atlas for GPU text.
    SituationBakeBitmapFontAtlas :: proc(font: ^Situation_Font) -> Situation_Error ---

    // Rasterize a font into a GPU-ready atlas at the given size.
    SituationBakeFontAtlas :: proc(font: ^Situation_Font, fontSizePixels: f32) -> Situation_Error ---

    // Start non-blocking GLSL load: [OpenGL] async compile/link; [Vulkan] shaderc on worker thread, pipelines on next frames. Poll with SituationPollShaderLoad.
    SituationBeginLoadShaderFromMemory :: proc(vs_code: cstring, fs_code: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---

    // [Vulkan] Non-blocking pipeline build from in-memory SPIR-V (bytecode copied). [OpenGL] blocking SPIR-V load (unchanged).
    SituationBeginLoadShaderFromSpirvMemory :: proc(vs_spirv: rawptr, vs_len: uint, fs_spirv: rawptr, fs_len: uint, out_shader: ^Situation_Shader) -> Situation_Error ---

    // [Vulkan] Async SPIR-V with layout profile (e.g. UBO_SSBO for Demon Hunt). [OpenGL] profile ignored; same as SituationBeginLoadShaderFromSpirvMemory.
    SituationBeginLoadShaderFromSpirvMemoryEx :: proc(vs_spirv: rawptr, vs_len: uint, fs_spirv: rawptr, fs_len: uint, layout_profile: Situation_Spirv_Layout_Profile, out_shader: ^Situation_Shader) -> Situation_Error ---

    // [OpenGL] glShaderStorageBlockBinding for SPIR-V when reflection reports binding 0 for layout(binding=N).
    SituationBindShaderStorageBlock :: proc(shader: Situation_Shader, block_name: cstring, binding_point: u32) -> Situation_Error ---

    // [OpenGL] glUniformBlockBinding for std140 UBO blocks (layout(binding=N)).
    SituationBindUniformBlock :: proc(shader: Situation_Shader, block_name: cstring, binding_point: u32) -> Situation_Error ---

    // Copies raw byte data into a specific region of an image.
    SituationBlitRawDataToImage :: proc(data: rawptr, x: c.int, y: c.int, width: c.int, height: c.int, src_channels: c.int) ---

    // All logical CPUs on a NUMA node
    SituationBuildNumaNodeMask :: proc(numa_node_index: c.int) -> u64 ---

    // All logical CPUs on one physical core
    SituationBuildPhysicalCoreMask :: proc(physical_core_index: c.int) -> u64 ---

    // One LP per core
    SituationBuildUniqueCoreMask :: proc(start_physical_core: c.int, count: c.int, avoid_siblings: b8) -> u64 ---

    SituationCameraBuildInvViewProj :: proc(desc: ^Situation_Camera_Desc, out_inv_vp: mat4) ---
    SituationCameraBuildProj :: proc(desc: ^Situation_Camera_Desc, out_proj: mat4) ---
    SituationCameraBuildView :: proc(desc: ^Situation_Camera_Desc, out_view: mat4) ---
    SituationCameraBuildViewProj :: proc(desc: ^Situation_Camera_Desc, out_vp: mat4) ---
    SituationCameraUnprojectPixel :: proc(desc: ^Situation_Camera_Desc, inv_vp: mat4, pixel: Vector2, framebuffer_px: Vector2, out_ray_origin: ^Vector3, out_ray_dir: ^Vector3) ---
    // Cancel an active learn operation.
    SituationCancelMidiLearn :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Checks all tracked resources for file changes and reloads them if necessary.
    SituationCheckHotReloads :: proc() -> Situation_Error ---

    // Clear all learned mappings for a node.
    SituationClearAllMidiMappings :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Clear a specific learned CC mapping.
    SituationClearMidiMapping :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, control_index: c.int) -> Situation_Error ---

    // Clear window configuration state flags.
    SituationClearWindowState :: proc(flags: u32) ---

    SituationCmdBeginDebugGroup :: proc(cmd: Situation_Command_Buffer, name: cstring, color: Color_RGBA) -> Situation_Error ---
    // [GL+VK] Begins a render pass with detailed configuration.
    SituationCmdBeginRenderPass :: proc(cmd: Situation_Command_Buffer, info: ^Situation_Render_Pass_Info) -> Situation_Error ---

    SituationCmdBeginRenderToDisplay :: proc(cmd: Situation_Command_Buffer, display_id: c.int, clear_color: Color_RGBA) -> Situation_Error ---
    SituationCmdBindComputeBuffer :: proc(cmd: Situation_Command_Buffer, binding: u32, buffer: Situation_Buffer) -> Situation_Error ---
    // Bind a compute pipeline for a subsequent dispatch.
    SituationCmdBindComputePipeline :: proc(cmd: Situation_Command_Buffer, pipeline: Situation_Compute_Pipeline) -> Situation_Error ---

    // [Core] Binds a texture as a storage image for compute shaders.
    SituationCmdBindComputeTexture :: proc(cmd: Situation_Command_Buffer, binding: u32, texture: Situation_Texture) -> Situation_Error ---

    // [GL+VK] [Core] Binds a buffer's descriptor set (UBO/SSBO) to a set index.
    SituationCmdBindDescriptorSet :: proc(cmd: Situation_Command_Buffer, set_index: u32, buffer: Situation_Buffer) -> Situation_Error ---

    // [GL+VK] [Core] Binds a dynamic buffer descriptor set with an offset.
    SituationCmdBindDescriptorSetDynamic :: proc(cmd: Situation_Command_Buffer, set_index: u32, buffer: Situation_Buffer, dynamic_offset: u32) -> Situation_Error ---

    // [Core] Bind a 32-bit index buffer (SIT_INDEX_UINT32). Pass offset 0 when indices start at the beginning of the buffer.
    SituationCmdBindIndexBuffer :: proc(cmd: Situation_Command_Buffer, buffer: Situation_Buffer, offset: uint) -> Situation_Error ---

    // [Core] Bind index buffer with 16- or 32-bit element type for subsequent SituationCmdDrawIndexed.
    SituationCmdBindIndexBufferEx :: proc(cmd: Situation_Command_Buffer, buffer: Situation_Buffer, offset: uint, index_type: Situation_Index_Type) -> Situation_Error ---

    // [VK+GL] Push mesh vertex/index BDA block for pull shaders (SituationMeshPullPushConstants @ offset 0). Requires SIT_FEATURE_BINDLESS_BUFFERS.
    SituationCmdBindMeshPullBuffers :: proc(cmd: Situation_Command_Buffer, mesh: Situation_Mesh) -> Situation_Error ---

    // [GL+VK] Binds a graphics pipeline (shader program) for subsequent draws.
    SituationCmdBindPipeline :: proc(cmd: Situation_Command_Buffer, shader: Situation_Shader) -> Situation_Error ---

    // Binds a texture as a sampled image (sampler2D) to a binding point.
    SituationCmdBindSampledTexture :: proc(cmd: Situation_Command_Buffer, binding: c.int, texture: Situation_Texture) -> Situation_Error ---

    SituationCmdBindTexture :: proc(cmd: Situation_Command_Buffer, set_index: u32, texture: Situation_Texture) -> Situation_Error ---
    // [GL+VK] [Core] Binds a texture's descriptor set (sampler/storage) to a set index.
    SituationCmdBindTextureSet :: proc(cmd: Situation_Command_Buffer, set_index: u32, texture: Situation_Texture) -> Situation_Error ---

    SituationCmdBindUniformBuffer :: proc(cmd: Situation_Command_Buffer, contract_id: u32, buffer: Situation_Buffer) -> Situation_Error ---
    // [Core] Bind a vertex buffer for subsequent SituationCmdDraw / SituationCmdDrawIndexed.
    SituationCmdBindVertexBuffer :: proc(cmd: Situation_Command_Buffer, binding: u32, buffer: Situation_Buffer, offset: uint, stride: uint) -> Situation_Error ---

    // Blit between color 2D textures; caller owns explicit texture barriers.
    SituationCmdBlitTexture :: proc(cmd: Situation_Command_Buffer, src: Situation_Texture, dst: Situation_Texture, region: ^Situation_Texture_Blit_Region) -> Situation_Error ---

    // Record an explicit buffer-range memory barrier.
    SituationCmdBufferBarrier :: proc(cmd: Situation_Command_Buffer, desc: ^Situation_Buffer_Barrier_Desc) -> Situation_Error ---

    // Mid-pass clear of active render-pass attachments; begin-pass clears use SituationRenderPassInfo loadOp.
    SituationCmdClear :: proc(cmd: Situation_Command_Buffer, clear_flags: u32, clear_value: ^Situation_Clear_Value) -> Situation_Error ---

    // Mid-pass clear of the active color attachment.
    SituationCmdClearColor :: proc(cmd: Situation_Command_Buffer, color: Color_RGBA) -> Situation_Error ---

    // Mid-pass clear of the active depth attachment.
    SituationCmdClearDepth :: proc(cmd: Situation_Command_Buffer, depth: f32) -> Situation_Error ---

    // Mid-pass clear of active depth and stencil attachments.
    SituationCmdClearDepthStencil :: proc(cmd: Situation_Command_Buffer, depth: f32, stencil: u32) -> Situation_Error ---

    // Mid-pass clear of the active stencil attachment when supported by backend/attachment state.
    SituationCmdClearStencil :: proc(cmd: Situation_Command_Buffer, stencil: u32) -> Situation_Error ---

    // Legacy buffer-copy command (now returns error).
    SituationCmdCopyBuffer :: proc(cmd: Situation_Command_Buffer, src: Situation_Buffer, dst: Situation_Buffer, offset: uint, size: uint) -> Situation_Error ---

    // Error-returning buffer-copy command with independent source/destination offsets.
    SituationCmdCopyBufferEx :: proc(cmd: Situation_Command_Buffer, src: Situation_Buffer, dst: Situation_Buffer, src_offset: uint, dst_offset: uint, size: uint) -> Situation_Error ---

    // Upload tightly packed RGBA8 rows from a buffer into a texture subregion; caller owns texture barriers.
    SituationCmdCopyBufferToTexture :: proc(cmd: Situation_Command_Buffer, src: Situation_Buffer, src_offset: uint, dst: Situation_Texture, dst_region: ^Situation_Texture_Copy_Region) -> Situation_Error ---

    // Exact-size copy between color 2D textures; caller owns explicit texture barriers.
    SituationCmdCopyTexture :: proc(cmd: Situation_Command_Buffer, src: Situation_Texture, dst: Situation_Texture, region: ^Situation_Texture_Copy_Region) -> Situation_Error ---

    // Copy a texture subregion into a buffer (`dst_row_pitch` 0 = width * 4); caller owns texture barriers.
    SituationCmdCopyTextureToBuffer :: proc(cmd: Situation_Command_Buffer, src: Situation_Texture, src_region: ^Situation_Texture_Copy_Region, dst: Situation_Buffer, dst_offset: uint, dst_row_pitch: uint) -> Situation_Error ---

    // Record a command to dispatch compute shader work groups.
    SituationCmdDispatch :: proc(cmd: Situation_Command_Buffer, group_count_x: u32, group_count_y: u32, group_count_z: u32) -> Situation_Error ---

    // Record a compute dispatch with validation and error reporting.
    SituationCmdDispatchEx :: proc(cmd: Situation_Command_Buffer, group_count_x: u32, group_count_y: u32, group_count_z: u32) -> Situation_Error ---

    // Record an indirect compute dispatch.
    SituationCmdDispatchIndirect :: proc(cmd: Situation_Command_Buffer, indirect_buffer: Situation_Buffer, offset: uint) -> Situation_Error ---

    // [GL+VK] [Core] Record a non-indexed draw call.
    SituationCmdDraw :: proc(cmd: Situation_Command_Buffer, vertex_count: u32, instance_count: u32, first_vertex: u32, first_instance: u32) -> Situation_Error ---

    // [GL+VK] [Core] Record an indexed draw call.
    SituationCmdDrawIndexed :: proc(cmd: Situation_Command_Buffer, index_count: u32, instance_count: u32, first_index: u32, vertex_offset: c.int, first_instance: u32) -> Situation_Error ---

    // [Core] Indexed indirect draw (32-bit indices; requires bound index buffer). firstIndex is relative to SituationCmdBindIndexBuffer offset.
    SituationCmdDrawIndexedIndirect :: proc(cmd: Situation_Command_Buffer, indirect_buffer: Situation_Buffer, offset: uint) -> Situation_Error ---

    // [Core] Draw from a CPU/GPU-filled SituationDrawIndirectCommand in an indirect buffer (requires active render pass, bound pipeline, and vertex buffers).
    SituationCmdDrawIndirect :: proc(cmd: Situation_Command_Buffer, indirect_buffer: Situation_Buffer, offset: uint) -> Situation_Error ---

    // [High-Level] Records a command to draw a complete, pre-configured mesh.
    SituationCmdDrawMesh :: proc(cmd: Situation_Command_Buffer, mesh: Situation_Mesh) -> Situation_Error ---

    // [High-Level] Record a command to draw a simple, colored 2D quad.
    SituationCmdDrawQuad :: proc(cmd: Situation_Command_Buffer, model: mat4, color: Vector4) -> Situation_Error ---

    // Draws a text string using GPU-accelerated textured quads.
    SituationCmdDrawText :: proc(cmd: Situation_Command_Buffer, font: Situation_Font, text: cstring, pos: Vector2, color: Color_RGBA) -> Situation_Error ---

    // Text clipped to a rectangle with optional word wrap.
    SituationCmdDrawTextBoxed :: proc(cmd: Situation_Command_Buffer, font: Situation_Font, text: cstring, bounds: Sit_Rectangle, fontSize: f32, spacing: f32, color: Color_RGBA, word_wrap: b8) -> Situation_Error ---

    // Advanced text drawing (scaling/spacing).
    SituationCmdDrawTextEx :: proc(cmd: Situation_Command_Buffer, font: Situation_Font, text: cstring, pos: Vector2, fontSize: f32, spacing: f32, color: Color_RGBA) -> Situation_Error ---

    // [High-Level] Draw a part of a texture defined by a rectangle.
    SituationCmdDrawTexture :: proc(cmd: Situation_Command_Buffer, texture: Situation_Texture, source: Sit_Rectangle, dest: Sit_Rectangle, origin: Vector2, rotation: f32, tint: Color_RGBA) -> Situation_Error ---

    // [High-Level] Draw texture with YPQ grade (matches SituationImageAdjustYPQ).
    SituationCmdDrawTextureYpqGrade :: proc(cmd: Situation_Command_Buffer, texture: Situation_Texture, source: Sit_Rectangle, dest: Sit_Rectangle, origin: Vector2, rotation: f32, phase_shift_deg: f32, chroma_factor: f32, luma_factor: f32, mix: f32) -> Situation_Error ---

    SituationCmdEndDebugGroup :: proc(cmd: Situation_Command_Buffer) -> Situation_Error ---
    SituationCmdEndRender :: proc(cmd: Situation_Command_Buffer) -> Situation_Error ---
    // [GL+VK] Ends the current render pass.
    SituationCmdEndRenderPass :: proc(cmd: Situation_Command_Buffer) -> Situation_Error ---

    // Legacy convenience barrier; prefer SituationCmdPipelineBarrierEx, SituationCmdBufferBarrier, or SituationCmdTextureBarrier for new synchronization code.
    SituationCmdPipelineBarrier :: proc(cmd: Situation_Command_Buffer, src_flags: u32, dst_flags: u32) ---

    // Record an explicit global memory barrier.
    SituationCmdPipelineBarrierEx :: proc(cmd: Situation_Command_Buffer, desc: ^Situation_Pipeline_Barrier_Desc) -> Situation_Error ---

    SituationCmdPopRasterState :: proc(cmd: Situation_Command_Buffer, scope_id: u32) -> Situation_Error ---
    // Submits a command to copy a texture to the main window's swapchain (Compute-Only).
    SituationCmdPresent :: proc(cmd: Situation_Command_Buffer, texture: Situation_Texture) -> Situation_Error ---

    SituationCmdPushRasterState :: proc(cmd: Situation_Command_Buffer, scope_id: u32) -> Situation_Error ---
    SituationCmdSetBlendEnable :: proc(cmd: Situation_Command_Buffer, enable: b8) -> Situation_Error ---
    SituationCmdSetBlendFuncSeparate :: proc(cmd: Situation_Command_Buffer, src_rgb: Situation_Blend_Factor, dst_rgb: Situation_Blend_Factor, src_a: Situation_Blend_Factor, dst_a: Situation_Blend_Factor) -> Situation_Error ---
    SituationCmdSetColorWriteMask :: proc(cmd: Situation_Command_Buffer, r: b8, g: b8, b: b8, a: b8) -> Situation_Error ---
    SituationCmdSetCullMode :: proc(cmd: Situation_Command_Buffer, mode: Situation_Cull_Mode) -> Situation_Error ---
    SituationCmdSetDepthBias :: proc(cmd: Situation_Command_Buffer, enable: b8, constant_factor: f32, clamp: f32, slope_factor: f32) -> Situation_Error ---
    SituationCmdSetDepthTest :: proc(cmd: Situation_Command_Buffer, enable: b8, depth_op: Situation_Depth_Compare_Op) -> Situation_Error ---
    SituationCmdSetDepthWrite :: proc(cmd: Situation_Command_Buffer, enable: b8) -> Situation_Error ---
    SituationCmdSetFrontFace :: proc(cmd: Situation_Command_Buffer, front_face: Situation_Front_Face) -> Situation_Error ---
    SituationCmdSetLineWidth :: proc(cmd: Situation_Command_Buffer, width: f32) -> Situation_Error ---
    SituationCmdSetMultisampleState :: proc(cmd: Situation_Command_Buffer, state: ^Situation_Multisample_State) -> Situation_Error ---
    SituationCmdSetPolygonMode :: proc(cmd: Situation_Command_Buffer, mode: Situation_Polygon_Mode) -> Situation_Error ---
    SituationCmdSetPrimitiveTopology :: proc(cmd: Situation_Command_Buffer, topology: Situation_Primitive_Topology) -> Situation_Error ---
    // [Core] Set a small block of per-draw uniform data (push constant).
    SituationCmdSetPushConstant :: proc(cmd: Situation_Command_Buffer, contract_id: u32, data: rawptr, size: uint) -> Situation_Error ---

    SituationCmdSetPushConstantData :: proc(cmd: Situation_Command_Buffer, shader: Situation_Shader, offset: u32, data: rawptr, size: uint) -> Situation_Error ---
    // Sets the dynamic scissor rectangle to clip rendering.
    SituationCmdSetScissor :: proc(cmd: Situation_Command_Buffer, x: c.int, y: c.int, width: c.int, height: c.int) -> Situation_Error ---

    // Sets scissor at index (0 = default scissor).
    SituationCmdSetScissorIndexed :: proc(cmd: Situation_Command_Buffer, index: u32, x: c.int, y: c.int, width: c.int, height: c.int) -> Situation_Error ---

    SituationCmdSetStencilTest :: proc(cmd: Situation_Command_Buffer, enable: b8, front: ^Situation_Stencil_State, back: ^Situation_Stencil_State) -> Situation_Error ---
    // [OpenGL Only, Deprecated v2.4] Attribute format + vertex buffer binding index. Prefer vertex pulling via SituationGetMeshVertexBufferAddress + sit/gpu/vertex_pull.glslh on Vulkan.
    SituationCmdSetVertexAttribute :: proc(cmd: Situation_Command_Buffer, location: u32, binding: u32, size: c.int, type: Situation_Data_Type, normalized: b8, offset: uint) -> Situation_Error ---

    // Sets the dynamic viewport and scissor for the current render pass.
    SituationCmdSetViewport :: proc(cmd: Situation_Command_Buffer, x: f32, y: f32, width: f32, height: f32) -> Situation_Error ---

    // Sets viewport at index (0 = default viewport).
    SituationCmdSetViewportIndexed :: proc(cmd: Situation_Command_Buffer, index: u32, x: f32, y: f32, width: f32, height: f32) -> Situation_Error ---

    // Record an explicit texture layout/memory barrier.
    SituationCmdTextureBarrier :: proc(cmd: Situation_Command_Buffer, texture: Situation_Texture, desc: ^Situation_Texture_Barrier_Desc) -> Situation_Error ---

    // Converts a YPQA color back to the standard RGBA color space.
    SituationColorFromYPQ :: proc(ypq_color: Color_YPQA) -> Color_RGBA ---

    // Float YPQ → RGBA (linear YIQ, clamped RGB).
    SituationColorFromYPQf :: proc(ypq: Color_YP_Qf) -> Color_RGBA ---

    // sRGB 0–255 → PQ clear color as RGBA floats×255 for debugging.
    SituationColorRgbaToHdrPqClear :: proc(srgb: Color_RGBA) -> Color_RGBA ---

    // Converts a standard RGBA color to the YPQA (Luma, Phase, Quadrature) color space.
    SituationColorToYPQ :: proc(color: Color_RGBA) -> Color_YPQA ---

    // RGBA → normalized float YPQ (no 8-bit quantize).
    SituationColorToYPQf :: proc(color: Color_RGBA) -> Color_YP_Qf ---

    // Configure a virtual display's properties.
    SituationConfigureVirtualDisplay :: proc(display_id: c.int, offset: Vector2, opacity: f32, z_order: c.int, visible: b8, frame_time_mult: f64, blend_mode: Situation_Blend_Mode) -> Situation_Error ---

    // Eat a key press this frame so later IsKeyPressed() returns false (e.g. for global hotkeys to take priority over app controls).
    SituationConsumeKeyPress :: proc(key: c.int) ---

    // Convert an 8-bit ColorRGBA struct to a normalized Vector4.
    SituationConvertColorToVector4 :: proc(c: Color_RGBA, out_normalized_color: ^Vector4) ---

    // Copy a file.
    SituationCopyFile :: proc(source_path: cstring, dest_path: cstring) -> Situation_Error ---

    SituationCreateASCIIFont :: proc(data: ^u8, cw: c.int, ch: c.int, out_font: ^Situation_Font) -> Situation_Error ---
    // Create a generic GPU data buffer (e.g., SSBO).
    SituationCreateBuffer :: proc(size: uint, initial_data: rawptr, usage_flags: Situation_Buffer_Usage_Flags, out_buffer: ^Situation_Buffer) -> Situation_Error ---

    SituationCreateCP437Font :: proc(font_data_8x16: ^u8, out_font: ^Situation_Font) -> Situation_Error ---
    // Create a compute pipeline from a shader file.
    SituationCreateComputePipeline :: proc(compute_shader_path: cstring, layout_type: Situation_Compute_Layout_Type, out_pipeline: ^Situation_Compute_Pipeline) -> Situation_Error ---

    // Create a compute pipeline from in-memory GLSL source.
    SituationCreateComputePipelineFromMemory :: proc(compute_shader_source: cstring, layout_type: Situation_Compute_Layout_Type, out_pipeline: ^Situation_Compute_Pipeline) -> Situation_Error ---

    // Create a directory, optionally creating parent directories.
    SituationCreateDirectory :: proc(dir_path: cstring, create_parents: b8) -> Situation_Error ---

    // Create a new audio processing graph.
    SituationCreateGraph :: proc() -> ^Situation_Audio_Graph ---

    // Allocates a new SituationImage container with UNINITIALIZED data.
    SituationCreateImage :: proc(width: c.int, height: c.int, channels: c.int, out_image: ^Situation_Image) -> Situation_Error ---

    // Create a mesh from vertex and index data.
    SituationCreateMesh :: proc(vertex_data: rawptr, vertex_count: c.int, vertex_stride: uint, index_data: ^u32, index_count: c.int, out_mesh: ^Situation_Mesh) -> Situation_Error ---

    // Create a mesh with an explicit vertex layout tag (includes SIT_MESH_LAYOUT_PULL).
    SituationCreateMeshEx :: proc(vertex_data: rawptr, vertex_count: c.int, vertex_stride: uint, index_data: ^u32, index_count: c.int, layout: Situation_Mesh_Vertex_Layout, out_mesh: ^Situation_Mesh) -> Situation_Error ---

    // Create a node of the given type in the graph.
    SituationCreateNode :: proc(graph: ^Situation_Audio_Graph, type: Situation_Node_Type, handle: ^Situation_Node_Handle) -> Situation_Error ---

    SituationCreateOutlinedPackedBitmapFont :: proc(packed_data: rawptr, config: ^Situation_Packed_Font, out_font: ^Situation_Font) -> Situation_Error ---
    SituationCreatePackedBitmapFont :: proc(packed_data: rawptr, config: ^Situation_Packed_Font, out_font: ^Situation_Font) -> Situation_Error ---
    // Connect an output port to an input port.
    SituationCreatePatch :: proc(graph: ^Situation_Audio_Graph, src: Situation_Node_Handle, src_port: c.int, dst: Situation_Node_Handle, dst_port: c.int, is_control: b8) -> Situation_Error ---

    // [Phase 1] Create an async GPU->CPU staging buffer.
    SituationCreateReadbackBuffer :: proc(size: uint, out_buffer: ^Situation_Buffer) -> Situation_Error ---

    SituationCreateTerminalFontEx :: proc(data: ^u8, char_width: c.int, char_height: c.int, char_count: c.int, chars_per_row: c.int, first_char: c.int, char_spacing: f32, line_spacing: f32, out_font: ^Situation_Font) -> Situation_Error ---
    SituationCreateTerminalFontFromMemory :: proc(data: ^u8, char_width: c.int, char_height: c.int, char_count: c.int, chars_per_row: c.int, first_char: c.int, out_font: ^Situation_Font) -> Situation_Error ---
    // Create a texture from a CPU-side image.
    SituationCreateTexture :: proc(image: Situation_Image, generate_mipmaps: b8, out_texture: ^Situation_Texture) -> Situation_Error ---

    // Create a texture with specific usage flags.
    SituationCreateTextureEx :: proc(image: Situation_Image, generate_mipmaps: b8, flags: Situation_Texture_Usage_Flags, out_texture: ^Situation_Texture) -> Situation_Error ---

    // Initializes the thread pool with dual-priority queues and worker threads.
    SituationCreateThreadPool :: proc(pool: ^Situation_Thread_Pool, num_threads: uint, queue_size: uint, hot_reload_rate: f64, disable_io: b8) -> Situation_Error ---

    SituationCreateVCRFont :: proc(font_data: ^u16, out_font: ^Situation_Font) -> Situation_Error ---
    SituationCreateVCRFontWithOutline :: proc(data: ^u16, outline_thickness: c.int, out_font: ^Situation_Font) -> Situation_Error ---
    SituationCreateVGA8x8Font :: proc(data: ^u8, out_font: ^Situation_Font) -> Situation_Error ---
    SituationCreateVGA8x8FontWithOutline :: proc(data: ^u8, outline_thickness: c.int, out_font: ^Situation_Font) -> Situation_Error ---
    // Create an off-screen render target.
    SituationCreateVirtualDisplay :: proc(resolution: Vector2, frame_time_mult: f64, z_order: c.int, scaling_mode: Situation_Scaling_Mode, blend_mode: Situation_Blend_Mode, out_id: ^c.int) -> Situation_Error ---

    // Create a virtual display with extended flags (e.g. COMPUTE_TARGET for compute shader writes).
    SituationCreateVirtualDisplayEx :: proc(resolution: Vector2, frame_time_mult: f64, z_order: c.int, scaling_mode: Situation_Scaling_Mode, blend_mode: Situation_Blend_Mode, flags: Situation_VD_Flags, out_id: ^c.int) -> Situation_Error ---

    // Create a virtual display from a full desc (VD-1 attachment config).
    SituationCreateVirtualDisplayFromDesc :: proc(desc: ^Situation_Virtual_Display_Desc, out_id: ^c.int) -> Situation_Error ---

    // Delete a directory, optionally deleting all its contents.
    SituationDeleteDirectory :: proc(dir_path: cstring, recursive: b8) -> Situation_Error ---

    // Delete a file.
    SituationDeleteFile :: proc(file_path: cstring) -> Situation_Error ---

    // Deserialize a graph from a JSON string.
    SituationDeserializeGraphFromJSON :: proc(graph: ^Situation_Audio_Graph, json_string: cstring, device_funcs: ^Situation_Device_Functions, num_device_funcs: c.int) -> Situation_Error ---

    // Destroy a GPU buffer.
    SituationDestroyBuffer :: proc(buffer: ^Situation_Buffer) ---

    // Destroy a compute pipeline and free its GPU resources.
    SituationDestroyComputePipeline :: proc(pipeline: ^Situation_Compute_Pipeline) ---

    // Destroy a graph and all its nodes/patches.
    SituationDestroyGraph :: proc(graph: ^Situation_Audio_Graph) ---

    // Unload a mesh from GPU memory.
    SituationDestroyMesh :: proc(mesh: ^Situation_Mesh) ---

    // Remove and destroy a node from the graph.
    SituationDestroyNode :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Disconnect a patch between two ports (legacy, no is_control param).
    SituationDestroyPatch :: proc(graph: ^Situation_Audio_Graph, src: Situation_Node_Handle, src_port: c.int, dst: Situation_Node_Handle, dst_port: c.int) -> Situation_Error ---

    // Unload a texture from GPU memory.
    SituationDestroyTexture :: proc(texture: ^Situation_Texture) ---

    // Shuts down the thread pool and releases resources.
    SituationDestroyThreadPool :: proc(pool: ^Situation_Thread_Pool) ---

    // Destroy a virtual display.
    SituationDestroyVirtualDisplay :: proc(display_id: c.int) -> Situation_Error ---

    // Detach a custom DSP processor from a sound.
    SituationDetachAudioProcessor :: proc(sound: ^Situation_Sound, processor: Situation_Audio_Processor_Callback, user_data: rawptr) -> Situation_Error ---

    // Check if a directory exists at the given path.
    SituationDirectoryExists :: proc(dir_path: cstring) -> b8 ---

    // Hide and lock the cursor, providing raw mouse motion.
    SituationDisableCursor :: proc() ---

    // Disable MIDI control for a node.
    SituationDisableMidiControl :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Disable MIDI Learn for a node.
    SituationDisableMidiLearn :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // Executes a loop in parallel across worker threads (Fork-Join).
    SituationDispatchParallel :: proc(pool: ^Situation_Thread_Pool, count: c.int, min_batch_size: c.int, user_data: rawptr) ---

    // Draws FPS, Latency, and Memory stats
    SituationDrawMetricsOverlay :: proc(cmd: Situation_Command_Buffer, position: Vector2, color: Color_RGBA) ---

    // Draws all sub-meshes of a model with a single root transformation.
    SituationDrawModel :: proc(cmd: Situation_Command_Buffer, model: Situation_Model, transform: mat4) -> Situation_Error ---

    // Prints the current task graph state to the stream.
    SituationDumpTaskGraph :: proc(pool: ^Situation_Thread_Pool, out_stream: ^FILE, json_mode: b8) ---

    // Metrics-only dump
    SituationDumpThreadPoolMetrics :: proc(pool: ^Situation_Thread_Pool, out_stream: ^FILE, json_mode: b8) ---

    // Pool metrics + per-role CPU snapshot
    SituationDumpThreadPoolStatus :: proc(pool: ^Situation_Thread_Pool, out_stream: ^FILE, json_mode: b8) ---

    // Status + topology line + pool dump
    SituationDumpThreadingReport :: proc(pool: ^Situation_Thread_Pool, out_stream: ^FILE, json_mode: b8) ---

    // Enable MIDI CC control for a node. Pass device_id=-1 for auto-select.
    SituationEnableMidiControl :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, device_id: c.int) -> Situation_Error ---

    // Enable MIDI Learn capability for a node. MIDI must already be enabled.
    SituationEnableMidiLearn :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> Situation_Error ---

    // [GL+VK] Submit all commands for the frame and present the result.
    SituationEndFrame :: proc() -> Situation_Error ---

    // [Caller frees via SituationFreeDeviceList] Canonical device enumeration.
    SituationEnumerateAudioDevices :: proc(out_count: ^c.int) -> ^Situation_Audio_Device_Info ---

    // Human-readable base label for an error code (from the errno table).
    SituationErrorToString :: proc(err: Situation_Error) -> cstring ---

    // Execute a shell command hidden, return exit code & combined output.
    SituationExecuteCommand :: proc() -> c.int ---

    // Export image data (.png, .bmp, .jpg, .tga, .hdr).
    SituationExportImage :: proc(image: Situation_Image) -> Situation_Error ---

    // Write a text-based frame time histogram into buf.
    SituationExportRenderHistogram :: proc(buf: cstring, buf_size: uint) ---

    // Check if a file exists at the given path.
    SituationFileExists :: proc(file_path: cstring) -> b8 ---

    // Find the best matching device by type and channel requirements.
    SituationFindBestDevice :: proc(preferred_type: Situation_Audio_Device_Type, min_channels_out: u32, min_channels_in: u32) -> ^Situation_Audio_Device_Info ---

    // Free a device list returned by SituationEnumerateAudioDevices.
    SituationFreeDeviceList :: proc(devices: ^Situation_Audio_Device_Info, count: c.int) ---

    // Free the memory allocated by SituationListDirectoryFiles.
    SituationFreeDirectoryFileList :: proc(file_list: [^]cstring, count: c.int) ---

    // Free a display info array returned by SituationGetDisplays.
    SituationFreeDisplays :: proc(displays: ^Situation_Display_Info, count: c.int) ---

    // Free a JSON string returned by SituationSerializeGraphToJSON.
    SituationFreeJSONString :: proc(json_string: cstring) ---

    // Free a process list returned by SituationGetProcessList().
    SituationFreeProcessList :: proc(list: ^Situation_Process_Info, count: c.int) ---

    // Free a string allocated by the library (e.g., from path helpers).
    SituationFreeString :: proc(str: cstring) ---

    // Generate a new image of a solid color.
    SituationGenImageColor :: proc(width: c.int, height: c.int, color: Color_RGBA, out_image: ^Situation_Image) -> Situation_Error ---

    // Generate a new image with a gradient.
    SituationGenImageGradient :: proc(width: c.int, height: c.int, tl: Color_RGBA, tr: Color_RGBA, bl: Color_RGBA, br: Color_RGBA, out_image: ^Situation_Image) -> Situation_Error ---

    // Get the name of the currently active playback device (static buffer, do not free).
    SituationGetActiveAudioDeviceName :: proc() -> cstring ---

    // Get the currently active audio processing graph (NULL if none).
    SituationGetActiveGraph :: proc() -> ^Situation_Audio_Graph ---

    // active_jobs counter
    SituationGetActiveJobCount :: proc(pool: ^Situation_Thread_Pool) -> c.int ---

    // Get a safe, persistent path for saving application data (caller must free).
    SituationGetAppSavePath :: proc(app_name: cstring) -> cstring ---

    // Get the value of an argument (e.g., "jungle" from "-level:jungle").
    SituationGetArgumentValue :: proc(arg_name: cstring) -> cstring ---

    SituationGetAudioDevices :: proc(count: ^c.int) -> ^Situation_Audio_Device_Info ---
    // Get the master volume for the audio device.
    SituationGetAudioMasterVolume :: proc() -> f32 ---

    // Get the sample rate of the current audio device.
    SituationGetAudioPlaybackSampleRate :: proc() -> c.int ---

    // Get the path to the directory containing the executable (caller must free).
    SituationGetBasePath :: proc() -> cstring ---

    // Read data from a GPU buffer (blocking).
    SituationGetBufferData :: proc(buffer: Situation_Buffer, offset: uint, size: uint, out_data: rawptr) -> Situation_Error ---

    // Retrieves the GPU device address of a buffer for bindless access.
    SituationGetBufferDeviceAddress :: proc(buffer: Situation_Buffer) -> u64 ---

    // Gets physical processors (Cores) from cached topology
    SituationGetCPUCoreCount :: proc() -> u32 ---

    // CPU name, core/thread counts, and clock speed.
    SituationGetCPUInfo :: proc(out: ^Situation_CPU_Info) ---

    // Logical processor count (cached topology).
    SituationGetCPUThreadCount :: proc() -> u32 ---

    // Get the display name for a device category.
    SituationGetCategoryName :: proc(category: Situation_Device_Category) -> cstring ---

    // Maps a physical key scancode (plus modifiers) to a Unicode character, respecting the current OS keyboard layout.
    SituationGetCharFromScancode :: proc(window: c.int, scancode: c.int, mods: c.int, out_char: ^u32) -> c.int ---

    // Get the next character from the text input queue.
    SituationGetCharPressed :: proc() -> c.uint ---

    // Get text from the system clipboard.
    SituationGetClipboardText :: proc(out_text: [^]cstring) -> Situation_Error ---

    // [VK] Get the compute-specific command buffer (Vulkan only).
    SituationGetComputeCommandBuffer :: proc() -> Situation_Command_Buffer ---

    // Effective audio mask (init or default)
    SituationGetConfiguredAudioThreadAffinity :: proc() -> u64 ---

    // Effective I/O mask (init or default CPU 3)
    SituationGetConfiguredIOThreadAffinity :: proc() -> u64 ---

    // Init mask for main thread (0 = no pin)
    SituationGetConfiguredMainThreadAffinity :: proc() -> u64 ---

    // Effective render mask (init or default)
    SituationGetConfiguredRenderThreadAffinity :: proc() -> u64 ---

    // Get the current value of a node's control parameter.
    SituationGetControl :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, control_id: u32, out_value: ^f32) -> Situation_Error ---

    // Pointer to cached topology (NULL on failure)
    SituationGetCpuTopology :: proc(out_topology: ^^Situation_Cpu_Topology) -> Situation_Error ---

    // Gets flags based on current GLFW window state
    SituationGetCurrentActualWindowStateFlags :: proc() -> u32 ---

    // Get the drive letter of the running executable (Windows only).
    SituationGetCurrentDriveLetter :: proc() -> c.char ---

    // Get the index of the monitor the window is on.
    SituationGetCurrentMonitor :: proc() -> c.int ---

    // Logical CPU index for current thread, or -1 if unknown
    SituationGetCurrentProcessorIndex :: proc() -> c.int ---

    SituationGetDeviceInfo :: proc() -> Situation_Device_Info ---
    // Get metadata for a registered device type.
    SituationGetDeviceMetadata :: proc(type: Situation_Node_Type, out_meta: ^Situation_Device_Metadata) -> Situation_Error ---

    // Get information for all displays (caller must free).
    SituationGetDisplays :: proc(out_displays: ^^Situation_Display_Info, out_count: ^c.int) -> Situation_Error ---

    // Number of draw commands this frame
    SituationGetDrawCallCount :: proc() -> u32 ---

    // Get info for a specific drive (Windows only).
    SituationGetDriveInfo :: proc(drive_letter: c.char, out_total_capacity_bytes: ^u64, out_free_space_bytes: ^u64, out_volume_name: cstring, volume_name_len: c.int) -> b8 ---

    // Get the current frames-per-second value.
    SituationGetFPS :: proc() -> c.int ---

    // Extract the file extension from a path.
    SituationGetFileExtension :: proc(file_path: cstring) -> cstring ---

    // Get the last modification time of a file (Unix timestamp).
    SituationGetFileModTime :: proc(file_path: cstring) -> c.long ---

    // Extract the file name (including extension) from a full path.
    SituationGetFileName :: proc(full_path: cstring) -> cstring ---

    // Count of detected frame spikes (general debugging aid)
    SituationGetFrameSpikeCount :: proc() -> u32 ---

    // Get the time in seconds for the last frame to complete (deltaTime).
    SituationGetFrameTime :: proc() -> f32 ---

    // Get the raw GLFW window handle.
    SituationGetGLFWwindow :: proc() -> ^GLF_Wwindow ---

    // GPU name and dedicated VRAM (when available).
    SituationGetGPUInfo :: proc(out: ^Situation_GPU_Info) ---

    // Get the name of the active GPU.
    SituationGetGPUName :: proc() -> cstring ---

    // Get the number of axes for a gamepad.
    SituationGetGamepadAxisCount :: proc(jid: c.int) -> c.int ---

    // Get the value of a gamepad axis (deadzone applied).
    SituationGetGamepadAxisValue :: proc(jid: c.int, axis: c.int) -> f32 ---

    // Get the next gamepad button from the press queue.
    SituationGetGamepadButtonPressed :: proc() -> c.int ---

    SituationGetGraphicsBackend :: proc() -> Situation_Graphics_Backend ---
    SituationGetGraphicsBackendName :: proc() -> cstring ---
    // Get backend capabilities for examples/frameworks.
    SituationGetGraphicsCaps :: proc(out_caps: ^Situation_Graphics_Caps) ---

    // High-priority queue depth
    SituationGetHighQueueDepth :: proc(pool: ^Situation_Thread_Pool) -> uint ---

    // [v2.3.37] Get the current depth of the IO/Low Priority queue
    SituationGetIOQueueDepth :: proc() -> uint ---

    // Query the current initialization state (thread-safe).
    SituationGetInitState :: proc() -> Situation_Init_State ---

    // Number of input devices (keyboard/mouse/gamepad).
    SituationGetInputDeviceCount :: proc() -> c.int ---

    SituationGetInputDeviceName :: proc(index: c.int, out_name: cstring, name_len: c.int) -> b8 ---
    // Returns pointer to the library's internal thread pool (NULL if not initialized).
    SituationGetInternalThreadPool :: proc() -> ^Situation_Thread_Pool ---

    // Get the human-readable name of a joystick/gamepad.
    SituationGetJoystickName :: proc(jid: c.int) -> cstring ---

    // Get the next key from the press queue (no repeats).
    SituationGetKeyPressed :: proc() -> c.int ---

    // Get the next key and its scancode from the queue.
    SituationGetKeyPressedEx :: proc(out_scancode: ^c.int) -> c.int ---

    // Get the platform-specific scancode for a logical key.
    SituationGetKeyScancode :: proc(key: c.int) -> c.int ---

    // Get the SituationError enum from the most recent _SituationSetErrorFromCode call.
    SituationGetLastErrorCode :: proc() -> Situation_Error ---

    // Get the last error message as a string (caller must free).
    SituationGetLastErrorMsg :: proc(out_msg: [^]cstring) -> Situation_Error ---

    SituationGetLastFramePhases :: proc(backpressure_ns: ^u64, fence_wait_ns: ^u64, execute_ns: ^u64, present_ns: ^u64) ---
    // Get the time taken for the last virtual display composite pass.
    SituationGetLastVDCompositeTimeMS :: proc() -> f64 ---

    // [GL+VK] Get the primary command buffer for the current frame.
    SituationGetMainCommandBuffer :: proc() -> Situation_Command_Buffer ---

    // Get the render pass for the main window.
    SituationGetMainWindowRenderPass :: proc() -> Vk_Render_Pass ---

    // Last playback callback block: peak sample magnitude & RMS (optional pointers; safe from main/UI thread).
    SituationGetMasterOutputMeter :: proc(out_peak: ^f32, out_rms: ^f32) ---

    // Query maximum compute work group count per dispatch.
    SituationGetMaxComputeWorkGroups :: proc(x: ^u32, y: ^u32, z: ^u32) ---

    // Highest observed frame delta (general spike debugging)
    SituationGetMaxFrameTime :: proc() -> f64 ---

    // Total and available physical RAM.
    SituationGetMemoryInfo :: proc(out: ^Situation_Memory_Info) ---

    // Get raw vertex/index data pointers from a mesh (read-only).
    SituationGetMeshData :: proc(mesh: Situation_Mesh, vertex_data: ^rawptr, vertex_count: ^c.int, vertex_stride: ^c.int, index_data: ^rawptr, index_count: ^c.int) ---

    // Retrieves the GPU device address of the mesh index buffer. [VK] requires SIT_FEATURE_BINDLESS_BUFFERS; [GL] NVIDIA-only via NV_shader_buffer_load. Returns 0 if unsupported.
    SituationGetMeshIndexBufferAddress :: proc(mesh: Situation_Mesh) -> u64 ---

    // GPU VA of mesh vertex buffer. [VK] SIT_FEATURE_BINDLESS_BUFFERS; pull draw: SituationCmdBindMeshPullBuffers + buffer_reference VS (see sit/gpu/vertex_pull.glslh).
    SituationGetMeshVertexBufferAddress :: proc(mesh: Situation_Mesh) -> u64 ---

    // Query layout tag stored at creation.
    SituationGetMeshVertexLayout :: proc(mesh: Situation_Mesh, out_layout: ^Situation_Mesh_Vertex_Layout) -> Situation_Error ---

    // PortMidi device name for device_id (hardware or virtual).
    SituationGetMidiDeviceName :: proc(device_id: c.int, out_name: cstring, out_name_size: uint) -> Situation_Error ---

    // Get the number of connected monitors.
    SituationGetMonitorCount :: proc() -> c.int ---

    // Get the height of a monitor's current video mode.
    SituationGetMonitorHeight :: proc(monitor_id: c.int) -> c.int ---

    // Get the human-readable name of a monitor.
    SituationGetMonitorName :: proc(monitor_id: c.int) -> cstring ---

    // Get the physical height of a monitor in millimeters.
    SituationGetMonitorPhysicalHeight :: proc(monitor_id: c.int) -> c.int ---

    // Get the physical width of a monitor in millimeters.
    SituationGetMonitorPhysicalWidth :: proc(monitor_id: c.int) -> c.int ---

    // Get the top-left position of a monitor on the desktop.
    SituationGetMonitorPosition :: proc(monitor_id: c.int) -> Vector2 ---

    // Get the refresh rate of a monitor.
    SituationGetMonitorRefreshRate :: proc(monitor_id: c.int) -> c.int ---

    // Get the width of a monitor's current video mode.
    SituationGetMonitorWidth :: proc(monitor_id: c.int) -> c.int ---

    // Get the mouse movement since the last frame.
    SituationGetMouseDelta :: proc() -> Vector2 ---

    // Get the mouse position within the window.
    SituationGetMousePosition :: proc() -> Vector2 ---

    // Get vertical mouse wheel movement.
    SituationGetMouseWheelMove :: proc() -> f32 ---

    // Get vertical and horizontal mouse wheel movement.
    SituationGetMouseWheelMoveV :: proc() -> Vector2 ---

    // Number of network adapters reported by the OS.
    SituationGetNetworkAdapterCount :: proc() -> c.int ---

    SituationGetNetworkAdapterName :: proc(index: c.int, out_name: cstring, name_len: c.int) -> b8 ---
    // Get a direct pointer to a node (for advanced use).
    SituationGetNode :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> ^Situation_Node ---

    // Query how many frames of space are available in the PCM_INPUT node's ring buffer.
    SituationGetNodePCMFreeFrames :: proc(graph: ^Situation_Audio_Graph, node: Situation_Node_Handle) -> u32 ---

    // Cached NUMA snapshot
    SituationGetNumaTopology :: proc(out_topology: ^^Situation_Numa_Topology) -> Situation_Error ---

    // Get operating system name, version, and build number.
    SituationGetOSInfo :: proc() -> Situation_OS_Info ---

    // TLS: node for current thread, or -1 if unset
    SituationGetPreferredNumaNode :: proc() -> c.int ---

    // Get snapshot of running OS processes. Caller must free with SituationFreeProcessList().
    SituationGetProcessList :: proc(out_count: ^c.int) -> ^Situation_Process_Info ---

    // Pending jobs per queue mask
    SituationGetQueueDepth :: proc(pool: ^Situation_Thread_Pool, mask: Situation_Job_Queue_Mask) -> uint ---

    // Sizing helper (no pool required)
    SituationGetRecommendedWorkerCount :: proc(reserved_threads: u32, use_physical_cores: b8) -> u32 ---

    // Get the number of registered audio device types.
    SituationGetRegisteredDeviceCount :: proc() -> c.int ---

    // Get the current render height (backbuffer size, considers HiDPI).
    SituationGetRenderHeight :: proc() -> c.int ---

    // Get render thread latency metrics
    SituationGetRenderLatencyStats :: proc(avg_ns: ^u64, max_ns: ^u64) ---

    // Get the current depth of the render queue
    SituationGetRenderQueueDepth :: proc() -> uint ---

    // Get the current render width (backbuffer size, considers HiDPI).
    SituationGetRenderWidth :: proc() -> c.int ---

    // Legacy — prefer SituationGetGraphicsBackend() + SituationGetGraphicsCaps().
    SituationGetRendererType :: proc() -> Situation_Renderer_Type ---

    // Get the current logical height of the window.
    SituationGetScreenHeight :: proc() -> c.int ---

    // Get the current logical width of the window.
    SituationGetScreenWidth :: proc() -> c.int ---

    // Get the current default screenshot format.
    SituationGetScreenshotFormat :: proc() -> Situation_Screenshot_Format ---

    // Get the current serialization format version string.
    SituationGetSerializationVersion :: proc() -> cstring ---

    // Get the stereo pan of a sound.
    SituationGetSoundPan :: proc(sound: ^Situation_Sound) -> f32 ---

    // Get the pitch of a sound.
    SituationGetSoundPitch :: proc(sound: ^Situation_Sound) -> f32 ---

    // Get the volume of a specific sound.
    SituationGetSoundVolume :: proc(sound: ^Situation_Sound) -> f32 ---

    SituationGetStorageDevice :: proc(index: c.int, out_name: cstring, name_len: c.int, out_capacity_bytes: ^u64, out_free_bytes: ^u64) -> b8 ---
    // Number of storage volumes reported by the OS.
    SituationGetStorageDeviceCount :: proc() -> c.int ---

    // Lines required for width constraint (grid/TTF).
    SituationGetTextLineCount :: proc(font: Situation_Font, max_width: f32) -> c.int ---

    // Retrieves the bindless texture handle (OpenGL Only).
    SituationGetTextureHandle :: proc(texture: Situation_Texture) -> u64 ---

    // [Phase 2] Query texture metadata.
    SituationGetTextureInfo :: proc(texture: Situation_Texture, out_info: ^Situation_Texture_Info) -> Situation_Error ---

    // Reads affinity mask for the CURRENT thread
    SituationGetThreadAffinity :: proc(out_mask: ^u64) -> Situation_Error ---

    // NUMA node for current thread, or -1 if unknown
    SituationGetThreadNumaNode :: proc() -> c.int ---

    // Scheduler counters snapshot
    SituationGetThreadPoolMetrics :: proc(pool: ^Situation_Thread_Pool, out_metrics: ^Situation_Thread_Pool_Metrics) -> Situation_Error ---

    // Worker/I/O/render/audio placement snapshot
    SituationGetThreadPoolSnapshot :: proc(pool: ^Situation_Thread_Pool, out: ^Situation_Thread_Pool_Snapshot) -> Situation_Error ---

    // Runtime threading capabilities + pool summary
    SituationGetThreadingStatus :: proc() -> Situation_Threading_Status ---

    // [Caller frees] Get the full path to the current user's home directory.
    SituationGetUserDirectory :: proc() -> cstring ---

    // Total GPU memory allocated (Bytes)
    SituationGetVRAMUsage :: proc() -> u64 ---

    // [Main thread] Returns a read-only static string (e.g., "2.4.336"). Do not free.
    SituationGetVersionString :: proc() -> cstring ---

    // Get a pointer to a virtual display's state.
    SituationGetVirtualDisplay :: proc(display_id: c.int) -> ^Situation_Virtual_Display ---

    // Copy current standby config (no-op if invalid id).
    SituationGetVirtualDisplayPatternConfig :: proc(display_id: c.int, out_config: ^Sit_Vd_Standby_Config) ---

    // Current standby layer bitmask (0 if invalid id).
    SituationGetVirtualDisplayPatternLayers :: proc(display_id: c.int) -> c.int ---

    // Get the internal resolution of a virtual display.
    SituationGetVirtualDisplaySize :: proc(display_id: c.int, width: ^c.int, height: ^c.int) ---

    // Get the VD's internal texture as a SituationTexture handle (valid for compute-target VDs).
    SituationGetVirtualDisplayTexture :: proc(display_id: c.int, out_texture: ^Situation_Texture) -> Situation_Error ---

    // Query last VD content write (not the frame clock).
    SituationGetVirtualDisplayUpdateInfo :: proc(display_id: c.int, out_last_content_update_time: ^f64, out_last_content_update_frame: ^u64, out_frames_since_update: ^u64, out_seconds_since_update: ^f64) -> Situation_Error ---

    // Get the raw Vulkan logical device handle.
    SituationGetVulkanDevice :: proc() -> Vk_Device ---

    // Get the raw Vulkan instance handle.
    SituationGetVulkanInstance :: proc() -> Vk_Instance ---

    // Get the raw Vulkan physical device handle.
    SituationGetVulkanPhysicalDevice :: proc() -> Vk_Physical_Device ---

    // Get the window's top-left position on the screen.
    SituationGetWindowPosition :: proc() -> Vector2 ---

    // Get the DPI scaling factor for the window.
    SituationGetWindowScaleDPI :: proc() -> Vector2 ---

    // Get the current logical window size.
    SituationGetWindowSize :: proc(width: ^c.int, height: ^c.int) ---

    // Check if the window is currently focused.
    SituationHasWindowFocus :: proc() -> b8 ---

    // Hide the mouse cursor.
    SituationHideCursor :: proc() ---

    // Converts a Hue, Saturation, Value color back to the standard RGBA color space.
    SituationHsvToRgb :: proc(hsv: Color_HSV) -> Color_RGBA ---

    // Control an image by Hue Saturation and Brightness.
    SituationImageAdjustHSV :: proc(hue_shift: f32, sat_factor: f32, val_factor: f32, mix: f32) ---

    // Grade an image in YPQ (phase/chroma/luma).
    SituationImageAdjustYPQ :: proc(phase_shift_deg: f32, chroma_factor: f32, luma_factor: f32, mix: f32) ---

    // Create a new image by copying another.
    SituationImageCopy :: proc(image: Situation_Image, out_image: ^Situation_Image) -> Situation_Error ---

    // Crop an image to a specific rectangle.
    SituationImageCrop :: proc(crop: Sit_Rectangle) ---

    // Copying portion of one image into another image at destination placement
    SituationImageDraw :: proc(src: Situation_Image, srcRect: Sit_Rectangle, dstPos: Vector2) ---

    // Draw a portion of a source image onto dst with alpha tinting.
    SituationImageDrawAlpha :: proc(src: Situation_Image, srcRect: Sit_Rectangle, dstPos: Vector2, tint: Color_RGBA) ---

    // Draw a single Unicode character with advanced styling onto an image.
    SituationImageDrawCodepoint :: proc(font: Situation_Font, codepoint: c.int, position: Vector2, fontSize: f32, rotationDegrees: f32, skewFactor: f32, fillColor: Color_RGBA, outlineColor: Color_RGBA, outlineThickness: f32) ---

    // Draw a simple, tinted text string onto an image.
    SituationImageDrawText :: proc(font: Situation_Font, position: Vector2, fontSize: f32, spacing: f32, tint: Color_RGBA) ---

    // Draw a text string with advanced styling (rotation, outline) onto an image.
    SituationImageDrawTextEx :: proc(font: Situation_Font, position: Vector2, fontSize: f32, spacing: f32, rotationDegrees: f32, skewFactor: f32, fillColor: Color_RGBA, outlineColor: Color_RGBA, outlineThickness: f32) ---

    // Flip an image.
    SituationImageFlip :: proc(mode: Situation_Image_Flip_Mode) ---

    // Resize an image using default bicubic scaling.
    SituationImageResize :: proc(newWidth: c.int, newHeight: c.int) ---

    SituationImageStampText :: proc(dst: ^Situation_Image, font: Situation_Font, text: cstring, pos: Vector2, fontSize: f32, text_color: Color_RGBA, bg_color: Color_RGBA) -> Situation_Error ---
    SituationImageStampTextBoxed :: proc(dst: ^Situation_Image, font: Situation_Font, text: cstring, bounds: Sit_Rectangle, fontSize: f32, text_color: Color_RGBA, bg_color: Color_RGBA, word_wrap: b8, out_width: ^c.int, out_height: ^c.int) -> Situation_Error ---
    // [Main thread] Initialize the library, create window and graphics context.
    SituationInit :: proc(argc: c.int, argv: [^]cstring, init_info: ^Situation_Init_Info) -> Situation_Error ---

    // Initialize the built-in device registry (call once at startup).
    SituationInitDeviceRegistry :: proc() ---

    // Check if the application is currently paused.
    SituationIsAppPaused :: proc() -> b8 ---

    // Check if a command-line argument (e.g., "-server") was provided.
    SituationIsArgumentPresent :: proc(arg_name: cstring) -> b8 ---

    // Check if the audio device is currently playing.
    SituationIsAudioDevicePlaying :: proc() -> b8 ---

    // Check if a device type is registered.
    SituationIsDeviceRegistered :: proc(type: Situation_Node_Type) -> b8 ---

    // Check if a graphics feature is supported on current hardware.
    SituationIsFeatureSupported :: proc(feature: Situation_Render_Feature) -> b8 ---

    // Check if a file was dropped into the window this frame.
    SituationIsFileDropped :: proc() -> b8 ---

    // Check if a connected joystick has a standard gamepad mapping.
    SituationIsGamepad :: proc(jid: c.int) -> b8 ---

    // Check if a gamepad button is currently held down (a state).
    SituationIsGamepadButtonDown :: proc(jid: c.int, button: c.int) -> b8 ---

    // Check if a gamepad button was pressed down this frame (an event).
    SituationIsGamepadButtonPressed :: proc(jid: c.int, button: c.int) -> b8 ---

    // Check if a gamepad button was released this frame (an event).
    SituationIsGamepadButtonReleased :: proc(jid: c.int, button: c.int) -> b8 ---

    // Check if an image has been loaded successfully.
    SituationIsImageValid :: proc(image: Situation_Image) -> b8 ---

    // [Main thread] Check if the library has been successfully initialized.
    SituationIsInitialized :: proc() -> b8 ---

    // Check if a joystick/gamepad is connected.
    SituationIsJoystickPresent :: proc(jid: c.int) -> b8 ---

    // Check if a key is currently held down (a state).
    SituationIsKeyDown :: proc(key: c.int) -> b8 ---

    // Check if a key was pressed down this frame (an event).
    SituationIsKeyPressed :: proc(key: c.int) -> b8 ---

    // Check if a key was released this frame (an event).
    SituationIsKeyReleased :: proc(key: c.int) -> b8 ---

    // Check if a key is currently up (a state).
    SituationIsKeyUp :: proc(key: c.int) -> b8 ---

    // Check if currently in learn mode. Returns 1/0.
    SituationIsLearning :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> c.int ---

    // Check if a lock key (Caps, Num) is currently active.
    SituationIsLockKeyPressed :: proc(lock_key_mod: c.int) -> b8 ---

    // Check if a node has MIDI control enabled. Returns 1/0.
    SituationIsMidiEnabled :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> c.int ---

    // Check if MIDI Learn is enabled. Returns 1/0.
    SituationIsMidiLearnEnabled :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle) -> c.int ---

    // Check if a modifier key (Shift, Ctrl, Alt) is pressed.
    SituationIsModifierPressed :: proc(modifier: c.int) -> b8 ---

    // Check if a mouse button is currently held down (a state).
    SituationIsMouseButtonDown :: proc(button: c.int) -> b8 ---

    // Check if a mouse button was pressed down this frame (an event).
    SituationIsMouseButtonPressed :: proc(button: c.int) -> b8 ---

    // Check if a mouse button was released this frame.
    SituationIsMouseButtonReleased :: proc(button: c.int) -> b8 ---

    // Check if a physical key (scancode) is currently held down.
    SituationIsScancodeDown :: proc(scancode: c.int) -> b8 ---

    // Check if Scroll Lock is currently toggled on.
    SituationIsScrollLockOn :: proc() -> b8 ---

    // True for stb_image decode extensions (.jpg, .png, .bmp, .tga, .psd, .gif, .hdr, .pic, .ppm, .pgm, .pnm).
    SituationIsStbImageLoadExtension :: proc(extension: cstring) -> b8 ---

    // Check if a serialized version is compatible with this library.
    SituationIsVersionCompatible :: proc(json_version: cstring) -> b8 ---

    // Check if a virtual display is marked as dirty.
    SituationIsVirtualDisplayDirty :: proc(display_id: c.int) -> b8 ---

    // Check if the window is currently in fullscreen mode.
    SituationIsWindowFullscreen :: proc() -> b8 ---

    // Check if the window is currently hidden.
    SituationIsWindowHidden :: proc() -> b8 ---

    // Check if the window is currently maximized.
    SituationIsWindowMaximized :: proc() -> b8 ---

    // Check if the window is currently minimized.
    SituationIsWindowMinimized :: proc() -> b8 ---

    // Check if the window was resized in the last frame.
    SituationIsWindowResized :: proc() -> b8 ---

    // Check if a specific window state flag is set.
    SituationIsWindowState :: proc(flag: u32) -> b8 ---

    // Join two path components with the correct OS separator (caller must free).
    SituationJoinPath :: proc(base_path: cstring, file_or_dir_name: cstring) -> cstring ---

    // Linear display light [0,1] → ST.2084 PQ [0,1].
    SituationLinearToPq :: proc(linear: f32) -> f32 ---

    // List files and subdirectories in a path (caller must free with SituationFreeDirectoryFileList).
    SituationListDirectoryFiles :: proc(dir_path: cstring, out_count: ^c.int) -> [^]cstring ---

    // List available MIDI input devices. Returns number found.
    SituationListMidiDevices :: proc(devices: ^Situation_Midi_Device_Info, max_count: c.int) -> c.int ---

    // Load audio and return a lightweight handle for playback control.
    SituationLoadAudio :: proc(file_path: cstring, mode: Situation_Audio_Load_Mode, looping: b8) -> Situation_Sound_Handle ---

    // Loads a raw bitmap font (e.g. 8x8 array).
    SituationLoadBitmapFontFromMemory :: proc(data: ^u8, char_width: c.int, char_height: c.int, num_chars: c.int, out_font: ^Situation_Font) -> Situation_Error ---

    // Grid atlas already on GPU — fills layout metadata.
    SituationLoadBitmapFontFromTexture :: proc(sheet: Situation_Texture, char_width: c.int, char_height: c.int, first_char: c.int, out_font: ^Situation_Font) -> Situation_Error ---

    SituationLoadComputeShader :: proc(cs_path: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---
    SituationLoadComputeShaderFromMemory :: proc(cs_code: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---
    // Get the paths of dropped files (returns a copy, caller must free).
    SituationLoadDroppedFiles :: proc(count: ^c.int) -> [^]cstring ---

    // Asynchronously load a file.
    SituationLoadFileAsync :: proc(pool: ^Situation_Thread_Pool, file_path: cstring, callback: Situation_File_Load_Callback, user_data: rawptr) -> Situation_Job_Id ---

    // Load an entire file into a memory buffer (caller must free).
    SituationLoadFileData :: proc(file_path: cstring, out_bytes_read: ^c.uint, out_data: ^^u8) -> Situation_Error ---

    // Load a text file into a null-terminated string (caller must free).
    SituationLoadFileText :: proc(file_path: cstring) -> cstring ---

    // Asynchronously load a text file.
    SituationLoadFileTextAsync :: proc(pool: ^Situation_Thread_Pool, file_path: cstring, callback: Situation_File_Text_Load_Callback, user_data: rawptr) -> Situation_Job_Id ---

    // Load a font from a TTF/OTF file for CPU rendering.
    SituationLoadFont :: proc(out_font: ^Situation_Font) -> Situation_Error ---

    // Loads a font directly from a memory buffer (e.g., embedded resource).
    SituationLoadFontFromMemory :: proc(data: rawptr, dataSize: c.int, out_font: ^Situation_Font) -> Situation_Error ---

    // Load a graph from a JSON file, re-creating nodes via device_funcs.
    SituationLoadGraphFromFile :: proc(graph: ^Situation_Audio_Graph, filepath: cstring, device_funcs: ^Situation_Device_Functions, num_device_funcs: c.int) -> Situation_Error ---

    // Load an image via stb_image (JPEG, PNG, BMP, TGA, PSD, GIF, HDR, PIC, PNM).
    SituationLoadImage :: proc(out_image: ^Situation_Image) -> Situation_Error ---

    // Load an image from a memory buffer.
    SituationLoadImageFromMemory :: proc(dataSize: c.int, out_image: ^Situation_Image) -> Situation_Error ---

    // Get a copy of the current screen backbuffer as an image.
    SituationLoadImageFromScreen :: proc(out_image: ^Situation_Image) -> Situation_Error ---

    // Load MIDI Learn mappings from JSON file.
    SituationLoadMidiPreset :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, filename: cstring) -> Situation_Error ---

    // Loads a complete 3D model and its textures from a GLTF file.
    SituationLoadModel :: proc(file_path: cstring, out_model: ^Situation_Model) -> Situation_Error ---

    // Wavefront OBJ: triangulated meshes, MTL/textures; missing/degenerate normals filled from face geometry, authored normals preserved.
    SituationLoadModelFromOBJ :: proc(file_path: cstring, out_model: ^Situation_Model) -> Situation_Error ---

    // Loads a 3D model from a binary or ASCII STL file. UVs are zeroed; normals are flat (per-face) by default, or smooth (averaged per shared vertex) when smooth_normals is true.
    SituationLoadModelFromSTL :: proc(file_path: cstring, smooth_normals: b8, out_model: ^Situation_Model) -> Situation_Error ---

    // Load a graphics shader pipeline from vertex and fragment files.
    SituationLoadShader :: proc(vs_path: cstring, fs_path: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---

    // Create a graphics shader pipeline from in-memory GLSL source.
    SituationLoadShaderFromMemory :: proc(vs_code: cstring, fs_code: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---

    // Precompiled .spv: OpenGL via GL_ARB_gl_spirv; Vulkan same pipeline contract as SituationLoadShaderFromMemory (no shaderc required).
    SituationLoadShaderFromSpirv :: proc(vs_spv_path: cstring, fs_spv_path: cstring, out_shader: ^Situation_Shader) -> Situation_Error ---

    // Same as SituationLoadShaderFromSpirv but from in-memory SPIR-V (e.g. build-time embedded .spv). No hot-reload paths (vs/fs file paths left unset).
    SituationLoadShaderFromSpirvMemory :: proc(vs_spirv: rawptr, vs_len: uint, fs_spirv: rawptr, fs_len: uint, out_shader: ^Situation_Shader) -> Situation_Error ---

    // [Vulkan] `layout_profile` selects user SSBO/UBO layouts; [OpenGL] profile ignored.
    SituationLoadShaderFromSpirvMemoryEx :: proc(vs_spirv: rawptr, vs_len: uint, fs_spirv: rawptr, fs_len: uint, layout_profile: Situation_Spirv_Layout_Profile, out_shader: ^Situation_Shader) -> Situation_Error ---

    // Load a sound from a file.
    SituationLoadSoundFromFile :: proc(file_path: cstring, mode: Situation_Audio_Load_Mode, looping: b8, out_sound: ^Situation_Sound) -> Situation_Error ---

    // Asynchronously loads and decodes a sound file.
    SituationLoadSoundFromFileAsync :: proc(pool: ^Situation_Thread_Pool, file_path: cstring, looping: b8, out_sound: ^Situation_Sound) -> Situation_Job_Id ---

    // Load a sound from a custom stream.
    SituationLoadSoundFromStream :: proc(on_read: Situation_Stream_Read_Callback, on_seek: Situation_Stream_Seek_Callback, user_data: rawptr, format: ^Situation_Audio_Format, looping: b8, out_sound: ^Situation_Sound) -> Situation_Error ---

    // Loads a texture from disk and registers the path for hot-reloading.
    SituationLoadTexture :: proc(file_path: cstring, generate_mipmaps: b8, out_texture: ^Situation_Texture) -> Situation_Error ---

    // Maximize the window if it's resizable.
    SituationMaximizeWindow :: proc() ---

    // Measure the pixel dimensions of a string before drawing.
    SituationMeasureText :: proc(font: Situation_Font, fontSize: f32) -> Sit_Rectangle ---

    // Measure with extra per-character spacing.
    SituationMeasureTextEx :: proc(font: Situation_Font, fontSize: f32, spacing: f32) -> Sit_Rectangle ---

    SituationMemoryBarrier :: proc(cmd: Situation_Command_Buffer, barrier_bits: u32) ---
    // Minimize the window (iconify).
    SituationMinimizeWindow :: proc() ---

    // Move/rename a file, even across drives on Windows.
    SituationMoveFile :: proc(old_path: cstring, new_path: cstring) -> Situation_Error ---

    // Open a file or folder with its default application.
    SituationOpenFile :: proc(filePath: cstring) ---

    // Pause the application's internal state (e.g., audio).
    SituationPauseApp :: proc() ---

    // Pause audio playback on the device.
    SituationPauseAudioDevice :: proc() -> Situation_Error ---

    // Peek at the next key in the press queue without consuming it.
    SituationPeekKeyPressed :: proc() -> c.int ---

    // Peek at the next key and its scancode.
    SituationPeekKeyPressedEx :: proc(out_scancode: ^c.int) -> c.int ---

    // Play audio by handle (restarts if already playing).
    SituationPlayAudio :: proc(handle: Situation_Sound_Handle) -> Situation_Error ---

    // Play a loaded sound (restarts if already playing).
    SituationPlayLoadedSound :: proc(sound: ^Situation_Sound) -> Situation_Error ---

    // Legacy: play a tone by MIDI note number (0-127).
    SituationPlayMidiNote :: proc(note: c.int, type: Situation_Wave_Type, volume: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) ---

    // Legacy: play a simple ADSR tone (backward compat / quick UI sounds).
    SituationPlayTone :: proc(type: Situation_Wave_Type, frequency: f32, volume: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) ---

    // @brief Plays an extended procedural tone with full control. @param type          Waveform type (Sine, Square, Triangle, Saw, Noise) @param frequency     Frequency in Hz (e.g., 440.0f). For noise: ignored (use 0.0f) @param volume        Peak volume (0.0 to 1.0) @param pan           Stereo panning (-1.0 left, 0.0 center, +1.0 right) @param attack_sec    Attack time in seconds @param decay_sec     Decay time in seconds @param sustain_level Sustain volume level (0.0 to 1.0) @param release_sec   Release time in seconds @param hold_sec      Hold duration in seconds. Use -1.0f for infinite sustain (key down) @return Handle to the playing tone, or 0 if no voice available (polyphony limit)
    SituationPlayToneEx :: proc(type: Situation_Wave_Type, frequency: f32, volume: f32, pan: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) -> Situation_Tone_Handle ---

    // [Main thread] Poll for all input events (keyboard, mouse, joystick). Call once per frame.
    SituationPollInputEvents :: proc() ---

    // SITUATION_SUCCESS when ready, SITUATION_ERROR_SHADER_LOAD_IN_PROGRESS while compiling/linking/building pipelines.
    SituationPollShaderLoad :: proc(shader: Situation_Shader) -> Situation_Error ---

    // Uniform PQ gray → A2R10G10B10 packed pixel.
    SituationPqGrayToRgb10Packed :: proc(pq_level: f32) -> u32 ---

    // ST.2084 PQ [0,1] → linear display light [0,1].
    SituationPqToLinear :: proc(pq: f32) -> f32 ---

    // Human-readable threading status (stdout if NULL)
    SituationPrintThreadingStatus :: proc(out_stream: ^FILE) ---

    // Push interleaved float PCM into a PCM_INPUT node's ring buffer (any thread). Returns frames written.
    SituationPushNodePCM :: proc(graph: ^Situation_Audio_Graph, node: Situation_Node_Handle, samples: ^f32, frame_count: u32, channels: u32) -> u32 ---

    // [OpenGL] Enumerate all active SSBO blocks and their assigned binding points. out_count receives actual block count (may exceed capacity). Returns NOT_IMPLEMENTED on Vulkan.
    SituationQueryShaderStorageBlocks :: proc(shader: Situation_Shader, out_blocks: ^Situation_Shader_Storage_Block_Info, capacity: c.int, out_count: ^c.int) -> Situation_Error ---

    // Read mapped buffer data safely.
    SituationReadBuffer :: proc(readback_buf: Situation_Buffer, dst: rawptr, size: uint) -> Situation_Error ---

    // [Phase 2] Blocking readback of framebuffer pixels (RGBA8 or raw RGB10 packed).
    SituationReadFramebuffer :: proc(desc: ^Situation_Read_Pixels_Desc, dst_pixels: rawptr, dst_size_bytes: uint) -> Situation_Error ---

    // [Phase 8] Raw A2R10G10B10 readback when HDR10 swapchain active.
    SituationReadFramebufferHdr :: proc(desc: ^Situation_Read_Pixels_Desc, dst_pixels: ^u32, dst_size_bytes: uint) -> Situation_Error ---

    // [Phase 2] Blocking readback of texture pixels.
    SituationReadTexture :: proc(texture: Situation_Texture, desc: ^Situation_Texture_Readback_Desc, dst_pixels: rawptr, dst_size_bytes: uint) -> Situation_Error ---

    // [Phase 2] Blocking readback into allocated SituationImage.
    SituationReadTextureAlloc :: proc(texture: Situation_Texture, desc: ^Situation_Texture_Readback_Desc, out_image: ^Situation_Image) -> Situation_Error ---

    // Rebuilds the process-wide topology cache
    SituationRefreshCpuTopology :: proc() -> Situation_Error ---

    // Force a refresh of the cached display information.
    SituationRefreshDisplays :: proc() ---

    // Rebuild NUMA summary from CPU topology + OS memory
    SituationRefreshNumaTopology :: proc() -> Situation_Error ---

    // Register a custom device type with the registry.
    SituationRegisterDeviceType :: proc(meta: ^Situation_Device_Metadata) -> Situation_Error ---

    // Recompiles a compute pipeline from its original source file (Synchronous/Stalls GPU).
    SituationReloadComputePipeline :: proc(pipeline: ^Situation_Compute_Pipeline) -> Situation_Error ---

    // Re-parses GLTF/GLB file and rebuilds all meshes and textures (Synchronous/Stalls GPU).
    SituationReloadModel :: proc(model: ^Situation_Model) -> Situation_Error ---

    // Recompiles and links a shader from its original source files (Synchronous/Stalls GPU).
    SituationReloadShader :: proc(shader: ^Situation_Shader) -> Situation_Error ---

    // Re-reads image file and recreates the GPU texture resource (Synchronous/Stalls GPU).
    SituationReloadTexture :: proc(texture: ^Situation_Texture) -> Situation_Error ---

    // Disconnect a specific patch between two ports.
    SituationRemovePatch :: proc(graph: ^Situation_Audio_Graph, src: Situation_Node_Handle, src_port: c.int, dst: Situation_Node_Handle, dst_port: c.int, is_control: b8) -> Situation_Error ---

    // Alias for SituationMoveFile.
    SituationRenameFile :: proc(old_path: cstring, new_path: cstring) -> Situation_Error ---

    // Fill pass struct from VD attachment defaults (tier C helper).
    SituationRenderPassInfoInherit :: proc(display_id: c.int) -> Situation_Render_Pass_Info ---

    // Composite all visible virtual displays to the current target.
    SituationRenderVirtualDisplays :: proc(cmd: Situation_Command_Buffer) -> Situation_Error ---

    // Replay a previously recorded render list into a command buffer.
    SituationReplayRenderList :: proc(cmd: Situation_Command_Buffer, list: Situation_Render_List) ---

    SituationRequestScreenCapture :: proc() ---
    // Reset a render list for reuse next frame.
    SituationResetRenderList :: proc(list: Situation_Render_List) ---

    // Zero scheduler counters
    SituationResetThreadPoolStats :: proc(pool: ^Situation_Thread_Pool) ---

    // Restore a minimized or maximized window.
    SituationRestoreWindow :: proc() ---

    // Resume a paused application.
    SituationResumeApp :: proc() ---

    // Resume audio playback on the device.
    SituationResumeAudioDevice :: proc() -> Situation_Error ---

    // Upscale 8-bit RGBA → 10-bit.
    SituationRgb10FromRgba :: proc(color: Color_RGBA) -> Color_RGBA10 ---

    // Converts a standard RGBA color to the Hue, Saturation, Value color space.
    SituationRgbToHsv :: proc(rgb: Color_RGBA) -> Color_HSV ---

    // 10-bit RGBA → float YPQ.
    SituationRgbToYpqFrom10 :: proc(color: Color_RGBA10) -> Color_YP_Qf ---

    // Downscale 10-bit RGBA → 8-bit.
    SituationRgbaFromRgb10 :: proc(color: Color_RGBA10) -> Color_RGBA ---

    // A2R10G10B10 texel → RGBA8 (readback parity).
    SituationRgbaFromRgb10Packed :: proc(packed: u32) -> Color_RGBA ---

    // Asynchronously save a file.
    SituationSaveFileAsync :: proc(pool: ^Situation_Thread_Pool, file_path: cstring, data: rawptr, size: uint, callback: Situation_File_Save_Callback, user_data: rawptr) -> Situation_Job_Id ---

    // Save a block of memory to a file.
    SituationSaveFileData :: proc(file_path: cstring, data: rawptr, bytes_to_write: c.uint) -> Situation_Error ---

    // Save a null-terminated string to a text file.
    SituationSaveFileText :: proc(file_path: cstring, text: cstring) -> Situation_Error ---

    // Asynchronously save a text file.
    SituationSaveFileTextAsync :: proc(pool: ^Situation_Thread_Pool, file_path: cstring, text: cstring, callback: Situation_File_Save_Callback, user_data: rawptr) -> Situation_Job_Id ---

    // Save a graph to a JSON file.
    SituationSaveGraphToFile :: proc(graph: ^Situation_Audio_Graph, filepath: cstring) -> Situation_Error ---

    // Save MIDI Learn mappings to JSON file.
    SituationSaveMidiPreset :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, filename: cstring) -> Situation_Error ---

    // Exports a model to a human-readable .gltf and a .bin file for debugging.
    SituationSaveModelAsGltf :: proc(model: Situation_Model, file_path: cstring) -> Situation_Error ---

    // Serialize a graph to a JSON string (caller must free with SituationFreeJSONString).
    SituationSerializeGraphToJSON :: proc(graph: ^Situation_Audio_Graph) -> cstring ---

    // Set the active audio processing graph (replaces default). NULL disables graph processing.
    SituationSetActiveGraph :: proc(graph: ^Situation_Audio_Graph) -> Situation_Error ---

    // Set the active audio device.
    SituationSetAudioDevice :: proc(internal_id: c.int, format: ^Situation_Audio_Format) -> Situation_Error ---

    // Set the master volume for the audio device.
    SituationSetAudioMasterVolume :: proc(volume: f32) -> Situation_Error ---

    // Set a callback to receive mixed output samples (for VU meters, FFT, etc.).
    SituationSetAudioOutputMonitor :: proc(user_data: rawptr) ---

    // Set stereo pan for a handle-based sound [-1.0 to 1.0].
    SituationSetAudioPan :: proc(handle: Situation_Sound_Handle, pan: f32) -> Situation_Error ---

    // Set pitch multiplier for a handle-based sound (1.0 = normal).
    SituationSetAudioPitch :: proc(handle: Situation_Sound_Handle, pitch: f32) -> Situation_Error ---

    // Re-initialize the audio device with a new sample rate.
    SituationSetAudioPlaybackSampleRate :: proc(sample_rate: c.int) -> Situation_Error ---

    // Set volume for a handle-based sound [0.0 to 1.0+].
    SituationSetAudioVolume :: proc(handle: Situation_Sound_Handle, volume: f32) -> Situation_Error ---

    // Set text in the system clipboard.
    SituationSetClipboardText :: proc(text: cstring) -> Situation_Error ---

    // Set a control parameter on a node.
    SituationSetControl :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, control_id: u32, value: f32) -> Situation_Error ---

    // OS-visible name for the calling thread (UTF-8); no-op if NULL/empty
    SituationSetCurrentThreadName :: proc(name: cstring) ---

    // Set the mouse cursor to a standard shape.
    SituationSetCursor :: proc(cursor: Situation_Cursor) ---

    // Set a callback for mouse movement events.
    SituationSetCursorPosCallback :: proc(callback: Situation_Cursor_Pos_Callback, user_data: rawptr) ---

    // Set the display mode for a monitor.
    SituationSetDisplayMode :: proc(monitor_id: c.int, mode: ^Situation_Display_Mode, fullscreen: b8) -> Situation_Error ---

    // Set a callback to run just before shutdown.
    SituationSetExitCallback :: proc(user_data: rawptr) ---

    // Set a callback for file drop events.
    SituationSetFileDropCallback :: proc(callback: Situation_File_Drop_Callback, user_data: rawptr) ---

    // Set a callback for window focus events.
    SituationSetFocusCallback :: proc(callback: Situation_Focus_Callback, user_data: rawptr) ---

    // Load a new set of gamepad mappings from a string.
    SituationSetGamepadMappings :: proc() -> c.int ---

    // Set gamepad vibration/rumble (Windows only).
    SituationSetGamepadVibration :: proc(jid: c.int, left_motor: f32, right_motor: f32) -> b8 ---

    // Designate the Sound Source node in the active graph to receive routed SFX tones.
    SituationSetGraphSFXSource :: proc(handle: Situation_Node_Handle) -> Situation_Error ---

    // Set a callback for joystick connection events.
    SituationSetJoystickCallback :: proc(callback: Situation_Joystick_Callback, user_data: rawptr) ---

    // Set a callback for key events.
    SituationSetKeyCallback :: proc(callback: Situation_Key_Callback, user_data: rawptr) ---

    // Set a callback for window maximize / restore events.
    SituationSetMaximizeCallback :: proc(callback: Situation_Maximize_Callback, user_data: rawptr) ---

    // Set a callback for mouse button events.
    SituationSetMouseButtonCallback :: proc(callback: Situation_Mouse_Button_Callback, user_data: rawptr) ---

    // Set a software offset for the mouse position.
    SituationSetMouseOffset :: proc(offset: Vector2) ---

    // Set the mouse position within the window.
    SituationSetMousePosition :: proc(pos: Vector2) ---

    // Set a software scale for the mouse position and delta.
    SituationSetMouseScale :: proc(scale: Vector2) ---

    // Filter MIDI to channel 0-15, or -1 omni.
    SituationSetNodeMidiChannel :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, channel: c.int) -> Situation_Error ---

    // Helper to set a specific pixel color (CPU-side).
    SituationSetPixelColor :: proc(x: c.int, y: c.int, col: Color_RGBA) ---

    // Set a callback for window framebuffer resize events.
    SituationSetResizeCallback :: proc(user_data: rawptr) ---

    // Set the default screenshot file format (default: BMP).
    SituationSetScreenshotFormat :: proc(format: Situation_Screenshot_Format) ---

    // Set a callback for mouse scroll events.
    SituationSetScrollCallback :: proc(callback: Situation_Scroll_Callback, user_data: rawptr) ---

    // [OpenGL] Set a standalone uniform by name (location cache). While a frame is active, defers to SIT_OP_SET_UNIFORM.
    SituationSetShaderUniform :: proc(shader: Situation_Shader, uniform_name: cstring, data: rawptr, type: Situation_Uniform_Type) -> Situation_Error ---

    // [OpenGL] Set float uniform array.
    SituationSetShaderUniform1fv :: proc(shader: Situation_Shader, uniform_name: cstring, count: c.int, values: ^f32) -> Situation_Error ---

    // [OpenGL] Set int uniform array in one call (e.g. name "uWallRows[0]", count=24). While a frame is active, records SIT_OP_SET_UNIFORM (same as render-thread mode).
    SituationSetShaderUniform1iv :: proc(shader: Situation_Shader, uniform_name: cstring, count: c.int, values: ^c.int) -> Situation_Error ---

    // [OpenGL] Set uniform by explicit location (SPIR-V layout(location=)); defers during frames like SituationSetShaderUniform.
    SituationSetShaderUniformLocation :: proc(shader: Situation_Shader, location: c.int, data: rawptr, type: Situation_Uniform_Type) -> Situation_Error ---

    // [OpenGL] Set mat4 uniform array.
    SituationSetShaderUniformMatrix4fv :: proc(shader: Situation_Shader, uniform_name: cstring, count: c.int, matrices: ^mat4) -> Situation_Error ---

    // Apply an echo effect to a sound.
    SituationSetSoundEcho :: proc(sound: ^Situation_Sound, enabled: b8, delay_sec: f32, feedback: f32, wet_mix: f32) -> Situation_Error ---

    // Apply a low-pass or high-pass filter to a sound.
    SituationSetSoundFilter :: proc(sound: ^Situation_Sound, type: Situation_Filter_Type, cutoff_hz: f32, q_factor: f32) -> Situation_Error ---

    // Set the stereo pan for a sound [-1.0 to 1.0].
    SituationSetSoundPan :: proc(sound: ^Situation_Sound, pan: f32) -> Situation_Error ---

    // Set the pitch for a sound (resamples).
    SituationSetSoundPitch :: proc(sound: ^Situation_Sound, pitch: f32) -> Situation_Error ---

    // Apply a reverb effect to a sound.
    SituationSetSoundReverb :: proc(sound: ^Situation_Sound, enabled: b8, room_size: f32, damping: f32, wet_mix: f32, dry_mix: f32) -> Situation_Error ---

    // Set the volume for a specific sound.
    SituationSetSoundVolume :: proc(sound: ^Situation_Sound, volume: f32) -> Situation_Error ---

    // Set a desired frame rate cap (0 for uncapped).
    SituationSetTargetFPS :: proc(fps: c.int) ---

    // [Phase 2] Update sampler state.
    SituationSetTextureSamplerParams :: proc(texture: Situation_Texture, min_filter: Situation_Texture_Filter, mag_filter: Situation_Texture_Filter, wrap_s: Situation_Texture_Wrap, wrap_t: Situation_Texture_Wrap) -> Situation_Error ---

    // Pins the CURRENT thread (logical CPU bitmask, bits 0..63)
    SituationSetThreadAffinity :: proc(core_mask: u64) -> Situation_Error ---

    // Set affinity; optional previous mask
    SituationSetThreadAffinityEx :: proc(core_mask: u64, out_previous: ^u64) -> Situation_Error ---

    // Set the period of an oscillator.
    SituationSetTimerOscillatorPeriod :: proc(oscillator_id: c.int, period_seconds: f64) -> Situation_Error ---

    // Route a procedural tone to the active graph's SFX sound source.
    SituationSetToneRouting :: proc(handle: Situation_Tone_Handle, route_to_graph: b8) -> Situation_Error ---

    // Set the minimum log level for output filtering.
    SituationSetTraceLogLevel :: proc(logType: c.int) ---

    // Enable or disable VSync (vertical synchronization).
    SituationSetVSync :: proc(enable: b8) ---

    // Tier B storage-only attachment defaults.
    SituationSetVirtualDisplayAttachmentDefaults :: proc(display_id: c.int, defaults: ^Situation_Virtual_Display_Attachment_Defaults) -> Situation_Error ---

    // Mark a virtual display as needing to be re-rendered.
    SituationSetVirtualDisplayDirty :: proc(display_id: c.int, is_dirty: b8) ---

    // SOLID idle tint (normalized by compositor).
    SituationSetVirtualDisplayFallbackColor :: proc(display_id: c.int, color: Color_RGBA) ---

    // SOLID, COLORBURST, or PATTERN when idle.
    SituationSetVirtualDisplayFallbackMode :: proc(display_id: c.int, mode: Situation_VD_Fallback_Mode) ---

    // Set idle threshold for compositor fallback (Phase 2a).
    SituationSetVirtualDisplayIdleThreshold :: proc(display_id: c.int, threshold_seconds: f64) ---

    // Full standby tuning + PATTERN mode.
    SituationSetVirtualDisplayPatternConfig :: proc(display_id: c.int, config: ^Sit_Vd_Standby_Config) ---

    // Toggle bitmask + PATTERN fallback (plan §3.4).
    SituationSetVirtualDisplayPatternLayers :: proc(display_id: c.int, pattern_layers: c.int) ---

    // Set the scaling/filtering mode for a virtual display.
    SituationSetVirtualDisplayScalingMode :: proc(display_id: c.int, scaling_mode: Situation_Scaling_Mode) -> Situation_Error ---

    // Set the window to be focused.
    SituationSetWindowFocused :: proc() ---

    // Set the icon for the window (single image).
    SituationSetWindowIcon :: proc(image: Situation_Image) ---

    // Set the icon for the window (multiple sizes).
    SituationSetWindowIcons :: proc(count: c.int) ---

    // Set the window maximum dimensions.
    SituationSetWindowMaxSize :: proc(width: c.int, height: c.int) ---

    // Set the window minimum dimensions.
    SituationSetWindowMinSize :: proc(width: c.int, height: c.int) ---

    // Set the window to be fullscreen on a specific monitor.
    SituationSetWindowMonitor :: proc(monitor_id: c.int) ---

    // Set window opacity [0.0f to 1.0f].
    SituationSetWindowOpacity :: proc(opacity: f32) ---

    // Set the window position on the screen.
    SituationSetWindowPosition :: proc(x: c.int, y: c.int) ---

    // Set the window dimensions.
    SituationSetWindowSize :: proc(width: c.int, height: c.int) ---

    // Set window configuration state using flags (additive).
    SituationSetWindowState :: proc(flags: u32) ---

    // Set the flag profiles for when the window is focused vs. unfocused.
    SituationSetWindowStateProfiles :: proc(active_flags: u32, inactive_flags: u32) -> Situation_Error ---

    // Set the title for the window.
    SituationSetWindowTitle :: proc() ---

    // Create connected virtual out→in pair. Returns input device_id for SituationEnableMidiControl().
    SituationSetupVirtualMidiLoopback :: proc(out_input_device_id: ^c.int) -> Situation_Error ---

    // Show the mouse cursor.
    SituationShowCursor :: proc() ---

    // Blocking UI message box; for fatal init errors.
    SituationShowMessageBox :: proc(title: cstring, message: cstring) ---

    // [Main thread] Shut down the library and release all resources.
    SituationShutdown :: proc() ---

    // Create a new sound by copying the raw PCM data from a source.
    SituationSoundCopy :: proc(source: ^Situation_Sound, out_destination: ^Situation_Sound) -> Situation_Error ---

    // Crop a sound's PCM data in-place to a new range.
    SituationSoundCrop :: proc(sound: ^Situation_Sound, initFrame: u64, finalFrame: u64) -> Situation_Error ---

    // Export the sound's raw PCM data to a WAV file.
    SituationSoundExportAsWav :: proc(sound: ^Situation_Sound, fileName: cstring) -> Situation_Error ---

    // Start capturing audio input with default format.
    SituationStartAudioCapture :: proc(callback: Situation_Audio_Capture_Callback, user_data: rawptr) -> Situation_Error ---

    // Start capturing with explicit sample rate and channel count.
    SituationStartAudioCaptureEx :: proc(callback: Situation_Audio_Capture_Callback, user_data: rawptr, sample_rate: u32, channels: u32) -> Situation_Error ---

    // Start learning: next CC received maps to this param. Scaling: 0=linear, 1=log, 2=dB, 3=discrete. Times out after 5s.
    SituationStartMidiLearn :: proc(graph: ^Situation_Audio_Graph, handle: Situation_Node_Handle, control_index: c.int, param_name: cstring, min_value: f32, max_value: f32, scaling: c.int) -> Situation_Error ---

    // Stop all currently playing sounds.
    SituationStopAllLoadedSounds :: proc() -> Situation_Error ---

    // Stop all active tones (triggers release on each).
    SituationStopAllTones :: proc() ---

    // Stop audio capture and release the input device.
    SituationStopAudioCapture :: proc() ---

    // Stop a specific sound from playing.
    SituationStopLoadedSound :: proc(sound: ^Situation_Sound) -> Situation_Error ---

    // Gracefully stop a tone by triggering its release envelope. Invalid handles are ignored.
    SituationStopTone :: proc(handle: Situation_Tone_Handle) ---

    // Submits a job with priority flags and optional data payload.
    SituationSubmitJobEx :: proc(pool: ^Situation_Thread_Pool, data: rawptr, data_size: uint, flags: Situation_Job_Flags) -> Situation_Job_Id ---

    // Submit a render list for async recording on a worker thread.
    SituationSubmitRenderList :: proc(pool: ^Situation_Thread_Pool, list: Situation_Render_List, user_data: rawptr) -> Situation_Job_Id ---

    // Take a screenshot. fileName is the base name (no extension) or NULL for auto-name. Extension added from format setting.
    SituationTakeScreenshot :: proc() -> Situation_Error ---

    // Close and destroy the virtual loopback devices.
    SituationTeardownVirtualMidiLoopback :: proc() ---

    // Get the period of an oscillator in seconds.
    SituationTimerGetOscillatorPeriod :: proc(oscillator_id: c.int) -> f64 ---

    // Get the current binary state (0 or 1) of an oscillator.
    SituationTimerGetOscillatorState :: proc(oscillator_id: c.int) -> b8 ---

    // Get the total number of times an oscillator has triggered.
    SituationTimerGetOscillatorTriggerCount :: proc(oscillator_id: c.int) -> u64 ---

    // Get progress [0.0 to 1.0+] of the interval since the last successful ping.
    SituationTimerGetPingProgress :: proc(oscillator_id: c.int) -> f64 ---

    // Get the previous frame's state of an oscillator.
    SituationTimerGetPreviousOscillatorState :: proc(oscillator_id: c.int) -> b8 ---

    // Get the total time elapsed since initialization.
    SituationTimerGetTime :: proc() -> f64 ---

    // Check if an oscillator's state has changed this frame.
    SituationTimerHasOscillatorUpdated :: proc(oscillator_id: c.int) -> b8 ---

    // Check if an oscillator's period has elapsed since the last ping.
    SituationTimerPingOscillator :: proc(oscillator_id: c.int) -> b8 ---

    // Toggle window between borderless and decorated mode.
    SituationToggleBorderlessWindowed :: proc() ---

    // Toggle window between fullscreen and windowed mode.
    SituationToggleFullscreen :: proc() ---

    // Toggle flags in the current profile and apply the result.
    SituationToggleWindowStateFlags :: proc(flags_to_toggle: Situation_Window_State_Flags) -> Situation_Error ---

    // Re-sort the graph processing order after topology changes. Call from the main thread after CreateNode/DestroyNode/CreatePatch/RemovePatch.
    SituationTopologicalSort :: proc(graph: ^Situation_Audio_Graph) -> Situation_Error ---

    // Unload audio by handle and free resources.
    SituationUnloadAudio :: proc(handle: Situation_Sound_Handle) ---

    // Unload the file path list returned by SituationLoadDroppedFiles.
    SituationUnloadDroppedFiles :: proc(paths: [^]cstring, count: c.int) ---

    // Frees CPU font data, glyph metrics, and owned GPU atlas (not the built-in default).
    SituationUnloadFont :: proc(font: Situation_Font) ---

    // Unload an image's pixel data from memory.
    SituationUnloadImage :: proc(image: Situation_Image) ---

    // Frees all GPU and CPU resources associated with a loaded model.
    SituationUnloadModel :: proc(model: ^Situation_Model) ---

    // Unload a graphics shader pipeline and free its GPU resources.
    SituationUnloadShader :: proc(shader: ^Situation_Shader) ---

    // Unload a sound and free its resources.
    SituationUnloadSound :: proc(sound: ^Situation_Sound) ---

    SituationUpdate :: proc() ---
    // Update data in a GPU buffer.
    SituationUpdateBuffer :: proc(buffer: Situation_Buffer, offset: uint, size: uint, data: rawptr) -> Situation_Error ---

    // [Main thread] Update all internal timers (frame timer, temporal system). Call after polling events.
    SituationUpdateTimers :: proc() ---

    // Returns first missing/wrong-type uniform, or SUCCESS if all resolved.
    SituationValidateShaderUniforms :: proc(shader: Situation_Shader, table: ^Situation_Uniform_Expectation, table_count: c.int, error_buf: cstring, error_buf_size: uint) -> Situation_Error ---

    // CC (e.g. mod wheel, expression).
    SituationVirtualMidiControlChange :: proc(channel: u8, controller: u8, value: u8) -> Situation_Error ---

    // Inject note-off on channel 0 (legacy wrapper).
    SituationVirtualMidiNoteOff :: proc(note: u8) -> Situation_Error ---

    // Channel-aware note-off (0-15).
    SituationVirtualMidiNoteOffEx :: proc(channel: u8, note: u8) -> Situation_Error ---

    // Inject note-on on channel 0 (legacy wrapper).
    SituationVirtualMidiNoteOn :: proc(note: u8, velocity: u8) -> Situation_Error ---

    // Channel-aware note-on (0-15).
    SituationVirtualMidiNoteOnEx :: proc(channel: u8, note: u8, velocity: u8) -> Situation_Error ---

    // Pitch bend 0..16383 (center 8192).
    SituationVirtualMidiPitchBend :: proc(channel: u8, bend: i16) -> Situation_Error ---

    // Program change on channel 0-15.
    SituationVirtualMidiProgramChange :: proc(channel: u8, program: u8) -> Situation_Error ---

    // Blocks until all queued jobs are finished.
    SituationWaitForAllJobs :: proc(pool: ^Situation_Thread_Pool) ---

    // Waits for a specific job to complete (O(1) check).
    SituationWaitForJob :: proc(pool: ^Situation_Thread_Pool, job_id: Situation_Job_Id) -> Situation_Error ---

    // Check if the application should close (e.g., user clicked X).
    SituationWindowShouldClose :: proc() -> b8 ---

    // Scale Q (chroma amplitude); preserve luma and phase.
    SituationYpqAdjustChroma :: proc(color: Color_YPQA, chroma_factor: f32) -> Color_YPQA ---

    // Scale Y (luma); preserve phase and chroma.
    SituationYpqAdjustLuma :: proc(color: Color_YPQA, luma_factor: f32) -> Color_YPQA ---

    // Rotate hue; P shifts by byte steps mod 256.
    SituationYpqAdjustPhase :: proc(color: Color_YPQA, phase_shift: c.int) -> Color_YPQA ---

    SituationYpqAnalyzeRgbMapping :: proc(out: ^Situation_Ypq_Rgb_Mapping_Stats) -> Situation_Error ---
    // Reduce chroma if linear RGB would clip.
    SituationYpqClampInGamut :: proc(ypq: Color_YP_Qf) -> Color_YP_Qf ---

    // Weighted distance in YPQ space.
    SituationYpqDistance :: proc(a: Color_YPQA, b: Color_YPQA) -> f32 ---

    // Per-channel tolerance compare.
    SituationYpqEquals :: proc(a: Color_YPQA, b: Color_YPQA, tolerance: u8) -> b8 ---

    // Normalized chroma amplitude [0, 1].
    SituationYpqGetChroma :: proc(color: Color_YPQA) -> f32 ---

    // Hue in degrees [0, 360).
    SituationYpqGetHueDegrees :: proc(color: Color_YPQA) -> f32 ---

    // Normalized luma [0, 1].
    SituationYpqGetLuma :: proc(color: Color_YPQA) -> f32 ---

    // Interpolate YPQ; phase uses shortest arc on the hue wheel.
    SituationYpqLerp :: proc(a: Color_YPQA, b: Color_YPQA, t: f32) -> Color_YPQA ---

    // Float YPQ → 8-bit ColorYPQA.
    SituationYpqQuantize :: proc(ypq: Color_YP_Qf) -> Color_YPQA ---

    SituationYpqSliceDuplicateCount :: proc(axis: c.char, value: c.int, out_dup: ^c.int) -> Situation_Error ---
    // Float YPQ → A2R10G10B10 packed pixel (10-bit SDR).
    SituationYpqToRgb10Packed :: proc(ypq: Color_YP_Qf) -> u32 ---

    // Float YPQ → PQ-encoded A2R10G10B10 (HDR10 swapchain).
    SituationYpqToRgb10PackedHdr :: proc(ypq: Color_YP_Qf) -> u32 ---

    // Float YPQ → 10-bit RGBA (linear YIQ, clamped).
    SituationYpqToRgba10 :: proc(ypq: Color_YP_Qf) -> Color_RGBA10 ---

}
