// Auto-generated by tools/generate_odin_bindings.py — Situation 2.4.214 (DLL-Linked Examples + Async Shader UAF Fix)
// Do not edit by hand.
package situation

import "core:c"

// Helpers replacing C preprocessor macros from situation_api.h

situation_begin_frame :: proc() {
    SituationPollInputEvents()
    SituationUpdateTimers()
}

situation_success :: proc(err: Situation_Error) -> bool {
    return err == .SITUATION_SUCCESS
}
