// Auto-generated by tools/generate_odin_bindings.py — Situation 2.4.214 (DLL-Linked Examples + Async Shader UAF Fix)
// Do not edit by hand.
package situation

import "core:c"

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.

Situation_File_Drop_Callback :: proc "c" (count: c.int, paths: [^]cstring, user_data: rawptr)
// Files/folders dragged from OS onto the window

Situation_File_Load_Callback :: proc "c" (data: rawptr, size: uint, user_data: rawptr)
// Callback for asynchronous file loading

Situation_File_Save_Callback :: proc "c" (success: b8, user_data: rawptr)
// Callback for asynchronous file saving

Situation_File_Text_Load_Callback :: proc "c" (text: cstring, user_data: rawptr)
// Callback for asynchronous text file loading

Situation_Focus_Callback :: proc "c" (gained_focus: b8, user_data: rawptr)
// Window focus change (alt-tab, click, etc.)

Situation_Maximize_Callback :: proc "c" (maximized: b8, user_data: rawptr)
// Title-bar maximize / restore (requires SITUATION_FLAG_WINDOW_RESIZABLE at init)

Situation_Window_Close_Callback :: proc "c" (user_data: rawptr)
// User clicked the OS close button. Rarely used — most code just polls SituationWindowShouldClose()

Situation_Key_Callback :: proc "c" (key: c.int, scancode: c.int, action: c.int, mods: c.int, user_data: rawptr)
// Exact GLFW key callback signature

Situation_Char_Callback :: proc "c" (codepoint: c.uint, user_data: rawptr)
// Text input (separate from key events — handles IME, dead keys, etc.)

Situation_Mouse_Button_Callback :: proc "c" (button: c.int, action: c.int, mods: c.int, user_data: rawptr)
// Mouse button events

Situation_Cursor_Pos_Callback :: proc "c" (position: Vector2, user_data: rawptr)
// Called every time the mouse moves (can be very frequent)

Situation_Scroll_Callback :: proc "c" (offset: Vector2, user_data: rawptr)
// Mouse wheel / trackpad scroll

Situation_Joystick_Callback :: proc "c" (jid: c.int, event: c.int, user_data: rawptr)
// Gamepad/controller hotplug events

Situation_Stream_Read_Callback :: proc "c" (pUserData: rawptr, pBufferOut: rawptr, bytesToRead: u64) -> u64
// Return number of bytes actually written

Situation_Stream_Seek_Callback :: proc "c" (pUserData: rawptr, byteOffset: ma_int64, origin: ma_seek_origin) -> c.int
// Return MA_SUCCESS on success

Situation_Audio_Capture_Callback :: proc "c" (input_buffer: ^f32, frame_count: u32, user_data: rawptr)
// Called from audio thread unless SITUATION_INIT_AUDIO_CAPTURE_MAIN_THREAD is set

Situation_Audio_Processor_Callback :: proc "c" (buffer: ^f32, frames: u32, channels: u32, sampleRate: u32, user_data: rawptr)
// Applied after built-in effects (filter → echo → reverb) but before final volume/pan

GLF_Werrorfun :: proc "c" (error_code: c.int, description: cstring)
