// Auto-generated by tools/generate_odin_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.)
// Do not edit by hand.
package situation

import "core:c"

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.
