// Auto-generated by tools/generate_odin_bindings.py — Situation 2.4.265 (YPQ Phase 3: public mapping diagnostics API, test_misc cleanup)
// Do not edit by hand.
package situation

import "core:c"

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.
