// Auto-generated by tools/generate_rust_bindings.py — Situation 2.4.265 (YPQ Phase 3: public mapping diagnostics API, test_misc cleanup)
// Do not edit by hand.

use std::os::raw::{c_char, c_int, c_uint, c_void, c_long};

use crate::situation_types::*;
use crate::situation_callbacks::*;

extern "C" {
    /// Prepare the backend for a new frame of rendering commands.
    pub fn SituationAcquireFrameCommandBuffer() -> SituationError;

    /// Adds multiple dependencies for a single dependent job.
    pub fn SituationAddJobDependencies(pool: *mut SituationThreadPool, prerequisites: *mut SituationJobId, count: c_int, dependent_job: SituationJobId) -> SituationError;

    /// Adds a dependency between two jobs (prereq -> dependent).
    pub fn SituationAddJobDependency(pool: *mut SituationThreadPool, prerequisite_job: SituationJobId, dependent_job: SituationJobId) -> SituationError;

    /// Manually apply the appropriate window state profile based on current focus.
    pub fn SituationApplyCurrentProfileWindowState() -> SituationError;

    /// Attach a custom DSP processor to a sound's effect chain.
    pub fn SituationAttachAudioProcessor(sound: *mut SituationSound, processor: SituationAudioProcessorCallback, user_data: *mut c_void) -> SituationError;

    /// Convenience: auto-select first available MIDI input. Equivalent to EnableMidiControl(..., -1).
    pub fn SituationAutoConnectMidi(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Rasterize a font into a GPU-ready atlas at the given size.
    pub fn SituationBakeFontAtlas(font: *mut SituationFont, fontSizePixels: f32) -> SituationError;

    /// Start non-blocking GLSL load: [OpenGL] async compile/link; [Vulkan] shaderc on worker thread, pipelines on next frames. Poll with SituationPollShaderLoad.
    pub fn SituationBeginLoadShaderFromMemory(vs_code: *const c_char, fs_code: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// [Vulkan] Non-blocking pipeline build from in-memory SPIR-V (bytecode copied). [OpenGL] blocking SPIR-V load (unchanged).
    pub fn SituationBeginLoadShaderFromSpirvMemory(vs_spirv: *mut c_void, vs_len: usize, fs_spirv: *mut c_void, fs_len: usize, out_shader: *mut SituationShader) -> SituationError;

    /// [Vulkan] Async SPIR-V with layout profile (e.g. UBO_SSBO for Demon Hunt). [OpenGL] profile ignored; same as SituationBeginLoadShaderFromSpirvMemory.
    pub fn SituationBeginLoadShaderFromSpirvMemoryEx(vs_spirv: *mut c_void, vs_len: usize, fs_spirv: *mut c_void, fs_len: usize, layout_profile: SituationSpirvLayoutProfile, out_shader: *mut SituationShader) -> SituationError;

    /// [OpenGL] glShaderStorageBlockBinding for SPIR-V when reflection reports binding 0 for layout(binding=N).
    pub fn SituationBindShaderStorageBlock(shader: SituationShader, block_name: *const c_char, binding_point: u32) -> SituationError;

    /// [OpenGL] glUniformBlockBinding for std140 UBO blocks (layout(binding=N)).
    pub fn SituationBindUniformBlock(shader: SituationShader, block_name: *const c_char, binding_point: u32) -> SituationError;

    /// Copies raw byte data into a specific region of an image.
    pub fn SituationBlitRawDataToImage(data: *mut c_void, x: c_int, y: c_int, width: c_int, height: c_int, src_channels: c_int) -> ();

    /// All logical CPUs on a NUMA node
    pub fn SituationBuildNumaNodeMask(numa_node_index: c_int) -> u64;

    /// All logical CPUs on one physical core
    pub fn SituationBuildPhysicalCoreMask(physical_core_index: c_int) -> u64;

    /// One LP per core
    pub fn SituationBuildUniqueCoreMask(start_physical_core: c_int, count: c_int, avoid_siblings: bool) -> u64;

    pub fn SituationCameraBuildInvViewProj(desc: *mut SituationCameraDesc, out_inv_vp: Mat4) -> ();
    pub fn SituationCameraBuildProj(desc: *mut SituationCameraDesc, out_proj: Mat4) -> ();
    pub fn SituationCameraBuildView(desc: *mut SituationCameraDesc, out_view: Mat4) -> ();
    pub fn SituationCameraBuildViewProj(desc: *mut SituationCameraDesc, out_vp: Mat4) -> ();
    pub fn SituationCameraUnprojectPixel(desc: *mut SituationCameraDesc, inv_vp: Mat4, pixel: Vector2, framebuffer_px: Vector2, out_ray_origin: *mut Vector3, out_ray_dir: *mut Vector3) -> ();
    /// Cancel an active learn operation.
    pub fn SituationCancelMidiLearn(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Checks all tracked resources for file changes and reloads them if necessary.
    pub fn SituationCheckHotReloads() -> SituationError;

    /// Clear all learned mappings for a node.
    pub fn SituationClearAllMidiMappings(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Clear a specific learned CC mapping.
    pub fn SituationClearMidiMapping(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, control_index: c_int) -> SituationError;

    /// Clear window configuration state flags.
    pub fn SituationClearWindowState(flags: u32) -> ();

    pub fn SituationCmdBeginDebugGroup(cmd: SituationCommandBuffer, name: *const c_char, color: ColorRGBA) -> SituationError;
    /// Begins a render pass with detailed configuration.
    pub fn SituationCmdBeginRenderPass(cmd: SituationCommandBuffer, info: *mut SituationRenderPassInfo) -> SituationError;

    /// [DEPRECATED] Begins a render pass on a target (-1 for main window), clearing it.
    pub fn SituationCmdBeginRenderToDisplay(cmd: SituationCommandBuffer, display_id: c_int, clear_color: ColorRGBA) -> SituationError;

    /// [DEPRECATED] Bind a buffer to a compute shader binding point.
    pub fn SituationCmdBindComputeBuffer(cmd: SituationCommandBuffer, binding: u32, buffer: SituationBuffer) -> SituationError;

    /// Bind a compute pipeline for a subsequent dispatch.
    pub fn SituationCmdBindComputePipeline(cmd: SituationCommandBuffer, pipeline: SituationComputePipeline) -> SituationError;

    /// [Core] Binds a texture as a storage image for compute shaders.
    pub fn SituationCmdBindComputeTexture(cmd: SituationCommandBuffer, binding: u32, texture: SituationTexture) -> SituationError;

    /// [Core] Binds a buffer's descriptor set (UBO/SSBO) to a set index.
    pub fn SituationCmdBindDescriptorSet(cmd: SituationCommandBuffer, set_index: u32, buffer: SituationBuffer) -> SituationError;

    /// [Core] Binds a dynamic buffer descriptor set with an offset.
    pub fn SituationCmdBindDescriptorSetDynamic(cmd: SituationCommandBuffer, set_index: u32, buffer: SituationBuffer, dynamic_offset: u32) -> SituationError;

    /// [Core] Bind a 32-bit index buffer (SIT_INDEX_UINT32). Pass offset 0 when indices start at the beginning of the buffer.
    pub fn SituationCmdBindIndexBuffer(cmd: SituationCommandBuffer, buffer: SituationBuffer, offset: usize) -> SituationError;

    /// [Core] Bind index buffer with 16- or 32-bit element type for subsequent SituationCmdDrawIndexed.
    pub fn SituationCmdBindIndexBufferEx(cmd: SituationCommandBuffer, buffer: SituationBuffer, offset: usize, index_type: SituationIndexType) -> SituationError;

    /// Binds a graphics pipeline (shader program) for subsequent draws.
    pub fn SituationCmdBindPipeline(cmd: SituationCommandBuffer, shader: SituationShader) -> SituationError;

    /// Binds a texture as a sampled image (sampler2D) to a binding point.
    pub fn SituationCmdBindSampledTexture(cmd: SituationCommandBuffer, binding: c_int, texture: SituationTexture) -> SituationError;

    /// [DEPRECATED] [Core] Bind a texture and sampler to a shader binding point.
    pub fn SituationCmdBindTexture(cmd: SituationCommandBuffer, set_index: u32, texture: SituationTexture) -> SituationError;

    /// [Core] Binds a texture's descriptor set (sampler/storage) to a set index.
    pub fn SituationCmdBindTextureSet(cmd: SituationCommandBuffer, set_index: u32, texture: SituationTexture) -> SituationError;

    /// [DEPRECATED] [Core] Bind a Uniform Buffer Object (UBO) to a shader binding point.
    pub fn SituationCmdBindUniformBuffer(cmd: SituationCommandBuffer, contract_id: u32, buffer: SituationBuffer) -> SituationError;

    /// [Core] Bind a vertex buffer for subsequent SituationCmdDraw / SituationCmdDrawIndexed.
    pub fn SituationCmdBindVertexBuffer(cmd: SituationCommandBuffer, binding: u32, buffer: SituationBuffer, offset: usize, stride: usize) -> SituationError;

    /// Blit between color 2D textures; caller owns explicit texture barriers.
    pub fn SituationCmdBlitTexture(cmd: SituationCommandBuffer, src: SituationTexture, dst: SituationTexture, region: *mut SituationTextureBlitRegion) -> SituationError;

    /// Record an explicit buffer-range memory barrier.
    pub fn SituationCmdBufferBarrier(cmd: SituationCommandBuffer, desc: *mut SituationBufferBarrierDesc) -> SituationError;

    /// Mid-pass clear of active render-pass attachments; begin-pass clears use SituationRenderPassInfo loadOp.
    pub fn SituationCmdClear(cmd: SituationCommandBuffer, clear_flags: u32, clear_value: *mut SituationClearValue) -> SituationError;

    /// Mid-pass clear of the active color attachment.
    pub fn SituationCmdClearColor(cmd: SituationCommandBuffer, color: ColorRGBA) -> SituationError;

    /// Mid-pass clear of the active depth attachment.
    pub fn SituationCmdClearDepth(cmd: SituationCommandBuffer, depth: f32) -> SituationError;

    /// Mid-pass clear of active depth and stencil attachments.
    pub fn SituationCmdClearDepthStencil(cmd: SituationCommandBuffer, depth: f32, stencil: u32) -> SituationError;

    /// Mid-pass clear of the active stencil attachment when supported by backend/attachment state.
    pub fn SituationCmdClearStencil(cmd: SituationCommandBuffer, stencil: u32) -> SituationError;

    /// Legacy buffer-copy command (now returns error).
    pub fn SituationCmdCopyBuffer(cmd: SituationCommandBuffer, src: SituationBuffer, dst: SituationBuffer, offset: usize, size: usize) -> SituationError;

    /// Error-returning buffer-copy command with independent source/destination offsets.
    pub fn SituationCmdCopyBufferEx(cmd: SituationCommandBuffer, src: SituationBuffer, dst: SituationBuffer, src_offset: usize, dst_offset: usize, size: usize) -> SituationError;

    /// Upload tightly packed RGBA8 rows from a buffer into a texture subregion; caller owns texture barriers.
    pub fn SituationCmdCopyBufferToTexture(cmd: SituationCommandBuffer, src: SituationBuffer, src_offset: usize, dst: SituationTexture, dst_region: *mut SituationTextureCopyRegion) -> SituationError;

    /// Exact-size copy between color 2D textures; caller owns explicit texture barriers.
    pub fn SituationCmdCopyTexture(cmd: SituationCommandBuffer, src: SituationTexture, dst: SituationTexture, region: *mut SituationTextureCopyRegion) -> SituationError;

    /// Copy a texture subregion into a buffer (`dst_row_pitch` 0 = width * 4); caller owns texture barriers.
    pub fn SituationCmdCopyTextureToBuffer(cmd: SituationCommandBuffer, src: SituationTexture, src_region: *mut SituationTextureCopyRegion, dst: SituationBuffer, dst_offset: usize, dst_row_pitch: usize) -> SituationError;

    /// Record a command to dispatch compute shader work groups.
    pub fn SituationCmdDispatch(cmd: SituationCommandBuffer, group_count_x: u32, group_count_y: u32, group_count_z: u32) -> SituationError;

    /// Record a compute dispatch with validation and error reporting.
    pub fn SituationCmdDispatchEx(cmd: SituationCommandBuffer, group_count_x: u32, group_count_y: u32, group_count_z: u32) -> SituationError;

    /// Record an indirect compute dispatch.
    pub fn SituationCmdDispatchIndirect(cmd: SituationCommandBuffer, indirect_buffer: SituationBuffer, offset: usize) -> SituationError;

    /// [Core] Record a non-indexed draw call.
    pub fn SituationCmdDraw(cmd: SituationCommandBuffer, vertex_count: u32, instance_count: u32, first_vertex: u32, first_instance: u32) -> SituationError;

    /// [Core] Record an indexed draw call.
    pub fn SituationCmdDrawIndexed(cmd: SituationCommandBuffer, index_count: u32, instance_count: u32, first_index: u32, vertex_offset: c_int, first_instance: u32) -> SituationError;

    /// [Core] Indexed indirect draw (32-bit indices; requires bound index buffer). firstIndex is relative to SituationCmdBindIndexBuffer offset.
    pub fn SituationCmdDrawIndexedIndirect(cmd: SituationCommandBuffer, indirect_buffer: SituationBuffer, offset: usize) -> SituationError;

    /// [Core] Draw from a CPU/GPU-filled SituationDrawIndirectCommand in an indirect buffer (requires active render pass, bound pipeline, and vertex buffers).
    pub fn SituationCmdDrawIndirect(cmd: SituationCommandBuffer, indirect_buffer: SituationBuffer, offset: usize) -> SituationError;

    /// [High-Level] Records a command to draw a complete, pre-configured mesh.
    pub fn SituationCmdDrawMesh(cmd: SituationCommandBuffer, mesh: SituationMesh) -> SituationError;

    /// [High-Level] Record a command to draw a simple, colored 2D quad.
    pub fn SituationCmdDrawQuad(cmd: SituationCommandBuffer, model: Mat4, color: Vector4) -> SituationError;

    /// Draws a text string using GPU-accelerated textured quads.
    pub fn SituationCmdDrawText(cmd: SituationCommandBuffer, font: SituationFont, text: *const c_char, pos: Vector2, color: ColorRGBA) -> SituationError;

    /// Advanced text drawing (scaling/spacing).
    pub fn SituationCmdDrawTextEx(cmd: SituationCommandBuffer, font: SituationFont, text: *const c_char, pos: Vector2, fontSize: f32, spacing: f32, color: ColorRGBA) -> SituationError;

    /// [High-Level] Draw a part of a texture defined by a rectangle.
    pub fn SituationCmdDrawTexture(cmd: SituationCommandBuffer, texture: SituationTexture, source: SitRectangle, dest: SitRectangle, origin: Vector2, rotation: f32, tint: ColorRGBA) -> SituationError;

    /// [High-Level] Draw texture with YPQ grade (matches SituationImageAdjustYPQ).
    pub fn SituationCmdDrawTextureYpqGrade(cmd: SituationCommandBuffer, texture: SituationTexture, source: SitRectangle, dest: SitRectangle, origin: Vector2, rotation: f32, phase_shift_deg: f32, chroma_factor: f32, luma_factor: f32, mix: f32) -> SituationError;

    pub fn SituationCmdEndDebugGroup(cmd: SituationCommandBuffer) -> SituationError;
    /// [DEPRECATED] End the current render pass.
    pub fn SituationCmdEndRender(cmd: SituationCommandBuffer) -> SituationError;

    /// Ends the current render pass.
    pub fn SituationCmdEndRenderPass(cmd: SituationCommandBuffer) -> SituationError;

    /// Legacy convenience barrier; prefer SituationCmdPipelineBarrierEx, SituationCmdBufferBarrier, or SituationCmdTextureBarrier for new synchronization code.
    pub fn SituationCmdPipelineBarrier(cmd: SituationCommandBuffer, src_flags: u32, dst_flags: u32) -> ();

    /// Record an explicit global memory barrier.
    pub fn SituationCmdPipelineBarrierEx(cmd: SituationCommandBuffer, desc: *mut SituationPipelineBarrierDesc) -> SituationError;

    pub fn SituationCmdPopRasterState(cmd: SituationCommandBuffer, scope_id: u32) -> SituationError;
    /// Submits a command to copy a texture to the main window's swapchain (Compute-Only).
    pub fn SituationCmdPresent(cmd: SituationCommandBuffer, texture: SituationTexture) -> SituationError;

    pub fn SituationCmdPushRasterState(cmd: SituationCommandBuffer, scope_id: u32) -> SituationError;
    pub fn SituationCmdSetBlendEnable(cmd: SituationCommandBuffer, enable: bool) -> SituationError;
    pub fn SituationCmdSetBlendFuncSeparate(cmd: SituationCommandBuffer, src_rgb: SituationBlendFactor, dst_rgb: SituationBlendFactor, src_a: SituationBlendFactor, dst_a: SituationBlendFactor) -> SituationError;
    pub fn SituationCmdSetColorWriteMask(cmd: SituationCommandBuffer, r: bool, g: bool, b: bool, a: bool) -> SituationError;
    pub fn SituationCmdSetCullMode(cmd: SituationCommandBuffer, mode: SituationCullMode) -> SituationError;
    pub fn SituationCmdSetDepthBias(cmd: SituationCommandBuffer, enable: bool, constant_factor: f32, clamp: f32, slope_factor: f32) -> SituationError;
    pub fn SituationCmdSetDepthTest(cmd: SituationCommandBuffer, enable: bool, depth_op: SituationDepthCompareOp) -> SituationError;
    pub fn SituationCmdSetDepthWrite(cmd: SituationCommandBuffer, enable: bool) -> SituationError;
    pub fn SituationCmdSetFrontFace(cmd: SituationCommandBuffer, front_face: SituationFrontFace) -> SituationError;
    pub fn SituationCmdSetLineWidth(cmd: SituationCommandBuffer, width: f32) -> SituationError;
    pub fn SituationCmdSetMultisampleState(cmd: SituationCommandBuffer, state: *mut SituationMultisampleState) -> SituationError;
    pub fn SituationCmdSetPolygonMode(cmd: SituationCommandBuffer, mode: SituationPolygonMode) -> SituationError;
    pub fn SituationCmdSetPrimitiveTopology(cmd: SituationCommandBuffer, topology: SituationPrimitiveTopology) -> SituationError;
    /// [Core] Set a small block of per-draw uniform data (push constant).
    pub fn SituationCmdSetPushConstant(cmd: SituationCommandBuffer, contract_id: u32, data: *mut c_void, size: usize) -> SituationError;

    pub fn SituationCmdSetPushConstantData(cmd: SituationCommandBuffer, shader: SituationShader, offset: u32, data: *mut c_void, size: usize) -> SituationError;
    /// Sets the dynamic scissor rectangle to clip rendering.
    pub fn SituationCmdSetScissor(cmd: SituationCommandBuffer, x: c_int, y: c_int, width: c_int, height: c_int) -> SituationError;

    /// Sets scissor at index (0 = default scissor).
    pub fn SituationCmdSetScissorIndexed(cmd: SituationCommandBuffer, index: u32, x: c_int, y: c_int, width: c_int, height: c_int) -> SituationError;

    pub fn SituationCmdSetStencilTest(cmd: SituationCommandBuffer, enable: bool, front: *mut SituationStencilState, back: *mut SituationStencilState) -> SituationError;
    /// [OpenGL Only, Deprecated v2.4] Attribute format + vertex buffer binding index. Prefer vertex pulling via SituationGetMeshVertexBufferAddress + sit/gpu/vertex_pull.glslh on Vulkan.
    pub fn SituationCmdSetVertexAttribute(cmd: SituationCommandBuffer, location: u32, binding: u32, size: c_int, r#type: SituationDataType, normalized: bool, offset: usize) -> SituationError;

    /// Sets the dynamic viewport and scissor for the current render pass.
    pub fn SituationCmdSetViewport(cmd: SituationCommandBuffer, x: f32, y: f32, width: f32, height: f32) -> SituationError;

    /// Sets viewport at index (0 = default viewport).
    pub fn SituationCmdSetViewportIndexed(cmd: SituationCommandBuffer, index: u32, x: f32, y: f32, width: f32, height: f32) -> SituationError;

    /// Record an explicit texture layout/memory barrier.
    pub fn SituationCmdTextureBarrier(cmd: SituationCommandBuffer, texture: SituationTexture, desc: *mut SituationTextureBarrierDesc) -> SituationError;

    /// Converts a YPQA color back to the standard RGBA color space.
    pub fn SituationColorFromYPQ(ypq_color: ColorYPQA) -> ColorRGBA;

    /// Float YPQ → RGBA (linear YIQ, clamped RGB).
    pub fn SituationColorFromYPQf(ypq: ColorYPQf) -> ColorRGBA;

    /// Converts a standard RGBA color to the YPQA (Luma, Phase, Quadrature) color space.
    pub fn SituationColorToYPQ(color: ColorRGBA) -> ColorYPQA;

    /// RGBA → normalized float YPQ (no 8-bit quantize).
    pub fn SituationColorToYPQf(color: ColorRGBA) -> ColorYPQf;

    /// Configure a virtual display's properties.
    pub fn SituationConfigureVirtualDisplay(display_id: c_int, offset: Vector2, opacity: f32, z_order: c_int, visible: bool, frame_time_mult: f64, blend_mode: SituationBlendMode) -> SituationError;

    /// Convert an 8-bit ColorRGBA struct to a normalized Vector4.
    pub fn SituationConvertColorToVector4(c: ColorRGBA, out_normalized_color: *mut Vector4) -> ();

    /// Copy a file.
    pub fn SituationCopyFile(source_path: *const c_char, dest_path: *const c_char) -> SituationError;

    /// Create a generic GPU data buffer (e.g., SSBO).
    pub fn SituationCreateBuffer(size: usize, initial_data: *mut c_void, usage_flags: SituationBufferUsageFlags, out_buffer: *mut SituationBuffer) -> SituationError;

    /// Create a compute pipeline from a shader file.
    pub fn SituationCreateComputePipeline(compute_shader_path: *const c_char, layout_type: SituationComputeLayoutType, out_pipeline: *mut SituationComputePipeline) -> SituationError;

    /// Create a compute pipeline from in-memory GLSL source.
    pub fn SituationCreateComputePipelineFromMemory(compute_shader_source: *const c_char, layout_type: SituationComputeLayoutType, out_pipeline: *mut SituationComputePipeline) -> SituationError;

    /// Create a directory, optionally creating parent directories.
    pub fn SituationCreateDirectory(dir_path: *const c_char, create_parents: bool) -> SituationError;

    /// Create a new audio processing graph.
    pub fn SituationCreateGraph() -> *mut SituationAudioGraph;

    /// Allocates a new SituationImage container with UNINITIALIZED data.
    pub fn SituationCreateImage(width: c_int, height: c_int, channels: c_int, out_image: *mut SituationImage) -> SituationError;

    /// Create a mesh from vertex and index data.
    pub fn SituationCreateMesh(vertex_data: *mut c_void, vertex_count: c_int, vertex_stride: usize, index_data: *mut u32, index_count: c_int, out_mesh: *mut SituationMesh) -> SituationError;

    /// Create a node of the given type in the graph.
    pub fn SituationCreateNode(graph: *mut SituationAudioGraph, r#type: SituationNodeType, handle: *mut SituationNodeHandle) -> SituationError;

    /// Connect an output port to an input port.
    pub fn SituationCreatePatch(graph: *mut SituationAudioGraph, src: SituationNodeHandle, src_port: c_int, dst: SituationNodeHandle, dst_port: c_int, is_control: bool) -> SituationError;

    /// [Phase 1] Create an async GPU->CPU staging buffer.
    pub fn SituationCreateReadbackBuffer(size: usize, out_buffer: *mut SituationBuffer) -> SituationError;

    /// Create a texture from a CPU-side image.
    pub fn SituationCreateTexture(image: SituationImage, generate_mipmaps: bool, out_texture: *mut SituationTexture) -> SituationError;

    /// Create a texture with specific usage flags.
    pub fn SituationCreateTextureEx(image: SituationImage, generate_mipmaps: bool, flags: SituationTextureUsageFlags, out_texture: *mut SituationTexture) -> SituationError;

    /// Initializes the thread pool with dual-priority queues and worker threads.
    pub fn SituationCreateThreadPool(pool: *mut SituationThreadPool, num_threads: usize, queue_size: usize, hot_reload_rate: f64, disable_io: bool) -> SituationError;

    /// Create an off-screen render target.
    pub fn SituationCreateVirtualDisplay(resolution: Vector2, frame_time_mult: f64, z_order: c_int, scaling_mode: SituationScalingMode, blend_mode: SituationBlendMode, out_id: *mut c_int) -> SituationError;

    /// Create a virtual display with extended flags (e.g. COMPUTE_TARGET for compute shader writes).
    pub fn SituationCreateVirtualDisplayEx(resolution: Vector2, frame_time_mult: f64, z_order: c_int, scaling_mode: SituationScalingMode, blend_mode: SituationBlendMode, flags: SituationVDFlags, out_id: *mut c_int) -> SituationError;

    /// Delete a directory, optionally deleting all its contents.
    pub fn SituationDeleteDirectory(dir_path: *const c_char, recursive: bool) -> SituationError;

    /// Delete a file.
    pub fn SituationDeleteFile(file_path: *const c_char) -> SituationError;

    /// Deserialize a graph from a JSON string.
    pub fn SituationDeserializeGraphFromJSON(graph: *mut SituationAudioGraph, json_string: *const c_char, device_funcs: *mut SituationDeviceFunctions, num_device_funcs: c_int) -> SituationError;

    /// Destroy a GPU buffer.
    pub fn SituationDestroyBuffer(buffer: *mut SituationBuffer) -> ();

    /// Destroy a compute pipeline and free its GPU resources.
    pub fn SituationDestroyComputePipeline(pipeline: *mut SituationComputePipeline) -> ();

    /// Destroy a graph and all its nodes/patches.
    pub fn SituationDestroyGraph(graph: *mut SituationAudioGraph) -> ();

    /// Unload a mesh from GPU memory.
    pub fn SituationDestroyMesh(mesh: *mut SituationMesh) -> ();

    /// Remove and destroy a node from the graph.
    pub fn SituationDestroyNode(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Disconnect a patch between two ports (legacy, no is_control param).
    pub fn SituationDestroyPatch(graph: *mut SituationAudioGraph, src: SituationNodeHandle, src_port: c_int, dst: SituationNodeHandle, dst_port: c_int) -> SituationError;

    /// Unload a texture from GPU memory.
    pub fn SituationDestroyTexture(texture: *mut SituationTexture) -> ();

    /// Shuts down the thread pool and releases resources.
    pub fn SituationDestroyThreadPool(pool: *mut SituationThreadPool) -> ();

    /// Destroy a virtual display.
    pub fn SituationDestroyVirtualDisplay(display_id: c_int) -> SituationError;

    /// Detach a custom DSP processor from a sound.
    pub fn SituationDetachAudioProcessor(sound: *mut SituationSound, processor: SituationAudioProcessorCallback, user_data: *mut c_void) -> SituationError;

    /// Check if a directory exists at the given path.
    pub fn SituationDirectoryExists(dir_path: *const c_char) -> bool;

    /// Hide and lock the cursor, providing raw mouse motion.
    pub fn SituationDisableCursor() -> ();

    /// Disable MIDI control for a node.
    pub fn SituationDisableMidiControl(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Disable MIDI Learn for a node.
    pub fn SituationDisableMidiLearn(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Executes a loop in parallel across worker threads (Fork-Join).
    pub fn SituationDispatchParallel(pool: *mut SituationThreadPool, count: c_int, min_batch_size: c_int, user_data: *mut c_void) -> ();

    /// Draws FPS, Latency, and Memory stats
    pub fn SituationDrawMetricsOverlay(cmd: SituationCommandBuffer, position: Vector2, color: ColorRGBA) -> ();

    /// Draws all sub-meshes of a model with a single root transformation.
    pub fn SituationDrawModel(cmd: SituationCommandBuffer, model: SituationModel, transform: Mat4) -> SituationError;

    /// Prints the current task graph state to the stream.
    pub fn SituationDumpTaskGraph(pool: *mut SituationThreadPool, out_stream: *mut FILE, json_mode: bool) -> ();

    /// Metrics-only dump
    pub fn SituationDumpThreadPoolMetrics(pool: *mut SituationThreadPool, out_stream: *mut FILE, json_mode: bool) -> ();

    /// Pool metrics + per-role CPU snapshot
    pub fn SituationDumpThreadPoolStatus(pool: *mut SituationThreadPool, out_stream: *mut FILE, json_mode: bool) -> ();

    /// Status + topology line + pool dump
    pub fn SituationDumpThreadingReport(pool: *mut SituationThreadPool, out_stream: *mut FILE, json_mode: bool) -> ();

    /// Enable MIDI CC control for a node. Pass device_id=-1 for auto-select.
    pub fn SituationEnableMidiControl(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, device_id: c_int) -> SituationError;

    /// Enable MIDI Learn capability for a node. MIDI must already be enabled.
    pub fn SituationEnableMidiLearn(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> SituationError;

    /// Submit all commands for the frame and present the result.
    pub fn SituationEndFrame() -> SituationError;

    /// Enumerate available audio devices. Caller must free with SituationFreeDeviceList.
    pub fn SituationEnumerateAudioDevices(out_count: *mut c_int) -> *mut SituationAudioDeviceInfo;

    /// Human-readable base label for an error code (from the errno table).
    pub fn SituationErrorToString(err: SituationError) -> *const c_char;

    /// Execute a shell command hidden, return exit code & combined output.
    pub fn SituationExecuteCommand() -> c_int;

    /// Export image data (.png, .bmp, .jpg, .tga, .hdr).
    pub fn SituationExportImage(image: SituationImage) -> SituationError;

    /// Write a text-based frame time histogram into buf.
    pub fn SituationExportRenderHistogram(buf: *const c_char, buf_size: usize) -> ();

    /// Check if a file exists at the given path.
    pub fn SituationFileExists(file_path: *const c_char) -> bool;

    /// Find the best matching device by type and channel requirements.
    pub fn SituationFindBestDevice(preferred_type: SituationAudioDeviceType, min_channels_out: u32, min_channels_in: u32) -> *mut SituationAudioDeviceInfo;

    /// Free a device list returned by SituationEnumerateAudioDevices.
    pub fn SituationFreeDeviceList(devices: *mut SituationAudioDeviceInfo, count: c_int) -> ();

    /// Free the memory allocated by SituationListDirectoryFiles.
    pub fn SituationFreeDirectoryFileList(file_list: *const *const c_char, count: c_int) -> ();

    /// Free a display info array returned by SituationGetDisplays.
    pub fn SituationFreeDisplays(displays: *mut SituationDisplayInfo, count: c_int) -> ();

    /// Free a JSON string returned by SituationSerializeGraphToJSON.
    pub fn SituationFreeJSONString(json_string: *const c_char) -> ();

    /// Free a process list returned by SituationGetProcessList().
    pub fn SituationFreeProcessList(list: *mut SituationProcessInfo, count: c_int) -> ();

    /// Free a string allocated by the library (e.g., from path helpers).
    pub fn SituationFreeString(str: *const c_char) -> ();

    /// Generate a new image of a solid color.
    pub fn SituationGenImageColor(width: c_int, height: c_int, color: ColorRGBA, out_image: *mut SituationImage) -> SituationError;

    /// Generate a new image with a gradient.
    pub fn SituationGenImageGradient(width: c_int, height: c_int, tl: ColorRGBA, tr: ColorRGBA, bl: ColorRGBA, br: ColorRGBA, out_image: *mut SituationImage) -> SituationError;

    /// Get the name of the currently active playback device (static buffer, do not free).
    pub fn SituationGetActiveAudioDeviceName() -> *const c_char;

    /// Get the currently active audio processing graph (NULL if none).
    pub fn SituationGetActiveGraph() -> *mut SituationAudioGraph;

    /// active_jobs counter
    pub fn SituationGetActiveJobCount(pool: *mut SituationThreadPool) -> c_int;

    /// Get a safe, persistent path for saving application data (caller must free).
    pub fn SituationGetAppSavePath(app_name: *const c_char) -> *const c_char;

    /// Get the value of an argument (e.g., "jungle" from "-level:jungle").
    pub fn SituationGetArgumentValue(arg_name: *const c_char) -> *const c_char;

    /// Get a list of available audio playback devices (caller must free).
    pub fn SituationGetAudioDevices(count: *mut c_int) -> *mut SituationAudioDeviceInfo;

    /// Get the master volume for the audio device.
    pub fn SituationGetAudioMasterVolume() -> f32;

    /// Get the sample rate of the current audio device.
    pub fn SituationGetAudioPlaybackSampleRate() -> c_int;

    /// Get the path to the directory containing the executable (caller must free).
    pub fn SituationGetBasePath() -> *const c_char;

    /// Read data from a GPU buffer (blocking).
    pub fn SituationGetBufferData(buffer: SituationBuffer, offset: usize, size: usize, out_data: *mut c_void) -> SituationError;

    /// Retrieves the GPU device address of a buffer for bindless access.
    pub fn SituationGetBufferDeviceAddress(buffer: SituationBuffer) -> u64;

    /// Gets physical processors (Cores) from cached topology
    pub fn SituationGetCPUCoreCount() -> u32;

    /// CPU name, core/thread counts, and clock speed.
    pub fn SituationGetCPUInfo(out: *mut SituationCPUInfo) -> ();

    /// Get the number of logical CPU cores.
    pub fn SituationGetCPUThreadCount() -> u32;

    /// Get the display name for a device category.
    pub fn SituationGetCategoryName(category: SituationDeviceCategory) -> *const c_char;

    /// Maps a physical key scancode (plus modifiers) to a Unicode character, respecting the current OS keyboard layout.
    pub fn SituationGetCharFromScancode(window: c_int, scancode: c_int, mods: c_int, out_char: *mut u32) -> c_int;

    /// Get the next character from the text input queue.
    pub fn SituationGetCharPressed() -> c_uint;

    /// Get text from the system clipboard.
    pub fn SituationGetClipboardText(out_text: *const *const c_char) -> SituationError;

    /// [v2.3.23] Get the compute-specific command buffer (Vulkan only).
    pub fn SituationGetComputeCommandBuffer() -> SituationCommandBuffer;

    /// Effective audio mask (init or default)
    pub fn SituationGetConfiguredAudioThreadAffinity() -> u64;

    /// Effective I/O mask (init or default CPU 3)
    pub fn SituationGetConfiguredIOThreadAffinity() -> u64;

    /// Init mask for main thread (0 = no pin)
    pub fn SituationGetConfiguredMainThreadAffinity() -> u64;

    /// Effective render mask (init or default)
    pub fn SituationGetConfiguredRenderThreadAffinity() -> u64;

    /// Get the current value of a node's control parameter.
    pub fn SituationGetControl(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, control_id: u32, out_value: *mut f32) -> SituationError;

    /// Pointer to cached topology (NULL on failure)
    pub fn SituationGetCpuTopology(out_topology: *mut SituationCpuTopology) -> SituationError;

    /// Gets flags based on current GLFW window state
    pub fn SituationGetCurrentActualWindowStateFlags() -> u32;

    /// Get the drive letter of the running executable (Windows only).
    pub fn SituationGetCurrentDriveLetter() -> c_char;

    /// Get the index of the monitor the window is on.
    pub fn SituationGetCurrentMonitor() -> c_int;

    /// Logical CPU index for current thread, or -1 if unknown
    pub fn SituationGetCurrentProcessorIndex() -> c_int;

    /// [DEPRECATED] Aggregated snapshot; prefer split queries below.
    pub fn SituationGetDeviceInfo() -> SituationDeviceInfo;

    /// Get metadata for a registered device type.
    pub fn SituationGetDeviceMetadata(r#type: SituationNodeType, out_meta: *mut SituationDeviceMetadata) -> SituationError;

    /// Get information for all displays (caller must free).
    pub fn SituationGetDisplays(out_displays: *mut SituationDisplayInfo, out_count: *mut c_int) -> SituationError;

    /// Number of draw commands this frame
    pub fn SituationGetDrawCallCount() -> u32;

    /// Get info for a specific drive (Windows only).
    pub fn SituationGetDriveInfo(drive_letter: c_char, out_total_capacity_bytes: *mut u64, out_free_space_bytes: *mut u64, out_volume_name: *const c_char, volume_name_len: c_int) -> bool;

    /// Get the current frames-per-second value.
    pub fn SituationGetFPS() -> c_int;

    /// Extract the file extension from a path.
    pub fn SituationGetFileExtension(file_path: *const c_char) -> *const c_char;

    /// Get the last modification time of a file (Unix timestamp).
    pub fn SituationGetFileModTime(file_path: *const c_char) -> c_long;

    /// Extract the file name (including extension) from a full path.
    pub fn SituationGetFileName(full_path: *const c_char) -> *const c_char;

    /// Get the time in seconds for the last frame to complete (deltaTime).
    pub fn SituationGetFrameTime() -> f32;

    /// Get the raw GLFW window handle.
    pub fn SituationGetGLFWwindow() -> *mut GLFWwindow;

    /// GPU name and dedicated VRAM (when available).
    pub fn SituationGetGPUInfo(out: *mut SituationGPUInfo) -> ();

    /// Get the name of the active GPU.
    pub fn SituationGetGPUName() -> *const c_char;

    /// Get the number of axes for a gamepad.
    pub fn SituationGetGamepadAxisCount(jid: c_int) -> c_int;

    /// Get the value of a gamepad axis (deadzone applied).
    pub fn SituationGetGamepadAxisValue(jid: c_int, axis: c_int) -> f32;

    /// Get the next gamepad button from the press queue.
    pub fn SituationGetGamepadButtonPressed() -> c_int;

    pub fn SituationGetGraphicsBackend() -> SituationGraphicsBackend;
    pub fn SituationGetGraphicsBackendName() -> *const c_char;
    /// Get backend capabilities for examples/frameworks.
    pub fn SituationGetGraphicsCaps(out_caps: *mut SituationGraphicsCaps) -> ();

    /// High-priority queue depth
    pub fn SituationGetHighQueueDepth(pool: *mut SituationThreadPool) -> usize;

    /// [v2.3.37] Get the current depth of the IO/Low Priority queue
    pub fn SituationGetIOQueueDepth() -> usize;

    /// Query the current initialization state (thread-safe).
    pub fn SituationGetInitState() -> SituationInitState;

    /// Number of input devices (keyboard/mouse/gamepad).
    pub fn SituationGetInputDeviceCount() -> c_int;

    pub fn SituationGetInputDeviceName(index: c_int, out_name: *const c_char, name_len: c_int) -> bool;
    /// Returns pointer to the library's internal thread pool (NULL if not initialized).
    pub fn SituationGetInternalThreadPool() -> *mut SituationThreadPool;

    /// Get the human-readable name of a joystick/gamepad.
    pub fn SituationGetJoystickName(jid: c_int) -> *const c_char;

    /// Get the next key from the press queue (no repeats).
    pub fn SituationGetKeyPressed() -> c_int;

    /// Get the next key and its scancode from the queue.
    pub fn SituationGetKeyPressedEx(out_scancode: *mut c_int) -> c_int;

    /// Get the platform-specific scancode for a logical key.
    pub fn SituationGetKeyScancode(key: c_int) -> c_int;

    /// Get the SituationError enum from the most recent _SituationSetErrorFromCode call.
    pub fn SituationGetLastErrorCode() -> SituationError;

    /// Get the last error message as a string (caller must free).
    pub fn SituationGetLastErrorMsg(out_msg: *const *const c_char) -> SituationError;

    /// Get the time taken for the last virtual display composite pass.
    pub fn SituationGetLastVDCompositeTimeMS() -> f64;

    /// Get the primary command buffer for the current frame.
    pub fn SituationGetMainCommandBuffer() -> SituationCommandBuffer;

    /// Get the render pass for the main window.
    pub fn SituationGetMainWindowRenderPass() -> VkRenderPass;

    /// Last playback callback block: peak sample magnitude & RMS (optional pointers; safe from main/UI thread).
    pub fn SituationGetMasterOutputMeter(out_peak: *mut f32, out_rms: *mut f32) -> ();

    /// Query maximum compute work group count per dispatch.
    pub fn SituationGetMaxComputeWorkGroups(x: *mut u32, y: *mut u32, z: *mut u32) -> ();

    /// Total and available physical RAM.
    pub fn SituationGetMemoryInfo(out: *mut SituationMemoryInfo) -> ();

    /// Get raw vertex/index data pointers from a mesh (read-only).
    pub fn SituationGetMeshData(mesh: SituationMesh, vertex_data: *mut c_void, vertex_count: *mut c_int, vertex_stride: *mut c_int, index_data: *mut c_void, index_count: *mut c_int) -> ();

    /// Retrieves the GPU device address of the mesh index buffer. [VK] requires SIT_FEATURE_BINDLESS_BUFFERS; [GL] NVIDIA-only via NV_shader_buffer_load. Returns 0 if unsupported.
    pub fn SituationGetMeshIndexBufferAddress(mesh: SituationMesh) -> u64;

    /// Retrieves the GPU device address of the mesh vertex buffer. [VK] requires SIT_FEATURE_BINDLESS_BUFFERS; [GL] NVIDIA-only via NV_shader_buffer_load. Returns 0 if unsupported.
    pub fn SituationGetMeshVertexBufferAddress(mesh: SituationMesh) -> u64;

    /// PortMidi device name for device_id (hardware or virtual).
    pub fn SituationGetMidiDeviceName(device_id: c_int, out_name: *const c_char, out_name_size: usize) -> SituationError;

    /// Get the number of connected monitors.
    pub fn SituationGetMonitorCount() -> c_int;

    /// Get the height of a monitor's current video mode.
    pub fn SituationGetMonitorHeight(monitor_id: c_int) -> c_int;

    /// Get the human-readable name of a monitor.
    pub fn SituationGetMonitorName(monitor_id: c_int) -> *const c_char;

    /// Get the physical height of a monitor in millimeters.
    pub fn SituationGetMonitorPhysicalHeight(monitor_id: c_int) -> c_int;

    /// Get the physical width of a monitor in millimeters.
    pub fn SituationGetMonitorPhysicalWidth(monitor_id: c_int) -> c_int;

    /// Get the top-left position of a monitor on the desktop.
    pub fn SituationGetMonitorPosition(monitor_id: c_int) -> Vector2;

    /// Get the refresh rate of a monitor.
    pub fn SituationGetMonitorRefreshRate(monitor_id: c_int) -> c_int;

    /// Get the width of a monitor's current video mode.
    pub fn SituationGetMonitorWidth(monitor_id: c_int) -> c_int;

    /// Get the mouse movement since the last frame.
    pub fn SituationGetMouseDelta() -> Vector2;

    /// Get the mouse position within the window.
    pub fn SituationGetMousePosition() -> Vector2;

    /// Get vertical mouse wheel movement.
    pub fn SituationGetMouseWheelMove() -> f32;

    /// Get vertical and horizontal mouse wheel movement.
    pub fn SituationGetMouseWheelMoveV() -> Vector2;

    /// Number of network adapters reported by the OS.
    pub fn SituationGetNetworkAdapterCount() -> c_int;

    pub fn SituationGetNetworkAdapterName(index: c_int, out_name: *const c_char, name_len: c_int) -> bool;
    /// Get a direct pointer to a node (for advanced use).
    pub fn SituationGetNode(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> *mut SituationNode;

    /// Query how many frames of space are available in the PCM_INPUT node's ring buffer.
    pub fn SituationGetNodePCMFreeFrames(graph: *mut SituationAudioGraph, node: SituationNodeHandle) -> u32;

    /// Cached NUMA snapshot
    pub fn SituationGetNumaTopology(out_topology: *mut SituationNumaTopology) -> SituationError;

    /// Get operating system name, version, and build number.
    pub fn SituationGetOSInfo() -> SituationOSInfo;

    /// TLS: node for current thread, or -1 if unset
    pub fn SituationGetPreferredNumaNode() -> c_int;

    /// Get snapshot of running OS processes. Caller must free with SituationFreeProcessList().
    pub fn SituationGetProcessList(out_count: *mut c_int) -> *mut SituationProcessInfo;

    /// Pending jobs per queue mask
    pub fn SituationGetQueueDepth(pool: *mut SituationThreadPool, mask: SituationJobQueueMask) -> usize;

    /// Sizing helper (no pool required)
    pub fn SituationGetRecommendedWorkerCount(reserved_threads: u32, use_physical_cores: bool) -> u32;

    /// Get the number of registered audio device types.
    pub fn SituationGetRegisteredDeviceCount() -> c_int;

    /// Get the current render height (backbuffer size, considers HiDPI).
    pub fn SituationGetRenderHeight() -> c_int;

    /// Get render thread latency metrics
    pub fn SituationGetRenderLatencyStats(avg_ns: *mut u64, max_ns: *mut u64) -> ();

    /// Get the current depth of the render queue
    pub fn SituationGetRenderQueueDepth() -> usize;

    /// Get the current render width (backbuffer size, considers HiDPI).
    pub fn SituationGetRenderWidth() -> c_int;

    /// Get the current active renderer type (OpenGL or Vulkan).
    pub fn SituationGetRendererType() -> SituationRendererType;

    /// Get the current logical height of the window.
    pub fn SituationGetScreenHeight() -> c_int;

    /// Get the current logical width of the window.
    pub fn SituationGetScreenWidth() -> c_int;

    /// Get the current default screenshot format.
    pub fn SituationGetScreenshotFormat() -> SituationScreenshotFormat;

    /// Get the current serialization format version string.
    pub fn SituationGetSerializationVersion() -> *const c_char;

    /// Get the stereo pan of a sound.
    pub fn SituationGetSoundPan(sound: *mut SituationSound) -> f32;

    /// Get the pitch of a sound.
    pub fn SituationGetSoundPitch(sound: *mut SituationSound) -> f32;

    /// Get the volume of a specific sound.
    pub fn SituationGetSoundVolume(sound: *mut SituationSound) -> f32;

    pub fn SituationGetStorageDevice(index: c_int, out_name: *const c_char, name_len: c_int, out_capacity_bytes: *mut u64, out_free_bytes: *mut u64) -> bool;
    /// Number of storage volumes reported by the OS.
    pub fn SituationGetStorageDeviceCount() -> c_int;

    /// Retrieves the bindless texture handle (OpenGL Only).
    pub fn SituationGetTextureHandle(texture: SituationTexture) -> u64;

    /// [Phase 2] Query texture metadata.
    pub fn SituationGetTextureInfo(texture: SituationTexture, out_info: *mut SituationTextureInfo) -> SituationError;

    /// Reads affinity mask for the CURRENT thread
    pub fn SituationGetThreadAffinity(out_mask: *mut u64) -> SituationError;

    /// NUMA node for current thread, or -1 if unknown
    pub fn SituationGetThreadNumaNode() -> c_int;

    /// Scheduler counters snapshot
    pub fn SituationGetThreadPoolMetrics(pool: *mut SituationThreadPool, out_metrics: *mut SituationThreadPoolMetrics) -> SituationError;

    /// Worker/I/O/render/audio placement snapshot
    pub fn SituationGetThreadPoolSnapshot(pool: *mut SituationThreadPool, out: *mut SituationThreadPoolSnapshot) -> SituationError;

    /// Runtime threading capabilities + pool summary
    pub fn SituationGetThreadingStatus() -> SituationThreadingStatus;

    /// Get the full path to the current user's home directory (caller must free).
    pub fn SituationGetUserDirectory() -> *const c_char;

    /// Total GPU memory allocated (Bytes)
    pub fn SituationGetVRAMUsage() -> u64;

    /// Returns a read-only static string (e.g., "2.3.3A"). Do not free.
    pub fn SituationGetVersionString() -> *const c_char;

    /// Get a pointer to a virtual display's state.
    pub fn SituationGetVirtualDisplay(display_id: c_int) -> *mut SituationVirtualDisplay;

    /// Get the internal resolution of a virtual display.
    pub fn SituationGetVirtualDisplaySize(display_id: c_int, width: *mut c_int, height: *mut c_int) -> ();

    /// Get the VD's internal texture as a SituationTexture handle (valid for compute-target VDs).
    pub fn SituationGetVirtualDisplayTexture(display_id: c_int, out_texture: *mut SituationTexture) -> SituationError;

    /// Query last VD content write (not the frame clock).
    pub fn SituationGetVirtualDisplayUpdateInfo(display_id: c_int, out_last_content_update_time: *mut f64, out_last_content_update_frame: *mut u64, out_frames_since_update: *mut u64, out_seconds_since_update: *mut f64) -> SituationError;

    /// Get the raw Vulkan logical device handle.
    pub fn SituationGetVulkanDevice() -> VkDevice;

    /// Get the raw Vulkan instance handle.
    pub fn SituationGetVulkanInstance() -> VkInstance;

    /// Get the raw Vulkan physical device handle.
    pub fn SituationGetVulkanPhysicalDevice() -> VkPhysicalDevice;

    /// Get the window's top-left position on the screen.
    pub fn SituationGetWindowPosition() -> Vector2;

    /// Get the DPI scaling factor for the window.
    pub fn SituationGetWindowScaleDPI() -> Vector2;

    /// Get the current logical window size.
    pub fn SituationGetWindowSize(width: *mut c_int, height: *mut c_int) -> ();

    /// Check if the window is currently focused.
    pub fn SituationHasWindowFocus() -> bool;

    /// Hide the mouse cursor.
    pub fn SituationHideCursor() -> ();

    /// Converts a Hue, Saturation, Value color back to the standard RGBA color space.
    pub fn SituationHsvToRgb(hsv: ColorHSV) -> ColorRGBA;

    /// Control an image by Hue Saturation and Brightness.
    pub fn SituationImageAdjustHSV(hue_shift: f32, sat_factor: f32, val_factor: f32, mix: f32) -> ();

    /// Grade an image in YPQ (phase/chroma/luma).
    pub fn SituationImageAdjustYPQ(phase_shift_deg: f32, chroma_factor: f32, luma_factor: f32, mix: f32) -> ();

    /// Create a new image by copying another.
    pub fn SituationImageCopy(image: SituationImage, out_image: *mut SituationImage) -> SituationError;

    /// Crop an image to a specific rectangle.
    pub fn SituationImageCrop(crop: SitRectangle) -> ();

    /// Copying portion of one image into another image at destination placement
    pub fn SituationImageDraw(src: SituationImage, srcRect: SitRectangle, dstPos: Vector2) -> ();

    /// Draw a portion of a source image onto dst with alpha tinting.
    pub fn SituationImageDrawAlpha(src: SituationImage, srcRect: SitRectangle, dstPos: Vector2, tint: ColorRGBA) -> ();

    /// Draw a single Unicode character with advanced styling onto an image.
    pub fn SituationImageDrawCodepoint(font: SituationFont, codepoint: c_int, position: Vector2, fontSize: f32, rotationDegrees: f32, skewFactor: f32, fillColor: ColorRGBA, outlineColor: ColorRGBA, outlineThickness: f32) -> ();

    /// Draw a simple, tinted text string onto an image.
    pub fn SituationImageDrawText(font: SituationFont, position: Vector2, fontSize: f32, spacing: f32, tint: ColorRGBA) -> ();

    /// Draw a text string with advanced styling (rotation, outline) onto an image.
    pub fn SituationImageDrawTextEx(font: SituationFont, position: Vector2, fontSize: f32, spacing: f32, rotationDegrees: f32, skewFactor: f32, fillColor: ColorRGBA, outlineColor: ColorRGBA, outlineThickness: f32) -> ();

    /// Flip an image.
    pub fn SituationImageFlip(mode: SituationImageFlipMode) -> ();

    /// Resize an image using default bicubic scaling.
    pub fn SituationImageResize(newWidth: c_int, newHeight: c_int) -> ();

    /// Initialize the library, create window and graphics context.
    pub fn SituationInit(argc: c_int, argv: *const *const c_char, init_info: *mut SituationInitInfo) -> SituationError;

    /// Initialize the built-in device registry (call once at startup).
    pub fn SituationInitDeviceRegistry() -> ();

    /// Check if the application is currently paused.
    pub fn SituationIsAppPaused() -> bool;

    /// Check if a command-line argument (e.g., "-server") was provided.
    pub fn SituationIsArgumentPresent(arg_name: *const c_char) -> bool;

    /// Check if the audio device is currently playing.
    pub fn SituationIsAudioDevicePlaying() -> bool;

    /// Check if a device type is registered.
    pub fn SituationIsDeviceRegistered(r#type: SituationNodeType) -> bool;

    /// Check if a graphics feature is supported on current hardware.
    pub fn SituationIsFeatureSupported(feature: SituationRenderFeature) -> bool;

    /// Check if a file was dropped into the window this frame.
    pub fn SituationIsFileDropped() -> bool;

    /// Check if a connected joystick has a standard gamepad mapping.
    pub fn SituationIsGamepad(jid: c_int) -> bool;

    /// Check if a gamepad button is currently held down (a state).
    pub fn SituationIsGamepadButtonDown(jid: c_int, button: c_int) -> bool;

    /// Check if a gamepad button was pressed down this frame (an event).
    pub fn SituationIsGamepadButtonPressed(jid: c_int, button: c_int) -> bool;

    /// Check if a gamepad button was released this frame (an event).
    pub fn SituationIsGamepadButtonReleased(jid: c_int, button: c_int) -> bool;

    /// Check if an image has been loaded successfully.
    pub fn SituationIsImageValid(image: SituationImage) -> bool;

    /// Check if the library has been successfully initialized.
    pub fn SituationIsInitialized() -> bool;

    /// Check if a joystick/gamepad is connected.
    pub fn SituationIsJoystickPresent(jid: c_int) -> bool;

    /// Check if a key is currently held down (a state).
    pub fn SituationIsKeyDown(key: c_int) -> bool;

    /// Check if a key was pressed down this frame (an event).
    pub fn SituationIsKeyPressed(key: c_int) -> bool;

    /// Check if a key was released this frame (an event).
    pub fn SituationIsKeyReleased(key: c_int) -> bool;

    /// Check if a key is currently up (a state).
    pub fn SituationIsKeyUp(key: c_int) -> bool;

    /// Check if currently in learn mode. Returns 1/0.
    pub fn SituationIsLearning(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> c_int;

    /// Check if a lock key (Caps, Num) is currently active.
    pub fn SituationIsLockKeyPressed(lock_key_mod: c_int) -> bool;

    /// Check if a node has MIDI control enabled. Returns 1/0.
    pub fn SituationIsMidiEnabled(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> c_int;

    /// Check if MIDI Learn is enabled. Returns 1/0.
    pub fn SituationIsMidiLearnEnabled(graph: *mut SituationAudioGraph, handle: SituationNodeHandle) -> c_int;

    /// Check if a modifier key (Shift, Ctrl, Alt) is pressed.
    pub fn SituationIsModifierPressed(modifier: c_int) -> bool;

    /// Check if a mouse button is currently held down (a state).
    pub fn SituationIsMouseButtonDown(button: c_int) -> bool;

    /// Check if a mouse button was pressed down this frame (an event).
    pub fn SituationIsMouseButtonPressed(button: c_int) -> bool;

    /// Check if a mouse button was released this frame.
    pub fn SituationIsMouseButtonReleased(button: c_int) -> bool;

    /// Check if a physical key (scancode) is currently held down.
    pub fn SituationIsScancodeDown(scancode: c_int) -> bool;

    /// Check if Scroll Lock is currently toggled on.
    pub fn SituationIsScrollLockOn() -> bool;

    /// True for stb_image decode extensions (.jpg, .png, .bmp, .tga, .psd, .gif, .hdr, .pic, .ppm, .pgm, .pnm).
    pub fn SituationIsStbImageLoadExtension(extension: *const c_char) -> bool;

    /// Check if a serialized version is compatible with this library.
    pub fn SituationIsVersionCompatible(json_version: *const c_char) -> bool;

    /// Check if a virtual display is marked as dirty.
    pub fn SituationIsVirtualDisplayDirty(display_id: c_int) -> bool;

    /// Check if the window is currently in fullscreen mode.
    pub fn SituationIsWindowFullscreen() -> bool;

    /// Check if the window is currently hidden.
    pub fn SituationIsWindowHidden() -> bool;

    /// Check if the window is currently maximized.
    pub fn SituationIsWindowMaximized() -> bool;

    /// Check if the window is currently minimized.
    pub fn SituationIsWindowMinimized() -> bool;

    /// Check if the window was resized in the last frame.
    pub fn SituationIsWindowResized() -> bool;

    /// Check if a specific window state flag is set.
    pub fn SituationIsWindowState(flag: u32) -> bool;

    /// Join two path components with the correct OS separator (caller must free).
    pub fn SituationJoinPath(base_path: *const c_char, file_or_dir_name: *const c_char) -> *const c_char;

    /// List files and subdirectories in a path (caller must free with SituationFreeDirectoryFileList).
    pub fn SituationListDirectoryFiles(dir_path: *const c_char, out_count: *mut c_int) -> *const *const c_char;

    /// List available MIDI input devices. Returns number found.
    pub fn SituationListMidiDevices(devices: *mut SituationMidiDeviceInfo, max_count: c_int) -> c_int;

    /// Load audio and return a lightweight handle for playback control.
    pub fn SituationLoadAudio(file_path: *const c_char, mode: SituationAudioLoadMode, looping: bool) -> SituationSoundHandle;

    /// Loads a raw bitmap font (e.g. 8x8 array).
    pub fn SituationLoadBitmapFontFromMemory(data: *mut u8, char_width: c_int, char_height: c_int, num_chars: c_int, out_font: *mut SituationFont) -> SituationError;

    /// [DEPRECATED] Load a compute shader from a file. Use SituationCreateComputePipeline instead.
    pub fn SituationLoadComputeShader(cs_path: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// [DEPRECATED] Create a compute shader from memory. Use SituationCreateComputePipelineFromMemory instead.
    pub fn SituationLoadComputeShaderFromMemory(cs_code: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// Get the paths of dropped files (returns a copy, caller must free).
    pub fn SituationLoadDroppedFiles(count: *mut c_int) -> *const *const c_char;

    /// Asynchronously load a file.
    pub fn SituationLoadFileAsync(pool: *mut SituationThreadPool, file_path: *const c_char, callback: SituationFileLoadCallback, user_data: *mut c_void) -> SituationJobId;

    /// Load an entire file into a memory buffer (caller must free).
    pub fn SituationLoadFileData(file_path: *const c_char, out_bytes_read: *mut c_uint, out_data: *mut u8) -> SituationError;

    /// Load a text file into a null-terminated string (caller must free).
    pub fn SituationLoadFileText(file_path: *const c_char) -> *const c_char;

    /// Asynchronously load a text file.
    pub fn SituationLoadFileTextAsync(pool: *mut SituationThreadPool, file_path: *const c_char, callback: SituationFileTextLoadCallback, user_data: *mut c_void) -> SituationJobId;

    /// Load a font from a TTF/OTF file for CPU rendering.
    pub fn SituationLoadFont(out_font: *mut SituationFont) -> SituationError;

    /// Loads a font directly from a memory buffer (e.g., embedded resource).
    pub fn SituationLoadFontFromMemory(data: *mut c_void, dataSize: c_int, out_font: *mut SituationFont) -> SituationError;

    /// Load a graph from a JSON file, re-creating nodes via device_funcs.
    pub fn SituationLoadGraphFromFile(graph: *mut SituationAudioGraph, filepath: *const c_char, device_funcs: *mut SituationDeviceFunctions, num_device_funcs: c_int) -> SituationError;

    /// Load an image via stb_image (JPEG, PNG, BMP, TGA, PSD, GIF, HDR, PIC, PNM).
    pub fn SituationLoadImage(out_image: *mut SituationImage) -> SituationError;

    /// Load an image from a memory buffer.
    pub fn SituationLoadImageFromMemory(dataSize: c_int, out_image: *mut SituationImage) -> SituationError;

    /// Get a copy of the current screen backbuffer as an image.
    pub fn SituationLoadImageFromScreen(out_image: *mut SituationImage) -> SituationError;

    /// Load MIDI Learn mappings from JSON file.
    pub fn SituationLoadMidiPreset(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, filename: *const c_char) -> SituationError;

    /// Loads a complete 3D model and its textures from a GLTF file.
    pub fn SituationLoadModel(file_path: *const c_char, out_model: *mut SituationModel) -> SituationError;

    /// Wavefront OBJ: triangulated meshes, MTL/textures; missing/degenerate normals filled from face geometry, authored normals preserved.
    pub fn SituationLoadModelFromOBJ(file_path: *const c_char, out_model: *mut SituationModel) -> SituationError;

    /// Loads a 3D model from a binary or ASCII STL file. UVs are zeroed; normals are flat (per-face) by default, or smooth (averaged per shared vertex) when smooth_normals is true.
    pub fn SituationLoadModelFromSTL(file_path: *const c_char, smooth_normals: bool, out_model: *mut SituationModel) -> SituationError;

    /// Load a graphics shader pipeline from vertex and fragment files.
    pub fn SituationLoadShader(vs_path: *const c_char, fs_path: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// Create a graphics shader pipeline from in-memory GLSL source.
    pub fn SituationLoadShaderFromMemory(vs_code: *const c_char, fs_code: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// Precompiled .spv: OpenGL via GL_ARB_gl_spirv; Vulkan same pipeline contract as SituationLoadShaderFromMemory (no shaderc required).
    pub fn SituationLoadShaderFromSpirv(vs_spv_path: *const c_char, fs_spv_path: *const c_char, out_shader: *mut SituationShader) -> SituationError;

    /// Same as SituationLoadShaderFromSpirv but from in-memory SPIR-V (e.g. build-time embedded .spv). No hot-reload paths (vs/fs file paths left unset).
    pub fn SituationLoadShaderFromSpirvMemory(vs_spirv: *mut c_void, vs_len: usize, fs_spirv: *mut c_void, fs_len: usize, out_shader: *mut SituationShader) -> SituationError;

    /// [Vulkan] `layout_profile` selects user SSBO/UBO layouts; [OpenGL] profile ignored.
    pub fn SituationLoadShaderFromSpirvMemoryEx(vs_spirv: *mut c_void, vs_len: usize, fs_spirv: *mut c_void, fs_len: usize, layout_profile: SituationSpirvLayoutProfile, out_shader: *mut SituationShader) -> SituationError;

    /// Load a sound from a file.
    pub fn SituationLoadSoundFromFile(file_path: *const c_char, mode: SituationAudioLoadMode, looping: bool, out_sound: *mut SituationSound) -> SituationError;

    /// Asynchronously loads and decodes a sound file.
    pub fn SituationLoadSoundFromFileAsync(pool: *mut SituationThreadPool, file_path: *const c_char, looping: bool, out_sound: *mut SituationSound) -> SituationJobId;

    /// Load a sound from a custom stream.
    pub fn SituationLoadSoundFromStream(on_read: SituationStreamReadCallback, on_seek: SituationStreamSeekCallback, user_data: *mut c_void, format: *mut SituationAudioFormat, looping: bool, out_sound: *mut SituationSound) -> SituationError;

    /// Loads a texture from disk and registers the path for hot-reloading.
    pub fn SituationLoadTexture(file_path: *const c_char, generate_mipmaps: bool, out_texture: *mut SituationTexture) -> SituationError;

    /// Maximize the window if it's resizable.
    pub fn SituationMaximizeWindow() -> ();

    /// Measure the pixel dimensions of a string before drawing.
    pub fn SituationMeasureText(font: SituationFont, fontSize: f32) -> SitRectangle;

    /// [DEPRECATED] Insert a coarse-grained memory barrier. Use SituationCmdPipelineBarrierEx, SituationCmdBufferBarrier, or SituationCmdTextureBarrier instead.
    pub fn SituationMemoryBarrier(cmd: SituationCommandBuffer, barrier_bits: u32) -> ();

    /// Minimize the window (iconify).
    pub fn SituationMinimizeWindow() -> ();

    /// Move/rename a file, even across drives on Windows.
    pub fn SituationMoveFile(old_path: *const c_char, new_path: *const c_char) -> SituationError;

    /// Open a file or folder with its default application.
    pub fn SituationOpenFile(filePath: *const c_char) -> ();

    /// Pause the application's internal state (e.g., audio).
    pub fn SituationPauseApp() -> ();

    /// Pause audio playback on the device.
    pub fn SituationPauseAudioDevice() -> SituationError;

    /// Peek at the next key in the press queue without consuming it.
    pub fn SituationPeekKeyPressed() -> c_int;

    /// Peek at the next key and its scancode.
    pub fn SituationPeekKeyPressedEx(out_scancode: *mut c_int) -> c_int;

    /// Play audio by handle (restarts if already playing).
    pub fn SituationPlayAudio(handle: SituationSoundHandle) -> SituationError;

    /// Play a loaded sound (restarts if already playing).
    pub fn SituationPlayLoadedSound(sound: *mut SituationSound) -> SituationError;

    /// Legacy: play a tone by MIDI note number (0-127).
    pub fn SituationPlayMidiNote(note: c_int, r#type: SituationWaveType, volume: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) -> ();

    /// Legacy: play a simple ADSR tone (backward compat / quick UI sounds).
    pub fn SituationPlayTone(r#type: SituationWaveType, frequency: f32, volume: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) -> ();

    /// @brief Plays an extended procedural tone with full control. @param type          Waveform type (Sine, Square, Triangle, Saw, Noise) @param frequency     Frequency in Hz (e.g., 440.0f). For noise: ignored (use 0.0f) @param volume        Peak volume (0.0 to 1.0) @param pan           Stereo panning (-1.0 left, 0.0 center, +1.0 right) @param attack_sec    Attack time in seconds @param decay_sec     Decay time in seconds @param sustain_level Sustain volume level (0.0 to 1.0) @param release_sec   Release time in seconds @param hold_sec      Hold duration in seconds. Use -1.0f for infinite sustain (key down) @return Handle to the playing tone, or 0 if no voice available (polyphony limit)
    pub fn SituationPlayToneEx(r#type: SituationWaveType, frequency: f32, volume: f32, pan: f32, attack_sec: f32, decay_sec: f32, sustain_level: f32, release_sec: f32, hold_sec: f32) -> SituationToneHandle;

    /// Poll for all input events (keyboard, mouse, joystick). Call once per frame.
    pub fn SituationPollInputEvents() -> ();

    /// SITUATION_SUCCESS when ready, SITUATION_ERROR_SHADER_LOAD_IN_PROGRESS while compiling/linking/building pipelines.
    pub fn SituationPollShaderLoad(shader: SituationShader) -> SituationError;

    /// Human-readable threading status (stdout if NULL)
    pub fn SituationPrintThreadingStatus(out_stream: *mut FILE) -> ();

    /// Push interleaved float PCM into a PCM_INPUT node's ring buffer (any thread). Returns frames written.
    pub fn SituationPushNodePCM(graph: *mut SituationAudioGraph, node: SituationNodeHandle, samples: *mut f32, frame_count: u32, channels: u32) -> u32;

    /// [OpenGL] Enumerate all active SSBO blocks and their assigned binding points. out_count receives actual block count (may exceed capacity). Returns NOT_IMPLEMENTED on Vulkan.
    pub fn SituationQueryShaderStorageBlocks(shader: SituationShader, out_blocks: *mut SituationShaderStorageBlockInfo, capacity: c_int, out_count: *mut c_int) -> SituationError;

    /// Read mapped buffer data safely.
    pub fn SituationReadBuffer(readback_buf: SituationBuffer, dst: *mut c_void, size: usize) -> SituationError;

    /// [Phase 2] Blocking readback of framebuffer pixels.
    pub fn SituationReadFramebuffer(desc: *mut SituationReadPixelsDesc, dst_pixels: *mut c_void, dst_size_bytes: usize) -> SituationError;

    /// [Phase 2] Blocking readback of texture pixels.
    pub fn SituationReadTexture(texture: SituationTexture, desc: *mut SituationTextureReadbackDesc, dst_pixels: *mut c_void, dst_size_bytes: usize) -> SituationError;

    /// [Phase 2] Blocking readback into allocated SituationImage.
    pub fn SituationReadTextureAlloc(texture: SituationTexture, desc: *mut SituationTextureReadbackDesc, out_image: *mut SituationImage) -> SituationError;

    /// Rebuilds the process-wide topology cache
    pub fn SituationRefreshCpuTopology() -> SituationError;

    /// Force a refresh of the cached display information.
    pub fn SituationRefreshDisplays() -> ();

    /// Rebuild NUMA summary from CPU topology + OS memory
    pub fn SituationRefreshNumaTopology() -> SituationError;

    /// Register a custom device type with the registry.
    pub fn SituationRegisterDeviceType(meta: *mut SituationDeviceMetadata) -> SituationError;

    /// Recompiles a compute pipeline from its original source file (Synchronous/Stalls GPU).
    pub fn SituationReloadComputePipeline(pipeline: *mut SituationComputePipeline) -> SituationError;

    /// Re-parses GLTF/GLB file and rebuilds all meshes and textures (Synchronous/Stalls GPU).
    pub fn SituationReloadModel(model: *mut SituationModel) -> SituationError;

    /// Recompiles and links a shader from its original source files (Synchronous/Stalls GPU).
    pub fn SituationReloadShader(shader: *mut SituationShader) -> SituationError;

    /// Re-reads image file and recreates the GPU texture resource (Synchronous/Stalls GPU).
    pub fn SituationReloadTexture(texture: *mut SituationTexture) -> SituationError;

    /// Disconnect a specific patch between two ports.
    pub fn SituationRemovePatch(graph: *mut SituationAudioGraph, src: SituationNodeHandle, src_port: c_int, dst: SituationNodeHandle, dst_port: c_int, is_control: bool) -> SituationError;

    /// Alias for SituationMoveFile.
    pub fn SituationRenameFile(old_path: *const c_char, new_path: *const c_char) -> SituationError;

    /// Composite all visible virtual displays to the current target.
    pub fn SituationRenderVirtualDisplays(cmd: SituationCommandBuffer) -> SituationError;

    /// Replay a previously recorded render list into a command buffer.
    pub fn SituationReplayRenderList(cmd: SituationCommandBuffer, list: SituationRenderList) -> ();

    /// Reset a render list for reuse next frame.
    pub fn SituationResetRenderList(list: SituationRenderList) -> ();

    /// Zero scheduler counters
    pub fn SituationResetThreadPoolStats(pool: *mut SituationThreadPool) -> ();

    /// Restore a minimized or maximized window.
    pub fn SituationRestoreWindow() -> ();

    /// Resume a paused application.
    pub fn SituationResumeApp() -> ();

    /// Resume audio playback on the device.
    pub fn SituationResumeAudioDevice() -> SituationError;

    /// Converts a standard RGBA color to the Hue, Saturation, Value color space.
    pub fn SituationRgbToHsv(rgb: ColorRGBA) -> ColorHSV;

    /// Asynchronously save a file.
    pub fn SituationSaveFileAsync(pool: *mut SituationThreadPool, file_path: *const c_char, data: *mut c_void, size: usize, callback: SituationFileSaveCallback, user_data: *mut c_void) -> SituationJobId;

    /// Save a block of memory to a file.
    pub fn SituationSaveFileData(file_path: *const c_char, data: *mut c_void, bytes_to_write: c_uint) -> SituationError;

    /// Save a null-terminated string to a text file.
    pub fn SituationSaveFileText(file_path: *const c_char, text: *const c_char) -> SituationError;

    /// Asynchronously save a text file.
    pub fn SituationSaveFileTextAsync(pool: *mut SituationThreadPool, file_path: *const c_char, text: *const c_char, callback: SituationFileSaveCallback, user_data: *mut c_void) -> SituationJobId;

    /// Save a graph to a JSON file.
    pub fn SituationSaveGraphToFile(graph: *mut SituationAudioGraph, filepath: *const c_char) -> SituationError;

    /// Save MIDI Learn mappings to JSON file.
    pub fn SituationSaveMidiPreset(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, filename: *const c_char) -> SituationError;

    /// Exports a model to a human-readable .gltf and a .bin file for debugging.
    pub fn SituationSaveModelAsGltf(model: SituationModel, file_path: *const c_char) -> SituationError;

    /// Serialize a graph to a JSON string (caller must free with SituationFreeJSONString).
    pub fn SituationSerializeGraphToJSON(graph: *mut SituationAudioGraph) -> *const c_char;

    /// Set the active audio processing graph (replaces default). NULL disables graph processing.
    pub fn SituationSetActiveGraph(graph: *mut SituationAudioGraph) -> SituationError;

    /// Set the active audio device.
    pub fn SituationSetAudioDevice(internal_id: c_int, format: *mut SituationAudioFormat) -> SituationError;

    /// Set the master volume for the audio device.
    pub fn SituationSetAudioMasterVolume(volume: f32) -> SituationError;

    /// Set a callback to receive mixed output samples (for VU meters, FFT, etc.).
    pub fn SituationSetAudioOutputMonitor(user_data: *mut c_void) -> ();

    /// Set stereo pan for a handle-based sound [-1.0 to 1.0].
    pub fn SituationSetAudioPan(handle: SituationSoundHandle, pan: f32) -> SituationError;

    /// Set pitch multiplier for a handle-based sound (1.0 = normal).
    pub fn SituationSetAudioPitch(handle: SituationSoundHandle, pitch: f32) -> SituationError;

    /// Re-initialize the audio device with a new sample rate.
    pub fn SituationSetAudioPlaybackSampleRate(sample_rate: c_int) -> SituationError;

    /// Set volume for a handle-based sound [0.0 to 1.0+].
    pub fn SituationSetAudioVolume(handle: SituationSoundHandle, volume: f32) -> SituationError;

    /// Set text in the system clipboard.
    pub fn SituationSetClipboardText(text: *const c_char) -> SituationError;

    /// Set a control parameter on a node.
    pub fn SituationSetControl(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, control_id: u32, value: f32) -> SituationError;

    /// OS-visible name for the calling thread (UTF-8); no-op if NULL/empty
    pub fn SituationSetCurrentThreadName(name: *const c_char) -> ();

    /// Set the mouse cursor to a standard shape.
    pub fn SituationSetCursor(cursor: SituationCursor) -> ();

    /// Set a callback for mouse movement events.
    pub fn SituationSetCursorPosCallback(callback: SituationCursorPosCallback, user_data: *mut c_void) -> ();

    /// Set the display mode for a monitor.
    pub fn SituationSetDisplayMode(monitor_id: c_int, mode: *mut SituationDisplayMode, fullscreen: bool) -> SituationError;

    /// Set a callback to run just before shutdown.
    pub fn SituationSetExitCallback(user_data: *mut c_void) -> ();

    /// Set a callback for file drop events.
    pub fn SituationSetFileDropCallback(callback: SituationFileDropCallback, user_data: *mut c_void) -> ();

    /// Set a callback for window focus events.
    pub fn SituationSetFocusCallback(callback: SituationFocusCallback, user_data: *mut c_void) -> ();

    /// Load a new set of gamepad mappings from a string.
    pub fn SituationSetGamepadMappings() -> c_int;

    /// Set gamepad vibration/rumble (Windows only).
    pub fn SituationSetGamepadVibration(jid: c_int, left_motor: f32, right_motor: f32) -> bool;

    /// Designate the Sound Source node in the active graph to receive routed SFX tones.
    pub fn SituationSetGraphSFXSource(handle: SituationNodeHandle) -> SituationError;

    /// Set a callback for joystick connection events.
    pub fn SituationSetJoystickCallback(callback: SituationJoystickCallback, user_data: *mut c_void) -> ();

    /// Set a callback for key events.
    pub fn SituationSetKeyCallback(callback: SituationKeyCallback, user_data: *mut c_void) -> ();

    /// Set a callback for window maximize / restore events.
    pub fn SituationSetMaximizeCallback(callback: SituationMaximizeCallback, user_data: *mut c_void) -> ();

    /// Set a callback for mouse button events.
    pub fn SituationSetMouseButtonCallback(callback: SituationMouseButtonCallback, user_data: *mut c_void) -> ();

    /// Set a software offset for the mouse position.
    pub fn SituationSetMouseOffset(offset: Vector2) -> ();

    /// Set the mouse position within the window.
    pub fn SituationSetMousePosition(pos: Vector2) -> ();

    /// Set a software scale for the mouse position and delta.
    pub fn SituationSetMouseScale(scale: Vector2) -> ();

    /// Filter MIDI to channel 0-15, or -1 omni.
    pub fn SituationSetNodeMidiChannel(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, channel: c_int) -> SituationError;

    /// Helper to set a specific pixel color (CPU-side).
    pub fn SituationSetPixelColor(x: c_int, y: c_int, col: ColorRGBA) -> ();

    /// Set a callback for window framebuffer resize events.
    pub fn SituationSetResizeCallback(user_data: *mut c_void) -> ();

    /// Set the default screenshot file format (default: BMP).
    pub fn SituationSetScreenshotFormat(format: SituationScreenshotFormat) -> ();

    /// Set a callback for mouse scroll events.
    pub fn SituationSetScrollCallback(callback: SituationScrollCallback, user_data: *mut c_void) -> ();

    /// [OpenGL] Set a standalone uniform by name (location cache). While a frame is active, defers to SIT_OP_SET_UNIFORM.
    pub fn SituationSetShaderUniform(shader: SituationShader, uniform_name: *const c_char, data: *mut c_void, r#type: SituationUniformType) -> SituationError;

    /// [OpenGL] Set float uniform array.
    pub fn SituationSetShaderUniform1fv(shader: SituationShader, uniform_name: *const c_char, count: c_int, values: *mut f32) -> SituationError;

    /// [OpenGL] Set int uniform array in one call (e.g. name "uWallRows[0]", count=24). While a frame is active, records SIT_OP_SET_UNIFORM (same as render-thread mode).
    pub fn SituationSetShaderUniform1iv(shader: SituationShader, uniform_name: *const c_char, count: c_int, values: *mut c_int) -> SituationError;

    /// [OpenGL] Set uniform by explicit location (SPIR-V layout(location=)); defers during frames like SituationSetShaderUniform.
    pub fn SituationSetShaderUniformLocation(shader: SituationShader, location: c_int, data: *mut c_void, r#type: SituationUniformType) -> SituationError;

    /// [OpenGL] Set mat4 uniform array.
    pub fn SituationSetShaderUniformMatrix4fv(shader: SituationShader, uniform_name: *const c_char, count: c_int, matrices: *mut Mat4) -> SituationError;

    /// Apply an echo effect to a sound.
    pub fn SituationSetSoundEcho(sound: *mut SituationSound, enabled: bool, delay_sec: f32, feedback: f32, wet_mix: f32) -> SituationError;

    /// Apply a low-pass or high-pass filter to a sound.
    pub fn SituationSetSoundFilter(sound: *mut SituationSound, r#type: SituationFilterType, cutoff_hz: f32, q_factor: f32) -> SituationError;

    /// Set the stereo pan for a sound [-1.0 to 1.0].
    pub fn SituationSetSoundPan(sound: *mut SituationSound, pan: f32) -> SituationError;

    /// Set the pitch for a sound (resamples).
    pub fn SituationSetSoundPitch(sound: *mut SituationSound, pitch: f32) -> SituationError;

    /// Apply a reverb effect to a sound.
    pub fn SituationSetSoundReverb(sound: *mut SituationSound, enabled: bool, room_size: f32, damping: f32, wet_mix: f32, dry_mix: f32) -> SituationError;

    /// Set the volume for a specific sound.
    pub fn SituationSetSoundVolume(sound: *mut SituationSound, volume: f32) -> SituationError;

    /// Set a desired frame rate cap (0 for uncapped).
    pub fn SituationSetTargetFPS(fps: c_int) -> ();

    /// [Phase 2] Update sampler state.
    pub fn SituationSetTextureSamplerParams(texture: SituationTexture, min_filter: SituationTextureFilter, mag_filter: SituationTextureFilter, wrap_s: SituationTextureWrap, wrap_t: SituationTextureWrap) -> SituationError;

    /// Pins the CURRENT thread (logical CPU bitmask, bits 0..63)
    pub fn SituationSetThreadAffinity(core_mask: u64) -> SituationError;

    /// Set affinity; optional previous mask
    pub fn SituationSetThreadAffinityEx(core_mask: u64, out_previous: *mut u64) -> SituationError;

    /// Set the period of an oscillator.
    pub fn SituationSetTimerOscillatorPeriod(oscillator_id: c_int, period_seconds: f64) -> SituationError;

    /// Route a procedural tone to the active graph's SFX sound source.
    pub fn SituationSetToneRouting(handle: SituationToneHandle, route_to_graph: bool) -> SituationError;

    /// Set the minimum log level for output filtering.
    pub fn SituationSetTraceLogLevel(logType: c_int) -> ();

    /// Enable or disable VSync (vertical synchronization).
    pub fn SituationSetVSync(enable: bool) -> ();

    /// Mark a virtual display as needing to be re-rendered.
    pub fn SituationSetVirtualDisplayDirty(display_id: c_int, is_dirty: bool) -> ();

    /// SOLID idle tint (normalized by compositor).
    pub fn SituationSetVirtualDisplayFallbackColor(display_id: c_int, color: ColorRGBA) -> ();

    /// SOLID or COLORBURST when idle.
    pub fn SituationSetVirtualDisplayFallbackMode(display_id: c_int, mode: SituationVDFallbackMode) -> ();

    /// Set idle threshold for compositor fallback (Phase 2a).
    pub fn SituationSetVirtualDisplayIdleThreshold(display_id: c_int, threshold_seconds: f64) -> ();

    /// Set the scaling/filtering mode for a virtual display.
    pub fn SituationSetVirtualDisplayScalingMode(display_id: c_int, scaling_mode: SituationScalingMode) -> SituationError;

    /// Set the window to be focused.
    pub fn SituationSetWindowFocused() -> ();

    /// Set the icon for the window (single image).
    pub fn SituationSetWindowIcon(image: SituationImage) -> ();

    /// Set the icon for the window (multiple sizes).
    pub fn SituationSetWindowIcons(count: c_int) -> ();

    /// Set the window maximum dimensions.
    pub fn SituationSetWindowMaxSize(width: c_int, height: c_int) -> ();

    /// Set the window minimum dimensions.
    pub fn SituationSetWindowMinSize(width: c_int, height: c_int) -> ();

    /// Set the window to be fullscreen on a specific monitor.
    pub fn SituationSetWindowMonitor(monitor_id: c_int) -> ();

    /// Set window opacity [0.0f to 1.0f].
    pub fn SituationSetWindowOpacity(opacity: f32) -> ();

    /// Set the window position on the screen.
    pub fn SituationSetWindowPosition(x: c_int, y: c_int) -> ();

    /// Set the window dimensions.
    pub fn SituationSetWindowSize(width: c_int, height: c_int) -> ();

    /// Set window configuration state using flags (additive).
    pub fn SituationSetWindowState(flags: u32) -> ();

    /// Set the flag profiles for when the window is focused vs. unfocused.
    pub fn SituationSetWindowStateProfiles(active_flags: u32, inactive_flags: u32) -> SituationError;

    /// Set the title for the window.
    pub fn SituationSetWindowTitle() -> ();

    /// Create connected virtual out→in pair. Returns input device_id for SituationEnableMidiControl().
    pub fn SituationSetupVirtualMidiLoopback(out_input_device_id: *mut c_int) -> SituationError;

    /// Show the mouse cursor.
    pub fn SituationShowCursor() -> ();

    /// Blocking UI message box; for fatal init errors.
    pub fn SituationShowMessageBox(title: *const c_char, message: *const c_char) -> ();

    /// Shut down the library and release all resources.
    pub fn SituationShutdown() -> ();

    /// Create a new sound by copying the raw PCM data from a source.
    pub fn SituationSoundCopy(source: *mut SituationSound, out_destination: *mut SituationSound) -> SituationError;

    /// Crop a sound's PCM data in-place to a new range.
    pub fn SituationSoundCrop(sound: *mut SituationSound, initFrame: u64, finalFrame: u64) -> SituationError;

    /// Export the sound's raw PCM data to a WAV file.
    pub fn SituationSoundExportAsWav(sound: *mut SituationSound, fileName: *const c_char) -> SituationError;

    /// Start capturing audio input with default format.
    pub fn SituationStartAudioCapture(callback: SituationAudioCaptureCallback, user_data: *mut c_void) -> SituationError;

    /// Start capturing with explicit sample rate and channel count.
    pub fn SituationStartAudioCaptureEx(callback: SituationAudioCaptureCallback, user_data: *mut c_void, sample_rate: u32, channels: u32) -> SituationError;

    /// Start learning: next CC received maps to this param. Scaling: 0=linear, 1=log, 2=dB, 3=discrete. Times out after 5s.
    pub fn SituationStartMidiLearn(graph: *mut SituationAudioGraph, handle: SituationNodeHandle, control_index: c_int, param_name: *const c_char, min_value: f32, max_value: f32, scaling: c_int) -> SituationError;

    /// Stop all currently playing sounds.
    pub fn SituationStopAllLoadedSounds() -> SituationError;

    /// Stop all active tones (triggers release on each).
    pub fn SituationStopAllTones() -> ();

    /// Stop audio capture and release the input device.
    pub fn SituationStopAudioCapture() -> ();

    /// Stop a specific sound from playing.
    pub fn SituationStopLoadedSound(sound: *mut SituationSound) -> SituationError;

    /// Gracefully stop a tone by triggering its release envelope. Invalid handles are ignored.
    pub fn SituationStopTone(handle: SituationToneHandle) -> ();

    /// Submits a job with priority flags and optional data payload.
    pub fn SituationSubmitJobEx(pool: *mut SituationThreadPool, data: *mut c_void, data_size: usize, flags: SituationJobFlags) -> SituationJobId;

    /// Submit a render list for async recording on a worker thread.
    pub fn SituationSubmitRenderList(pool: *mut SituationThreadPool, list: SituationRenderList, user_data: *mut c_void) -> SituationJobId;

    /// Take a screenshot. fileName is the base name (no extension) or NULL for auto-name. Extension added from format setting.
    pub fn SituationTakeScreenshot() -> SituationError;

    /// Close and destroy the virtual loopback devices.
    pub fn SituationTeardownVirtualMidiLoopback() -> ();

    /// Get the period of an oscillator in seconds.
    pub fn SituationTimerGetOscillatorPeriod(oscillator_id: c_int) -> f64;

    /// Get the current binary state (0 or 1) of an oscillator.
    pub fn SituationTimerGetOscillatorState(oscillator_id: c_int) -> bool;

    /// Get the total number of times an oscillator has triggered.
    pub fn SituationTimerGetOscillatorTriggerCount(oscillator_id: c_int) -> u64;

    /// Get progress [0.0 to 1.0+] of the interval since the last successful ping.
    pub fn SituationTimerGetPingProgress(oscillator_id: c_int) -> f64;

    /// Get the previous frame's state of an oscillator.
    pub fn SituationTimerGetPreviousOscillatorState(oscillator_id: c_int) -> bool;

    /// Get the total time elapsed since initialization.
    pub fn SituationTimerGetTime() -> f64;

    /// Check if an oscillator's state has changed this frame.
    pub fn SituationTimerHasOscillatorUpdated(oscillator_id: c_int) -> bool;

    /// Check if an oscillator's period has elapsed since the last ping.
    pub fn SituationTimerPingOscillator(oscillator_id: c_int) -> bool;

    /// Toggle window between borderless and decorated mode.
    pub fn SituationToggleBorderlessWindowed() -> ();

    /// Toggle window between fullscreen and windowed mode.
    pub fn SituationToggleFullscreen() -> ();

    /// Toggle flags in the current profile and apply the result.
    pub fn SituationToggleWindowStateFlags(flags_to_toggle: SituationWindowStateFlags) -> SituationError;

    /// Re-sort the graph processing order after topology changes. Call from the main thread after CreateNode/DestroyNode/CreatePatch/RemovePatch.
    pub fn SituationTopologicalSort(graph: *mut SituationAudioGraph) -> SituationError;

    /// Unload audio by handle and free resources.
    pub fn SituationUnloadAudio(handle: SituationSoundHandle) -> ();

    /// Unload the file path list returned by SituationLoadDroppedFiles.
    pub fn SituationUnloadDroppedFiles(paths: *const *const c_char, count: c_int) -> ();

    /// Unload a CPU-side font and free its memory.
    pub fn SituationUnloadFont(font: SituationFont) -> ();

    /// Unload an image's pixel data from memory.
    pub fn SituationUnloadImage(image: SituationImage) -> ();

    /// Frees all GPU and CPU resources associated with a loaded model.
    pub fn SituationUnloadModel(model: *mut SituationModel) -> ();

    /// Unload a graphics shader pipeline and free its GPU resources.
    pub fn SituationUnloadShader(shader: *mut SituationShader) -> ();

    /// Unload a sound and free its resources.
    pub fn SituationUnloadSound(sound: *mut SituationSound) -> ();

    /// DEPRECATED: Use SituationPollInputEvents() and SituationUpdateTimers().
    pub fn SituationUpdate() -> ();

    /// Update data in a GPU buffer.
    pub fn SituationUpdateBuffer(buffer: SituationBuffer, offset: usize, size: usize, data: *mut c_void) -> SituationError;

    /// Update all internal timers (frame timer, temporal system). Call after polling events.
    pub fn SituationUpdateTimers() -> ();

    /// Returns first missing/wrong-type uniform, or SUCCESS if all resolved.
    pub fn SituationValidateShaderUniforms(shader: SituationShader, table: *mut SituationUniformExpectation, table_count: c_int, error_buf: *const c_char, error_buf_size: usize) -> SituationError;

    /// CC (e.g. mod wheel, expression).
    pub fn SituationVirtualMidiControlChange(channel: u8, controller: u8, value: u8) -> SituationError;

    /// Inject note-off on channel 0 (legacy wrapper).
    pub fn SituationVirtualMidiNoteOff(note: u8) -> SituationError;

    /// Channel-aware note-off (0-15).
    pub fn SituationVirtualMidiNoteOffEx(channel: u8, note: u8) -> SituationError;

    /// Inject note-on on channel 0 (legacy wrapper).
    pub fn SituationVirtualMidiNoteOn(note: u8, velocity: u8) -> SituationError;

    /// Channel-aware note-on (0-15).
    pub fn SituationVirtualMidiNoteOnEx(channel: u8, note: u8, velocity: u8) -> SituationError;

    /// Pitch bend 0..16383 (center 8192).
    pub fn SituationVirtualMidiPitchBend(channel: u8, bend: i16) -> SituationError;

    /// Program change on channel 0-15.
    pub fn SituationVirtualMidiProgramChange(channel: u8, program: u8) -> SituationError;

    /// Blocks until all queued jobs are finished.
    pub fn SituationWaitForAllJobs(pool: *mut SituationThreadPool) -> ();

    /// Waits for a specific job to complete (O(1) check).
    pub fn SituationWaitForJob(pool: *mut SituationThreadPool, job_id: SituationJobId) -> SituationError;

    /// Check if the application should close (e.g., user clicked X).
    pub fn SituationWindowShouldClose() -> bool;

    /// Scale Q (chroma amplitude); preserve luma and phase.
    pub fn SituationYpqAdjustChroma(color: ColorYPQA, chroma_factor: f32) -> ColorYPQA;

    /// Scale Y (luma); preserve phase and chroma.
    pub fn SituationYpqAdjustLuma(color: ColorYPQA, luma_factor: f32) -> ColorYPQA;

    /// Rotate hue; P shifts by byte steps mod 256.
    pub fn SituationYpqAdjustPhase(color: ColorYPQA, phase_shift: c_int) -> ColorYPQA;

    pub fn SituationYpqAnalyzeRgbMapping(out: *mut SituationYpqRgbMappingStats) -> SituationError;
    /// Reduce chroma if linear RGB would clip.
    pub fn SituationYpqClampInGamut(ypq: ColorYPQf) -> ColorYPQf;

    /// Weighted distance in YPQ space.
    pub fn SituationYpqDistance(a: ColorYPQA, b: ColorYPQA) -> f32;

    /// Per-channel tolerance compare.
    pub fn SituationYpqEquals(a: ColorYPQA, b: ColorYPQA, tolerance: u8) -> bool;

    /// Normalized chroma amplitude [0, 1].
    pub fn SituationYpqGetChroma(color: ColorYPQA) -> f32;

    /// Hue in degrees [0, 360).
    pub fn SituationYpqGetHueDegrees(color: ColorYPQA) -> f32;

    /// Normalized luma [0, 1].
    pub fn SituationYpqGetLuma(color: ColorYPQA) -> f32;

    /// Interpolate YPQ; phase uses shortest arc on the hue wheel.
    pub fn SituationYpqLerp(a: ColorYPQA, b: ColorYPQA, t: f32) -> ColorYPQA;

    /// Float YPQ → 8-bit ColorYPQA.
    pub fn SituationYpqQuantize(ypq: ColorYPQf) -> ColorYPQA;

    pub fn SituationYpqSliceDuplicateCount(axis: c_char, value: c_int, out_dup: *mut c_int) -> SituationError;
}
