// Auto-generated by tools/generate_rust_bindings.py — Situation 2.4.218 (STL Model Loader, Demon Hunt Visual Bolster Fixes)
// Do not edit by hand.

use std::os::raw::{c_char, c_int, c_uint, c_void, c_long, c_ulong};

use crate::situation_types::*;

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.

pub type SituationFileDropCallback = Option<unsafe extern "C" fn(count: c_int, paths: *const *const c_char, user_data: *mut c_void) -> ()>;
/// Files/folders dragged from OS onto the window

pub type SituationFileLoadCallback = Option<unsafe extern "C" fn(data: *mut c_void, size: usize, user_data: *mut c_void) -> ()>;
/// Callback for asynchronous file loading

pub type SituationFileSaveCallback = Option<unsafe extern "C" fn(success: bool, user_data: *mut c_void) -> ()>;
/// Callback for asynchronous file saving

pub type SituationFileTextLoadCallback = Option<unsafe extern "C" fn(text: *const c_char, user_data: *mut c_void) -> ()>;
/// Callback for asynchronous text file loading

pub type SituationFocusCallback = Option<unsafe extern "C" fn(gained_focus: bool, user_data: *mut c_void) -> ()>;
/// Window focus change (alt-tab, click, etc.)

pub type SituationMaximizeCallback = Option<unsafe extern "C" fn(maximized: bool, user_data: *mut c_void) -> ()>;
/// Title-bar maximize / restore (requires SITUATION_FLAG_WINDOW_RESIZABLE at init)

pub type SituationWindowCloseCallback = Option<unsafe extern "C" fn(user_data: *mut c_void) -> ()>;
/// User clicked the OS close button. Rarely used — most code just polls SituationWindowShouldClose()

pub type SituationKeyCallback = Option<unsafe extern "C" fn(key: c_int, scancode: c_int, action: c_int, mods: c_int, user_data: *mut c_void) -> ()>;
/// Exact GLFW key callback signature

pub type SituationCharCallback = Option<unsafe extern "C" fn(codepoint: c_uint, user_data: *mut c_void) -> ()>;
/// Text input (separate from key events — handles IME, dead keys, etc.)

pub type SituationMouseButtonCallback = Option<unsafe extern "C" fn(button: c_int, action: c_int, mods: c_int, user_data: *mut c_void) -> ()>;
/// Mouse button events

pub type SituationCursorPosCallback = Option<unsafe extern "C" fn(position: Vector2, user_data: *mut c_void) -> ()>;
/// Called every time the mouse moves (can be very frequent)

pub type SituationScrollCallback = Option<unsafe extern "C" fn(offset: Vector2, user_data: *mut c_void) -> ()>;
/// Mouse wheel / trackpad scroll

pub type SituationJoystickCallback = Option<unsafe extern "C" fn(jid: c_int, event: c_int, user_data: *mut c_void) -> ()>;
/// Gamepad/controller hotplug events

pub type SituationStreamReadCallback = Option<unsafe extern "C" fn(pUserData: *mut c_void, pBufferOut: *mut c_void, bytesToRead: u64) -> u64>;
/// Return number of bytes actually written

pub type SituationStreamSeekCallback = Option<unsafe extern "C" fn(pUserData: *mut c_void, byteOffset: ma_int64, origin: ma_seek_origin) -> c_int>;
/// Return MA_SUCCESS on success

pub type SituationAudioCaptureCallback = Option<unsafe extern "C" fn(input_buffer: *mut f32, frame_count: u32, user_data: *mut c_void) -> ()>;
/// Called from audio thread unless SITUATION_INIT_AUDIO_CAPTURE_MAIN_THREAD is set

pub type SituationAudioProcessorCallback = Option<unsafe extern "C" fn(buffer: *mut f32, frames: u32, channels: u32, sampleRate: u32, user_data: *mut c_void) -> ()>;
/// Applied after built-in effects (filter → echo → reverb) but before final volume/pan

pub type GLFWerrorfunCallback = Option<unsafe extern "C" fn(error_code: c_int, description: *const c_char) -> ()>;
