// Auto-generated by tools/generate_rust_bindings.py — Situation 2.4.218 (STL Model Loader, Demon Hunt Visual Bolster Fixes)
// Do not edit by hand.

use std::os::raw::{c_char, c_int, c_uint, c_void, c_long, c_ulong};

// Core math & color (ABI must match sit/situation_api.h)
#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct ColorRGBA {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SitRectangle {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct Vector2 {
    pub x: f32,
    pub y: f32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct Vector3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct Vector4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}

// Generational GPU handles
#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationTexture {
    pub slot_index: u32,
    pub generation: u32,
    pub width: c_int,
    pub height: c_int,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationShader {
    pub slot_index: u32,
    pub generation: u32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationFont {
    pub texture: SituationTexture,
    pub font_size: f32,
    pub ascent: f32,
    pub descent: f32,
    pub line_gap: f32,
    pub glyph_count: c_int,
    pub is_bitmap: bool,
}

// Opaque handles (layout unknown — pass as pointer)
pub type SituationCommandBuffer = *mut c_void;

#[repr(C)]
pub struct SituationThreadPool {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationAudioGraph {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationNode {
    _private: [u8; 0],
}

// Scalar type aliases for C/miniaudio interop
pub type SituationJobId = u32;
pub type SituationNodeHandle = u32;
pub type ma_int64 = i64;
pub type ma_seek_origin = c_int;

// Additional opaque/resource handles
#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationSound {
    pub slot_index: u32,
    pub generation: u32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationBuffer {
    pub slot_index: u32,
    pub generation: u32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationComputePipeline {
    pub slot_index: u32,
    pub generation: u32,
}

// Structs referenced by the API but defined internally
#[repr(C)]
pub struct SituationCameraDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationRenderPassInfo {
    _private: [u8; 0],
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct SituationTextureBlitRegion {
    pub x: c_int,
    pub y: c_int,
    pub width: c_int,
    pub height: c_int,
}

// cglm mat4 equivalent
pub type Mat4 = [[f32; 4]; 4];

#[repr(C)]
pub struct SituationInitInfo {
    pub window_width: c_int,
    pub window_height: c_int,
    pub window_title: *const c_char,
    pub initial_active_window_flags: u32,
    pub initial_inactive_window_flags: u32,
    pub enable_vulkan_validation: bool,
    pub force_single_queue: bool,
    pub max_frames_in_flight: u32,
    pub required_vulkan_extensions: *const *const c_char,
    pub required_vulkan_extension_count: u32,
    pub flags: u32,
    pub max_audio_voices: u32,
    pub io_queue_capacity: u32,
    pub disable_io_thread: bool,
    pub hot_reload_poll_rate: f64,
    pub staging_buffer_size: u64,
    pub thread_affinity_main: u64,
    pub thread_affinity_render: u64,
    pub thread_affinity_audio: u64,
    pub numa_prefer_local: bool,
    pub worker_numa_spread: bool,
    pub io_thread_numa_node: i32,
    pub thread_pool_use_physical_cores: bool,
    pub thread_pool_reserved_threads: u32,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationError {
    SITUATION_SUCCESS = 0,
    SITUATION_ERROR_GENERAL = -1,
    SITUATION_ERROR_NOT_IMPLEMENTED = -2,
    SITUATION_ERROR_NOT_INITIALIZED = -3,
    SITUATION_ERROR_ALREADY_INITIALIZED = -4,
    SITUATION_ERROR_INIT_FAILED = -5,
    SITUATION_ERROR_SHUTDOWN_FAILED = -6,
    SITUATION_ERROR_INVALID_PARAM = -7,
    SITUATION_ERROR_MEMORY_ALLOCATION = -8,
    SITUATION_ERROR_INTERNAL_STATE_CORRUPTED = -9,
    SITUATION_ERROR_ASSERTION_FAILED = -10,
    SITUATION_ERROR_UPDATE_AFTER_DRAW_VIOLATION = -11,
    SITUATION_ERROR_MEMORY_ACCESS = -12,
    SITUATION_ERROR_TIMER_SYSTEM = -20,
    SITUATION_ERROR_THREAD_QUEUE_FULL = -80,
    SITUATION_ERROR_THREAD_VIOLATION = -81,
    SITUATION_ERROR_THREAD_CYCLE = -82,
    SITUATION_ERROR_THREAD_CREATION_FAILED = -83,
    SITUATION_ERROR_THREAD_MUTEX_INIT_FAILED = -84,
    SITUATION_ERROR_THREAD_MUTEX_LOCK_FAILED = -85,
    SITUATION_ERROR_THREAD_MUTEX_UNLOCK_FAILED = -86,
    SITUATION_ERROR_THREAD_MUTEX_TIMEOUT = -87,
    SITUATION_ERROR_THREAD_JOIN_FAILED = -88,
    SITUATION_ERROR_THREAD_DETACH_FAILED = -89,
    SITUATION_ERROR_THREAD_NOT_AVAILABLE = -90,
    SITUATION_ERROR_THREAD_ATOMIC_FAILED = -91,
    SITUATION_ERROR_THREAD_STATE_INVALID = -92,
    SITUATION_ERROR_THREAD_BUFFER_OVERFLOW = -93,
    SITUATION_ERROR_THREAD_DEADLOCK_DETECTED = -94,
    SITUATION_ERROR_RENDER_BACKPRESSURE_TIMEOUT = -95,
    SITUATION_ERROR_RENDER_LIST_INCOMPLETE = -96,
    SITUATION_ERROR_ARM_INTRINSICS_FAILED = -97,
    SITUATION_ERROR_COMMAND_EXECUTION_FAILED = -98,
    SITUATION_ERROR_GLFW_FAILED = -100,
    SITUATION_ERROR_WINDOW_CREATION_FAILED = -101,
    SITUATION_ERROR_WINDOW_FOCUS_FAILED = -102,
    SITUATION_ERROR_CLIPBOARD_FAILED = -103,
    SITUATION_ERROR_CURSOR_CREATION_FAILED = -104,
    SITUATION_ERROR_WINDOW_STATE_FAILED = -105,
    SITUATION_ERROR_WINDOW_PROPERTY_FAILED = -106,
    SITUATION_ERROR_APP_STATE_FAILED = -107,
    SITUATION_ERROR_COM_INITIALIZATION_FAILED = -110,
    SITUATION_ERROR_DXGI_QUERY_FAILED = -111,
    SITUATION_ERROR_WINDOW_FOCUS = -120,
    SITUATION_ERROR_DEVICE_QUERY = -121,
    SITUATION_ERROR_COM_FAILED = -123,
    SITUATION_ERROR_DXGI_FAILED = -124,
    SITUATION_ERROR_INPUT_DEVICE_DISCONNECTED = -130,
    SITUATION_ERROR_INPUT_MAPPING_INVALID = -131,
    SITUATION_ERROR_INPUT_HAPTIC_FAILED = -132,
    SITUATION_ERROR_DISPLAY_QUERY = -200,
    SITUATION_ERROR_DISPLAY_SET = -201,
    SITUATION_ERROR_VIRTUAL_DISPLAY_LIMIT = -202,
    SITUATION_ERROR_VIRTUAL_DISPLAY_INVALID_ID = -203,
    SITUATION_ERROR_DISPLAY_QUERY_FAILED = -210,
    SITUATION_ERROR_DISPLAY_MODE_UNSUPPORTED = -211,
    SITUATION_ERROR_DISPLAY_MODE_SET_FAILED = -212,
    SITUATION_ERROR_VIRTUAL_DISPLAY_LIMIT_REACHED = -213,
    SITUATION_ERROR_VIRTUAL_DISPLAY_NOT_FOUND = -214,
    SITUATION_ERROR_FILE_ACCESS = -300,
    SITUATION_ERROR_PATH_NOT_FOUND = -301,
    SITUATION_ERROR_PATH_INVALID = -302,
    SITUATION_ERROR_PERMISSION_DENIED = -303,
    SITUATION_ERROR_DISK_FULL = -304,
    SITUATION_ERROR_FILE_LOCKED = -305,
    SITUATION_ERROR_DIR_NOT_EMPTY = -306,
    SITUATION_ERROR_FILE_ALREADY_EXISTS = -307,
    SITUATION_ERROR_PATH_IS_DIRECTORY = -308,
    SITUATION_ERROR_PATH_IS_FILE = -309,
    SITUATION_ERROR_FILE_NOT_FOUND = -310,
    SITUATION_ERROR_FILE_ACCESS_DENIED = -311,
    SITUATION_ERROR_FILE_OPEN_FAILED = -312,
    SITUATION_ERROR_FILE_READ_FAILED = -313,
    SITUATION_ERROR_FILE_WRITE_FAILED = -314,
    SITUATION_ERROR_FILE_TOO_LARGE = -315,
    SITUATION_ERROR_DIRECTORY_CREATION_FAILED = -316,
    SITUATION_ERROR_FILE_MODIFIED = -317,
    SITUATION_ERROR_HOTRELOAD_WATCHER_FAILED = -320,
    SITUATION_ERROR_HOTRELOAD_FILE_CHANGED_TOO_FAST = -321,
    SITUATION_ERROR_HOTRELOAD_GPU_SYNC_FAILED = -322,
    SITUATION_ERROR_ASSET_PARSE_FAILED = -330,
    SITUATION_ERROR_ASSET_CORRUPTED = -331,
    SITUATION_ERROR_ASSET_VERSION_MISMATCH = -332,
    SITUATION_ERROR_ASSET_DECOMPRESSION_FAILED = -333,
    SITUATION_ERROR_PLUGIN_LOAD_FAILED = -360,
    SITUATION_ERROR_PLUGIN_SYMBOL_NOT_FOUND = -361,
    SITUATION_ERROR_PLUGIN_ABI_MISMATCH = -362,
    SITUATION_ERROR_AUDIO_CONTEXT = -400,
    SITUATION_ERROR_AUDIO_DEVICE = -401,
    SITUATION_ERROR_AUDIO_SOUND_LIMIT = -402,
    SITUATION_ERROR_AUDIO_CONVERTER = -403,
    SITUATION_ERROR_AUDIO_DECODING = -404,
    SITUATION_ERROR_AUDIO_INVALID_OPERATION = -405,
    SITUATION_ERROR_AUDIO_BACKEND_INIT_FAILED = -410,
    SITUATION_ERROR_AUDIO_DEVICE_INIT_FAILED = -411,
    SITUATION_ERROR_AUDIO_DEVICE_START_FAILED = -412,
    SITUATION_ERROR_AUDIO_DECODER_INIT_FAILED = -413,
    SITUATION_ERROR_AUDIO_DECODER_FORMAT_UNSUPPORTED = -414,
    SITUATION_ERROR_AUDIO_STREAM_ENDED = -415,
    SITUATION_ERROR_AUDIO_SOUND_LIMIT_REACHED = -420,
    SITUATION_ERROR_AUDIO_CAPTURE_NOT_AVAILABLE = -430,
    SITUATION_ERROR_MIXER_NOT_INITIALIZED = -440,
    SITUATION_ERROR_MIXER_TRACK_LIMIT = -441,
    SITUATION_ERROR_MIXER_TRACK_INVALID = -442,
    SITUATION_ERROR_MIXER_BUS_LIMIT = -443,
    SITUATION_ERROR_MIXER_BUS_INVALID = -444,
    SITUATION_ERROR_MIXER_INSERT_INVALID = -445,
    SITUATION_ERROR_MIXER_INSERT_ALREADY_ATTACHED = -446,
    SITUATION_ERROR_MIXER_INSERT_NOT_ATTACHED = -447,
    SITUATION_ERROR_MIXER_ROUTING_CYCLE = -448,
    SITUATION_ERROR_MIXER_ROUTING_INVALID = -449,
    SITUATION_ERROR_MIXER_SEND_INVALID = -450,
    SITUATION_ERROR_MIXER_TOPOLOGY_LOCKED = -451,
    SITUATION_ERROR_MIXER_SCENE_LOAD_FAILED = -452,
    SITUATION_ERROR_MIXER_SCENE_SAVE_FAILED = -453,
    SITUATION_ERROR_MIXER_SCENE_VERSION_MISMATCH = -454,
    SITUATION_ERROR_NODE_GRAPH_NOT_INITIALIZED = -460,
    SITUATION_ERROR_NODE_LIMIT_REACHED = -461,
    SITUATION_ERROR_NODE_INVALID_HANDLE = -462,
    SITUATION_ERROR_NODE_TYPE_INVALID = -463,
    SITUATION_ERROR_NODE_ALREADY_EXISTS = -464,
    SITUATION_ERROR_NODE_NOT_FOUND = -465,
    SITUATION_ERROR_NODE_PORT_INVALID = -466,
    SITUATION_ERROR_NODE_PORT_TYPE_MISMATCH = -467,
    SITUATION_ERROR_NODE_CHANNEL_MISMATCH = -468,
    SITUATION_ERROR_NODE_PATCH_ALREADY_EXISTS = -469,
    SITUATION_ERROR_NODE_PATCH_NOT_FOUND = -470,
    SITUATION_ERROR_NODE_PATCH_CYCLE_DETECTED = -471,
    SITUATION_ERROR_NODE_CONTROL_INVALID = -472,
    SITUATION_ERROR_NODE_CONTROL_OUT_OF_RANGE = -473,
    SITUATION_ERROR_NODE_CONTROL_TYPE_MISMATCH = -474,
    SITUATION_ERROR_NODE_PROCESSING_FAILED = -475,
    SITUATION_ERROR_NODE_SERIALIZATION_FAILED = -476,
    SITUATION_ERROR_NODE_DESERIALIZATION_FAILED = -477,
    SITUATION_ERROR_NODE_TOPOLOGY_INVALID = -478,
    SITUATION_ERROR_NODE_ALLOCATION_FAILED = -479,
    SITUATION_ERROR_DEVICE_REGISTRY_NOT_INITIALIZED = -480,
    SITUATION_ERROR_DEVICE_TYPE_INVALID = -481,
    SITUATION_ERROR_DEVICE_TYPE_NOT_REGISTERED = -482,
    SITUATION_ERROR_DEVICE_TYPE_ALREADY_REGISTERED = -483,
    SITUATION_ERROR_DEVICE_REGISTRY_FULL = -484,
    SITUATION_ERROR_DEVICE_METADATA_INVALID = -485,
    SITUATION_ERROR_DEVICE_CONTROL_INVALID = -486,
    SITUATION_ERROR_DEVICE_PORT_INVALID = -487,
    SITUATION_ERROR_DEVICE_CATEGORY_INVALID = -488,
    SITUATION_ERROR_DEVICE_QUERY_FAILED = -489,
    SITUATION_ERROR_DEVICE_FUNCTION_TABLE_INVALID = -490,
    SITUATION_ERROR_DEVICE_CREATE_FAILED = -491,
    SITUATION_ERROR_DEVICE_DESTROY_FAILED = -492,
    SITUATION_ERROR_DEVICE_PROCESS_FAILED = -493,
    SITUATION_ERROR_MIDI_INIT_FAILED = -494,
    SITUATION_ERROR_MIDI_NO_DEVICES = -495,
    SITUATION_ERROR_MIDI_DEVICE_OPEN_FAILED = -496,
    SITUATION_ERROR_MIDI_NOT_SUPPORTED = -497,
    SITUATION_ERROR_MIDI_LEARN_NOT_ENABLED = -498,
    SITUATION_ERROR_MIDI_LEARN_ALREADY_ENABLED = -499,
    SITUATION_ERROR_RESOURCE_INVALID = -500,
    SITUATION_ERROR_BUFFER_INVALID_SIZE = -501,
    SITUATION_ERROR_RENDER_COMMAND_FAILED = -502,
    SITUATION_ERROR_RENDER_PASS_ACTIVE = -503,
    SITUATION_ERROR_INVALID_RESOURCE_HANDLE = -510,
    SITUATION_ERROR_RESOURCE_ALREADY_DESTROYED = -511,
    SITUATION_ERROR_BUFFER_MAP_FAILED = -512,
    SITUATION_ERROR_BUFFER_OVERFLOW = -513,
    SITUATION_ERROR_BUFFER_INVALID_USAGE = -514,
    SITUATION_ERROR_TEXTURE_UPLOAD_FAILED = -520,
    SITUATION_ERROR_TEXTURE_INVALID_USAGE = -521,
    SITUATION_ERROR_TEXTURE_REGION_INVALID = -522,
    SITUATION_ERROR_TEXTURE_FORMAT_UNSUPPORTED = -523,
    SITUATION_ERROR_NO_ACTIVE_COMMAND_BUFFER = -530,
    SITUATION_ERROR_COMMAND_BUFFER_FULL = -531,
    SITUATION_ERROR_NO_RENDER_PASS_ACTIVE = -540,
    SITUATION_ERROR_RENDER_PASS_ALREADY_ACTIVE = -541,
    SITUATION_ERROR_BACKEND_MISMATCH = -550,
    SITUATION_ERROR_BACKEND_SPECIFIC = -551,
    SITUATION_ERROR_PIPELINE_BIND_FAIL = -552,
    SITUATION_ERROR_SHADER_LOAD_IN_PROGRESS = -553,
    SITUATION_ERROR_SPIRV_FILE_READ_FAILED = -554,
    SITUATION_ERROR_SPIRV_INVALID_BINARY = -555,
    SITUATION_ERROR_INDIRECT_COMMAND_INVALID = -556,
    SITUATION_ERROR_FONT_LOAD_FAILED = -560,
    SITUATION_ERROR_FONT_GLYPH_MISSING = -561,
    SITUATION_ERROR_FONT_ATLAS_FULL = -562,
    SITUATION_ERROR_IMAGE_OPERATION_FAILED = -580,
    SITUATION_ERROR_OPENGL_GENERAL = -600,
    SITUATION_ERROR_OPENGL_LOADER_FAILED = -601,
    SITUATION_ERROR_OPENGL_UNSUPPORTED = -602,
    SITUATION_ERROR_OPENGL_SHADER_COMPILE = -610,
    SITUATION_ERROR_OPENGL_SHADER_LINK = -611,
    SITUATION_ERROR_OPENGL_FBO_INCOMPLETE = -620,
    SITUATION_ERROR_OPENGL_CONTEXT_CREATION_FAILED = -630,
    SITUATION_ERROR_OPENGL_UNSUPPORTED_VERSION = -631,
    SITUATION_ERROR_OPENGL_SHADER_COMPILE_FAILED = -632,
    SITUATION_ERROR_OPENGL_SHADER_LINK_FAILED = -633,
    SITUATION_ERROR_OPENGL_PROGRAM_VALIDATION_FAILED = -634,
    SITUATION_ERROR_OPENGL_UNIFORM_NOT_FOUND = -635,
    SITUATION_ERROR_OPENGL_SPIRV_UNAVAILABLE = -636,
    SITUATION_ERROR_OPENGL_SPIRV_INVALID_BINARY = -637,
    SITUATION_ERROR_OPENGL_SPIRV_VS_SPECIALIZE_FAILED = -638,
    SITUATION_ERROR_OPENGL_SPIRV_FS_SPECIALIZE_FAILED = -639,
    SITUATION_ERROR_OPENGL_SPIRV_CS_SPECIALIZE_FAILED = -640,
    SITUATION_ERROR_OPENGL_SPIRV_PROGRAM_LINK_FAILED = -641,
    SITUATION_ERROR_VULKAN_INIT_FAILED = -700,
    SITUATION_ERROR_VULKAN_INSTANCE_FAILED = -701,
    SITUATION_ERROR_VULKAN_DEVICE_FAILED = -702,
    SITUATION_ERROR_VULKAN_UNSUPPORTED = -703,
    SITUATION_ERROR_VULKAN_SWAPCHAIN_FAILED = -710,
    SITUATION_ERROR_VULKAN_COMMAND_FAILED = -720,
    SITUATION_ERROR_VULKAN_COMMAND_BUFFER_FAILED = -721,
    SITUATION_ERROR_VULKAN_RENDERPASS_FAILED = -730,
    SITUATION_ERROR_VULKAN_FRAMEBUFFER_FAILED = -731,
    SITUATION_ERROR_VULKAN_PIPELINE_FAILED = -732,
    SITUATION_ERROR_VULKAN_SYNC_OBJECT_FAILED = -733,
    SITUATION_ERROR_VULKAN_MEMORY_ALLOC_FAILED = -734,
    SITUATION_ERROR_VULKAN_DESCRIPTOR_FAILED = -735,
    SITUATION_ERROR_VULKAN_INSTANCE_CREATION_FAILED = -740,
    SITUATION_ERROR_VULKAN_PHYSICAL_DEVICE_UNSUITABLE = -741,
    SITUATION_ERROR_VULKAN_DEVICE_CREATION_FAILED = -742,
    SITUATION_ERROR_VULKAN_SWAPCHAIN_CREATION_FAILED = -743,
    SITUATION_ERROR_VULKAN_SWAPCHAIN_INVALID = -744,
    SITUATION_ERROR_VULKAN_IMAGE_ACQUIRE_FAILED = -745,
    SITUATION_ERROR_VULKAN_QUEUE_SUBMIT_FAILED = -746,
    SITUATION_ERROR_VULKAN_PIPELINE_CREATION_FAILED = -747,
    SITUATION_ERROR_VULKAN_SHADER_MODULE_FAILED = -748,
    SITUATION_ERROR_VULKAN_DESCRIPTOR_POOL_EXHAUSTED = -749,
    SITUATION_ERROR_VULKAN_MEMORY_ALLOCATION_FAILED = -750,
    SITUATION_ERROR_VULKAN_VALIDATION_LAYER_ERROR = -751,
    SITUATION_ERROR_SHADER_COMPILATION_FAILED = -752,
    SITUATION_ERROR_VULKAN_SPIRV_INVALID = -753,
    SITUATION_ERROR_VULKAN_SPIRV_VS_MODULE_FAILED = -754,
    SITUATION_ERROR_VULKAN_SPIRV_FS_MODULE_FAILED = -755,
    SITUATION_ERROR_VULKAN_SPIRV_CS_MODULE_FAILED = -756,
    SITUATION_ERROR_COMPUTE_PIPELINE_CREATION_FAILED = -800,
    SITUATION_ERROR_COMPUTE_DISPATCH_FAILED = -801,
    SITUATION_ERROR_COMPUTE_BUFFER_BINDING_MISSING = -802,
    SITUATION_ERROR_NETWORK_INIT_FAILED = -900,
    SITUATION_ERROR_NETWORK_SOCKET_CREATION_FAILED = -901,
    SITUATION_ERROR_NETWORK_CONNECTION_FAILED = -902,
    SITUATION_ERROR_NETWORK_SEND_FAILED = -903,
    SITUATION_ERROR_NETWORK_RECEIVE_FAILED = -904,
    SITUATION_ERROR_NETWORK_BIND_FAILED = -905,
    SITUATION_ERROR_NETWORK_LISTEN_FAILED = -906,
    SITUATION_ERROR_NETWORK_ACCEPT_FAILED = -907,
    SITUATION_ERROR_NETWORK_TIMEOUT = -908,
    SITUATION_ERROR_NETWORK_DNS_RESOLUTION_FAILED = -909,
    SITUATION_ERROR_NETWORK_TLS_HANDSHAKE_FAILED = -910,
    SITUATION_ERROR_UNKNOWN_ERROR = -999,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationInitState {
    SITUATION_STATE_UNINITIALIZED = 0,
    SITUATION_STATE_INITIALIZING = 1,
    SITUATION_STATE_READY = 2,
    SITUATION_STATE_SHUTTING_DOWN = 3,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationLogLevel {
    SIT_LOG_ALL = 0,
    SIT_LOG_TRACE,
    SIT_LOG_DEBUG,
    SIT_LOG_INFO,
    SIT_LOG_WARNING,
    SIT_LOG_ERROR,
    SIT_LOG_FATAL,
    SIT_LOG_NONE,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationJobFlags {
    SIT_SUBMIT_DEFAULT = 0,
    SIT_SUBMIT_HIGH_PRIORITY = 1 << 0,
    SIT_SUBMIT_BLOCK_IF_FULL = 1 << 1,
    SIT_SUBMIT_RUN_IF_FULL = 1 << 2,
    SIT_SUBMIT_POINTER_ONLY = 1 << 3,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationThreadCapability {
    SITUATION_THREAD_CAP_NONE = 0,
    SITUATION_THREAD_CAP_C11_THREADS = (1 << 0),
    SITUATION_THREAD_CAP_C11_ATOMICS = (1 << 1),
    SITUATION_THREAD_CAP_MUTEX = (1 << 2),
    SITUATION_THREAD_CAP_SLEEP = (1 << 3),
    SITUATION_THREAD_CAP_PLATFORM_SLEEP = (1 << 4),
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationThreadRole {
    SIT_THREAD_ROLE_UNKNOWN = 0,
    SIT_THREAD_ROLE_MAIN,
    SIT_THREAD_ROLE_WORKER,
    SIT_THREAD_ROLE_IO,
    SIT_THREAD_ROLE_RENDER,
    SIT_THREAD_ROLE_AUDIO,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationJobQueueMask {
    SIT_JOB_QUEUE_LOW = (1 << 0),
    SIT_JOB_QUEUE_HIGH = (1 << 1),
    SIT_JOB_QUEUE_BOTH = ((1 << 0) | (1 << 1)),
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBufferUsageFlags {
    SITUATION_BUFFER_USAGE_VERTEX_BUFFER = 1 << 0,
    SITUATION_BUFFER_USAGE_INDEX_BUFFER = 1 << 1,
    SITUATION_BUFFER_USAGE_UNIFORM_BUFFER = 1 << 2,
    SITUATION_BUFFER_USAGE_STORAGE_BUFFER = 1 << 3,
    SITUATION_BUFFER_USAGE_INDIRECT_BUFFER = 1 << 4,
    SITUATION_BUFFER_USAGE_TRANSFER_SRC = 1 << 5,
    SITUATION_BUFFER_USAGE_TRANSFER_DST = 1 << 6,
    SITUATION_BUFFER_USAGE_DEVICE_ADDRESS = 1 << 7,
    SITUATION_BUFFER_USAGE_VERTEX_AND_STORAGE = 1 << 0 | 1 << 3,
    SITUATION_BUFFER_USAGE_DYNAMIC_VERTEX = 1 << 0 | 1 << 6,
    SITUATION_BUFFER_USAGE_DYNAMIC_UNIFORM = 1 << 2 | 1 << 6,
    SITUATION_BUFFER_USAGE_STORAGE_COMPUTE = 1 << 3 | 1 << 5 | 1 << 6 | 1 << 7,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationColorEncoding {
    SITUATION_COLOR_LINEAR = 0,
    SITUATION_COLOR_SRGB = 1,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationImageFlipMode {
    SIT_FLIP_VERTICAL,
    SIT_FLIP_HORIZONTAL,
    SIT_FLIP_BOTH,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationScreenshotFormat {
    SIT_SCREENSHOT_BMP = 0,
    SIT_SCREENSHOT_PNG,
    SIT_SCREENSHOT_JPG,
    SIT_SCREENSHOT_TGA,
    SIT_SCREENSHOT_FORMAT_COUNT,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationRendererType {
    SIT_RENDERER_OPENGL,
    SIT_RENDERER_VULKAN,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationComputeLayoutType {
    SIT_COMPUTE_LAYOUT_ONE_SSBO,
    SIT_COMPUTE_LAYOUT_TWO_SSBOS,
    SIT_COMPUTE_LAYOUT_IMAGE_AND_SSBO,
    SIT_COMPUTE_LAYOUT_PUSH_CONSTANT,
    SIT_COMPUTE_LAYOUT_EMPTY,
    SIT_COMPUTE_LAYOUT_BUFFER_IMAGE,
    SIT_COMPUTE_LAYOUT_TERMINAL,
    SIT_COMPUTE_LAYOUT_VECTOR,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationSpirvLayoutProfile {
    SIT_SPIRV_LAYOUT_PROFILE_MESH = 0,
    SIT_SPIRV_LAYOUT_PROFILE_DUAL_SSBO,
    SIT_SPIRV_LAYOUT_PROFILE_UBO_SSBO,
    SIT_SPIRV_LAYOUT_PROFILE_UBO_SSBO_SAMPLER,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationTextureUsageFlags {
    SITUATION_TEXTURE_USAGE_SAMPLED = 1 << 0,
    SITUATION_TEXTURE_USAGE_STORAGE = 1 << 1,
    SITUATION_TEXTURE_USAGE_TRANSFER_SRC = 1 << 2,
    SITUATION_TEXTURE_USAGE_TRANSFER_DST = 1 << 3,
    SITUATION_TEXTURE_USAGE_COMPUTE_SAMPLED = 1 << 4,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationTextureFormat {
    SIT_TEXTURE_FORMAT_UNKNOWN = 0,
    SIT_TEXTURE_FORMAT_RGBA8_UNORM,
    SIT_TEXTURE_FORMAT_RGBA8_SRGB,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationTextureFilter {
    SIT_TEXTURE_FILTER_NEAREST = 0,
    SIT_TEXTURE_FILTER_LINEAR,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationTextureWrap {
    SIT_TEXTURE_WRAP_CLAMP_TO_EDGE = 0,
    SIT_TEXTURE_WRAP_REPEAT,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBlitFilter {
    SITUATION_BLIT_FILTER_NEAREST = 0,
    SITUATION_BLIT_FILTER_LINEAR = 1,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationCursor {
    SIT_CURSOR_DEFAULT = 0,
    SIT_CURSOR_ARROW,
    SIT_CURSOR_IBEAM,
    SIT_CURSOR_CROSSHAIR,
    SIT_CURSOR_HAND,
    SIT_CURSOR_HRESIZE,
    SIT_CURSOR_VRESIZE,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBlendMode {
    SITUATION_BLEND_ALPHA,
    SITUATION_BLEND_ADDITIVE,
    SITUATION_BLEND_MULTIPLY,
    SITUATION_BLEND_SCREEN,
    SITUATION_BLEND_NONE,
    SITUATION_BLEND_OVERLAY,
    SITUATION_BLEND_SOFT_LIGHT,
    SITUATION_BLEND_HARD_LIGHT,
    SITUATION_BLEND_COLOR_DODGE,
    SITUATION_BLEND_COLOR_BURN,
    SITUATION_BLEND_DARKEN,
    SITUATION_BLEND_LIGHTEN,
    SITUATION_BLEND_DIFFERENCE,
    SITUATION_BLEND_EXCLUSION,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationScalingMode {
    SITUATION_SCALING_STRETCH,
    SITUATION_SCALING_FIT,
    SITUATION_SCALING_INTEGER,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationVDFlags {
    SITUATION_VD_FLAG_NONE = 0,
    SITUATION_VD_FLAG_COMPUTE_TARGET = 1 << 0,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationAttachmentLoadOp {
    SIT_LOAD_OP_LOAD,
    SIT_LOAD_OP_CLEAR,
    SIT_LOAD_OP_DONT_CARE,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationAttachmentStoreOp {
    SIT_STORE_OP_STORE,
    SIT_STORE_OP_DONT_CARE,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationClearFlags {
    SIT_CLEAR_COLOR_BIT = 0x1,
    SIT_CLEAR_DEPTH_BIT = 0x2,
    SIT_CLEAR_STENCIL_BIT = 0x4,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationWindowStateFlags {
    SITUATION_WINDOW_STATE_ON_TOP = 0x00000001,
    SITUATION_WINDOW_STATE_HIDDEN = 0x00000002,
    SITUATION_WINDOW_STATE_FROZEN = 0x00000004,
    SITUATION_WINDOW_STATE_FULLSCREEN = 0x00000008,
    SITUATION_WINDOW_STATE_UNDECORATED = 0x00000010,
    SITUATION_WINDOW_STATE_ALWAYS_RUN = 0x00000020,
    SITUATION_WINDOW_STATE_MINIMIZED = 0x00000040,
    SITUATION_WINDOW_STATE_MAXIMIZED = 0x00000080,
    SITUATION_WINDOW_STATE_RESIZABLE = 0x00000200,
    SITUATION_WINDOW_STATE_BORDERLESS = 0x00000400,
    SITUATION_WINDOW_STATE_MSAA_4X_HINT = 0x00000800,
    SITUATION_WINDOW_STATE_VSYNC_HINT = 0x00001000,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationUniformType {
    SIT_UNIFORM_FLOAT,
    SIT_UNIFORM_VEC2,
    SIT_UNIFORM_VEC3,
    SIT_UNIFORM_VEC4,
    SIT_UNIFORM_INT,
    SIT_UNIFORM_IVEC2,
    SIT_UNIFORM_IVEC3,
    SIT_UNIFORM_IVEC4,
    SIT_UNIFORM_MAT4,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationAudioDeviceType {
    SIT_AUDIO_DEVICE_TYPE_UNKNOWN = 0,
    SIT_AUDIO_DEVICE_TYPE_PLAYBACK = 1,
    SIT_AUDIO_DEVICE_TYPE_CAPTURE = 2,
    SIT_AUDIO_DEVICE_TYPE_DUPLEX = 3,
    SIT_AUDIO_DEVICE_TYPE_LOOPBACK = 4,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationDeviceCategory {
    SITUATION_DEVICE_EFFECT = 0,
    SITUATION_DEVICE_SOURCE,
    SITUATION_DEVICE_CAPTURE,
    SITUATION_DEVICE_UTILITY,
    SITUATION_DEVICE_MODULATOR,
    SITUATION_DEVICE_ANALYZER,
    SITUATION_DEVICE_CUSTOM,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationControlType {
    SITUATION_CONTROL_FLOAT = 0,
    SITUATION_CONTROL_INT,
    SITUATION_CONTROL_BOOL,
    SITUATION_CONTROL_ENUM,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationNodeType {
    SITUATION_NODE_REVERB = 0,
    SITUATION_NODE_ECHO,
    SITUATION_NODE_CHORUS,
    SITUATION_NODE_PHASER,
    SITUATION_NODE_OVERDRIVE,
    SITUATION_NODE_EXCITER,
    SITUATION_NODE_MAXIMIZER,
    SITUATION_NODE_SPRING_REVERB,
    SITUATION_NODE_STUDIO_REVERB,
    SITUATION_NODE_SST282,
    SITUATION_NODE_DYNAMICS,
    SITUATION_NODE_COMPANDER,
    SITUATION_NODE_EQ_4BAND,
    SITUATION_NODE_FILTER,
    SITUATION_NODE_MASTERING_AMP,
    SITUATION_NODE_DEAFMAX,
    SITUATION_NODE_PANNER,
    SITUATION_NODE_GAIN,
    SITUATION_NODE_MIXER,
    SITUATION_NODE_SOUND_SOURCE,
    SITUATION_NODE_TONE_SYNTH,
    SITUATION_NODE_PCM_INPUT,
    SITUATION_NODE_MIC_CAPTURE,
    SITUATION_NODE_LFO,
    SITUATION_NODE_ENVELOPE_FOLLOWER,
    SITUATION_NODE_SPECTRUM_ANALYZER,
    SITUATION_NODE_PEAK_METER,
    SITUATION_NODE_CUSTOM = 1000,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationAudioLoadMode {
    SITUATION_AUDIO_LOAD_AUTO,
    SITUATION_AUDIO_LOAD_FULL,
    SITUATION_AUDIO_LOAD_STREAM,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationWaveType {
    SIT_WAVE_SINE,
    SIT_WAVE_SQUARE,
    SIT_WAVE_TRIANGLE,
    SIT_WAVE_SAW,
    SIT_WAVE_NOISE,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationFilterType {
    SITUATION_FILTER_NONE,
    SITUATION_FILTER_LOWPASS,
    SITUATION_FILTER_HIGHPASS,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationRenderBackpressurePolicy {
    SIT_RENDER_BACKPRESSURE_SPIN = 0,
    SIT_RENDER_BACKPRESSURE_YIELD = 1,
    SIT_RENDER_BACKPRESSURE_SLEEP = 2,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationRenderFeature {
    SIT_FEATURE_GEOMETRY_SHADER = 1 << 0,
    SIT_FEATURE_TESSELLATION_SHADER = 1 << 1,
    SIT_FEATURE_WIDE_LINES = 1 << 2,
    SIT_FEATURE_FILL_MODE_NON_SOLID = 1 << 3,
    SIT_FEATURE_SAMPLER_ANISOTROPY = 1 << 4,
    SIT_FEATURE_MULTI_VIEWPORT = 1 << 5,
    SIT_FEATURE_COMPUTE_SHADER = 1 << 6,
    SIT_FEATURE_INT64 = 1 << 7,
    SIT_FEATURE_FLOAT64 = 1 << 8,
    SIT_FEATURE_FLOAT16 = 1 << 9,
    SIT_FEATURE_SUBGROUP_OPERATIONS = 1 << 10,
    SIT_FEATURE_BINDLESS_BUFFERS = 1 << 11,
    SIT_FEATURE_BINDLESS_TEXTURES = 1 << 12,
    SIT_FEATURE_DRAW_INDIRECT_COUNT = 1 << 13,
    SIT_FEATURE_MULTI_DRAW_INDIRECT = 1 << 14,
    SIT_FEATURE_MESH_SHADER = 1 << 15,
    SIT_FEATURE_RAY_TRACING = 1 << 16,
    SIT_FEATURE_VARIABLE_RATE_SHADING = 1 << 17,
    SIT_FEATURE_ATOMIC_FLOAT = 1 << 18,
    SIT_FEATURE_TEXTURE_COMPRESSION_BC = 1 << 19,
    SIT_FEATURE_TEXTURE_COMPRESSION_ASTC = 1 << 20,
    SIT_FEATURE_HDR_OUTPUT = 1 << 21,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationDataType {
    SIT_DATA_BYTE = 0,
    SIT_DATA_UNSIGNED_BYTE = 1,
    SIT_DATA_SHORT = 2,
    SIT_DATA_UNSIGNED_SHORT = 3,
    SIT_DATA_INT = 4,
    SIT_DATA_UNSIGNED_INT = 5,
    SIT_DATA_FLOAT = 6,
    SIT_DATA_DOUBLE = 7,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationGLShaderSourceType {
    SITUATION_GL_SHADER_SOURCE_TYPE_GLSL = 0,
    SITUATION_GL_SHADER_SOURCE_TYPE_SPIRV = 1,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBarrierSrcFlags {
    SITUATION_BARRIER_VERTEX_SHADER_WRITE = 1 << 0,
    SITUATION_BARRIER_FRAGMENT_SHADER_WRITE = 1 << 1,
    SITUATION_BARRIER_COMPUTE_SHADER_WRITE = 1 << 2,
    SITUATION_BARRIER_TRANSFER_WRITE = 1 << 3,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBarrierDstFlags {
    SITUATION_BARRIER_VERTEX_SHADER_READ = 1 << 0,
    SITUATION_BARRIER_FRAGMENT_SHADER_READ = 1 << 1,
    SITUATION_BARRIER_COMPUTE_SHADER_READ = 1 << 2,
    SITUATION_BARRIER_TRANSFER_READ = 1 << 3,
    SITUATION_BARRIER_INDIRECT_COMMAND_READ = 1 << 4,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationPipelineStageFlags {
    SITUATION_PIPELINE_STAGE_TOP = 1 << 0,
    SITUATION_PIPELINE_STAGE_INDIRECT_COMMAND = 1 << 1,
    SITUATION_PIPELINE_STAGE_VERTEX_INPUT = 1 << 2,
    SITUATION_PIPELINE_STAGE_VERTEX_SHADER = 1 << 3,
    SITUATION_PIPELINE_STAGE_FRAGMENT_SHADER = 1 << 4,
    SITUATION_PIPELINE_STAGE_COLOR_ATTACHMENT = 1 << 5,
    SITUATION_PIPELINE_STAGE_DEPTH_STENCIL = 1 << 6,
    SITUATION_PIPELINE_STAGE_COMPUTE_SHADER = 1 << 7,
    SITUATION_PIPELINE_STAGE_TRANSFER = 1 << 8,
    SITUATION_PIPELINE_STAGE_HOST = 1 << 9,
    SITUATION_PIPELINE_STAGE_BOTTOM = 1 << 10,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationAccessFlags {
    SITUATION_ACCESS_INDIRECT_COMMAND_READ = 1 << 0,
    SITUATION_ACCESS_VERTEX_READ = 1 << 1,
    SITUATION_ACCESS_INDEX_READ = 1 << 2,
    SITUATION_ACCESS_UNIFORM_READ = 1 << 3,
    SITUATION_ACCESS_SHADER_READ = 1 << 4,
    SITUATION_ACCESS_SHADER_WRITE = 1 << 5,
    SITUATION_ACCESS_COLOR_ATTACHMENT_READ = 1 << 6,
    SITUATION_ACCESS_COLOR_ATTACHMENT_WRITE = 1 << 7,
    SITUATION_ACCESS_DEPTH_STENCIL_READ = 1 << 8,
    SITUATION_ACCESS_DEPTH_STENCIL_WRITE = 1 << 9,
    SITUATION_ACCESS_TRANSFER_READ = 1 << 10,
    SITUATION_ACCESS_TRANSFER_WRITE = 1 << 11,
    SITUATION_ACCESS_HOST_READ = 1 << 12,
    SITUATION_ACCESS_HOST_WRITE = 1 << 13,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationTextureLayout {
    SITUATION_TEXTURE_LAYOUT_UNDEFINED = 0,
    SITUATION_TEXTURE_LAYOUT_GENERAL,
    SITUATION_TEXTURE_LAYOUT_SHADER_READ,
    SITUATION_TEXTURE_LAYOUT_TRANSFER_SRC,
    SITUATION_TEXTURE_LAYOUT_TRANSFER_DST,
    SITUATION_TEXTURE_LAYOUT_COLOR_ATTACHMENT,
    SITUATION_TEXTURE_LAYOUT_DEPTH_STENCIL_ATTACHMENT,
    SITUATION_TEXTURE_LAYOUT_PRESENT,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationGraphicsBackend {
    SIT_GRAPHICS_BACKEND_UNKNOWN = 0,
    SIT_GRAPHICS_BACKEND_OPENGL = 1,
    SIT_GRAPHICS_BACKEND_VULKAN = 2,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationCullMode {
    SIT_CULL_NONE = 0,
    SIT_CULL_BACK,
    SIT_CULL_FRONT,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationFrontFace {
    SIT_FRONT_FACE_CCW = 0,
    SIT_FRONT_FACE_CW,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationPrimitiveTopology {
    SIT_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 0,
    SIT_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
    SIT_PRIMITIVE_TOPOLOGY_LINE_LIST,
    SIT_PRIMITIVE_TOPOLOGY_LINE_STRIP,
    SIT_PRIMITIVE_TOPOLOGY_POINT_LIST,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationPolygonMode {
    SIT_POLYGON_MODE_FILL = 0,
    SIT_POLYGON_MODE_LINE,
    SIT_POLYGON_MODE_POINT,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationIndexType {
    SIT_INDEX_UINT32 = 0,
    SIT_INDEX_UINT16,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationDepthCompareOp {
    SIT_DEPTH_COMPARE_ALWAYS = 0,
    SIT_DEPTH_COMPARE_LESS,
    SIT_DEPTH_COMPARE_LEQUAL,
    SIT_DEPTH_COMPARE_GREATER,
    SIT_DEPTH_COMPARE_GEQUAL,
    SIT_DEPTH_COMPARE_EQUAL,
    SIT_DEPTH_COMPARE_NOTEQUAL,
    SIT_DEPTH_COMPARE_NEVER,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationStencilOp {
    SIT_STENCIL_OP_KEEP = 0,
    SIT_STENCIL_OP_ZERO,
    SIT_STENCIL_OP_REPLACE,
    SIT_STENCIL_OP_INCREMENT_CLAMP,
    SIT_STENCIL_OP_DECREMENT_CLAMP,
    SIT_STENCIL_OP_INVERT,
    SIT_STENCIL_OP_INCREMENT_WRAP,
    SIT_STENCIL_OP_DECREMENT_WRAP,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationBlendFactor {
    SIT_BLEND_ZERO = 0,
    SIT_BLEND_ONE,
    SIT_BLEND_SRC_COLOR,
    SIT_BLEND_ONE_MINUS_SRC_COLOR,
    SIT_BLEND_DST_COLOR,
    SIT_BLEND_ONE_MINUS_DST_COLOR,
    SIT_BLEND_SRC_ALPHA,
    SIT_BLEND_ONE_MINUS_SRC_ALPHA,
    SIT_BLEND_DST_ALPHA,
    SIT_BLEND_ONE_MINUS_DST_ALPHA,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SituationCameraFlags {
    SIT_CAMERA_FLAG_NONE = 0,
    SIT_CAMERA_FLAG_ORTHOGRAPHIC = 1 << 0,
    SIT_CAMERA_FLAG_REVERSE_Z = 1 << 1,
    SIT_CAMERA_FLAG_INFINITE_PROJECTION = 1 << 2,
}

// --- Auto-generated opaque type stubs ---
// These types are referenced by the API but their layout is internal.

#[repr(C)]
pub struct ColorHSV {
    _private: [u8; 0],
}

#[repr(C)]
pub struct ColorYPQA {
    _private: [u8; 0],
}

#[repr(C)]
pub struct ColorYPQf {
    _private: [u8; 0],
}

#[repr(C)]
pub struct FILE {
    _private: [u8; 0],
}

#[repr(C)]
pub struct GLFWwindow {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationAudioDeviceInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationAudioFormat {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationBufferBarrierDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationCPUInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationClearValue {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationCpuTopology {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationDeviceFunctions {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationDeviceInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationDeviceMetadata {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationDisplayInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationDisplayMode {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationGPUInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationGraphicsCaps {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationImage {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationMemoryInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationMesh {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationMidiDeviceInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationModel {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationMultisampleState {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationNumaTopology {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationOSInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationPipelineBarrierDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationProcessInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationReadPixelsDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationRenderList {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationSoundHandle {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationStencilState {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationTextureBarrierDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationTextureCopyRegion {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationTextureInfo {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationTextureReadbackDesc {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationThreadPoolMetrics {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationThreadPoolSnapshot {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationThreadingStatus {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationToneHandle {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationUniformExpectation {
    _private: [u8; 0],
}

#[repr(C)]
pub struct SituationVirtualDisplay {
    _private: [u8; 0],
}

#[repr(C)]
pub struct VkDevice {
    _private: [u8; 0],
}

#[repr(C)]
pub struct VkInstance {
    _private: [u8; 0],
}

#[repr(C)]
pub struct VkPhysicalDevice {
    _private: [u8; 0],
}

#[repr(C)]
pub struct VkRenderPass {
    _private: [u8; 0],
}
