// Auto-generated by tools/generate_rust_bindings.py — Situation 2.4.218 (STL Model Loader, Demon Hunt Visual Bolster Fixes)
// Do not edit by hand.

use std::os::raw::{c_char, c_int, c_uint, c_void, c_long, c_ulong};

use crate::situation_ffi::*;
use crate::situation_types::SituationError;

// Helpers replacing C preprocessor macros from situation_api.h

pub fn situation_begin_frame() {
    unsafe {
        SituationPollInputEvents();
        SituationUpdateTimers();
    }
}

pub fn situation_success(err: SituationError) -> bool {
    err == SituationError::SITUATION_SUCCESS
}
