// Auto-generated by tools/generate_rust_bindings.py — Situation 2.4.265 (YPQ Phase 3: public mapping diagnostics API, test_misc cleanup)
// Do not edit by hand.

use std::os::raw::{c_char, c_int, c_uint, c_void};

use crate::situation_types::*;

// Callback typedefs from sit/situation_api.h and sit/situation_base_callbacks.h

pub type SituationFileDropCallback = Option<unsafe extern "C" fn(count: c_int, paths: *const *const c_char, user_data: *mut c_void) -> ()>;

pub type SituationFileLoadCallback = Option<unsafe extern "C" fn(data: *mut c_void, size: usize, user_data: *mut c_void) -> ()>;

pub type SituationFileSaveCallback = Option<unsafe extern "C" fn(success: bool, user_data: *mut c_void) -> ()>;

pub type SituationFileTextLoadCallback = Option<unsafe extern "C" fn(text: *const c_char, user_data: *mut c_void) -> ()>;

pub type SituationFocusCallback = Option<unsafe extern "C" fn(gained_focus: bool, user_data: *mut c_void) -> ()>;

pub type SituationMaximizeCallback = Option<unsafe extern "C" fn(maximized: bool, user_data: *mut c_void) -> ()>;

pub type SituationWindowCloseCallback = Option<unsafe extern "C" fn(user_data: *mut c_void) -> ()>;

pub type SituationKeyCallback = Option<unsafe extern "C" fn(key: c_int, scancode: c_int, action: c_int, mods: SituationModifiers, user_data: *mut c_void) -> ()>;

pub type SituationCharCallback = Option<unsafe extern "C" fn(codepoint: c_uint, user_data: *mut c_void) -> ()>;

pub type SituationMouseButtonCallback = Option<unsafe extern "C" fn(button: c_int, action: c_int, mods: SituationModifiers, user_data: *mut c_void) -> ()>;

pub type SituationCursorPosCallback = Option<unsafe extern "C" fn(position: Vector2, user_data: *mut c_void) -> ()>;

pub type SituationScrollCallback = Option<unsafe extern "C" fn(offset: Vector2, user_data: *mut c_void) -> ()>;

pub type SituationJoystickCallback = Option<unsafe extern "C" fn(jid: c_int, event: c_int, user_data: *mut c_void) -> ()>;

pub type SituationStreamReadCallback = Option<unsafe extern "C" fn(pUserData: *mut c_void, pBufferOut: *mut c_void, bytesToRead: SituationStreamSize) -> SituationStreamSize>;

pub type SituationStreamSeekCallback = Option<unsafe extern "C" fn(pUserData: *mut c_void, byteOffset: i64, origin: SituationSeekOrigin) -> SituationStreamResult>;

pub type SituationAudioCaptureCallback = Option<unsafe extern "C" fn(input_buffer: *mut f32, frame_count: u32, user_data: *mut c_void) -> ()>;

pub type SituationAudioProcessorCallback = Option<unsafe extern "C" fn(buffer: *mut f32, frames: u32, channels: u32, sampleRate: u32, user_data: *mut c_void) -> ()>;

pub type GLFWerrorfunCallback = Option<unsafe extern "C" fn(error_code: c_int, description: *const c_char) -> ()>;
