// Auto-generated by tools/generate_zig_bindings.py — Situation 2.4.218 (STL Model Loader, Demon Hunt Visual Bolster Fixes)
// Do not edit by hand.

const types = @import("situation_types.zig");

const Vector2 = types.Vector2;
const ma_int64 = types.ma_int64;
const ma_seek_origin = types.ma_seek_origin;

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.

pub const SituationFileDropCallback = *const fn (count: c_int, paths: ?[*][*:0]const u8, user_data: ?*anyopaque) callconv(.C) void;
/// Files/folders dragged from OS onto the window

pub const SituationFileLoadCallback = *const fn (data: ?*anyopaque, size: usize, user_data: ?*anyopaque) callconv(.C) void;
/// Callback for asynchronous file loading

pub const SituationFileSaveCallback = *const fn (success: bool, user_data: ?*anyopaque) callconv(.C) void;
/// Callback for asynchronous file saving

pub const SituationFileTextLoadCallback = *const fn (text: [*:0]const u8, user_data: ?*anyopaque) callconv(.C) void;
/// Callback for asynchronous text file loading

pub const SituationFocusCallback = *const fn (gained_focus: bool, user_data: ?*anyopaque) callconv(.C) void;
/// Window focus change (alt-tab, click, etc.)

pub const SituationMaximizeCallback = *const fn (maximized: bool, user_data: ?*anyopaque) callconv(.C) void;
/// Title-bar maximize / restore (requires SITUATION_FLAG_WINDOW_RESIZABLE at init)

pub const SituationWindowCloseCallback = *const fn (user_data: ?*anyopaque) callconv(.C) void;
/// User clicked the OS close button. Rarely used — most code just polls SituationWindowShouldClose()

pub const SituationKeyCallback = *const fn (key: c_int, scancode: c_int, action: c_int, mods: c_int, user_data: ?*anyopaque) callconv(.C) void;
/// Exact GLFW key callback signature

pub const SituationCharCallback = *const fn (codepoint: c_uint, user_data: ?*anyopaque) callconv(.C) void;
/// Text input (separate from key events — handles IME, dead keys, etc.)

pub const SituationMouseButtonCallback = *const fn (button: c_int, action: c_int, mods: c_int, user_data: ?*anyopaque) callconv(.C) void;
/// Mouse button events

pub const SituationCursorPosCallback = *const fn (position: Vector2, user_data: ?*anyopaque) callconv(.C) void;
/// Called every time the mouse moves (can be very frequent)

pub const SituationScrollCallback = *const fn (offset: Vector2, user_data: ?*anyopaque) callconv(.C) void;
/// Mouse wheel / trackpad scroll

pub const SituationJoystickCallback = *const fn (jid: c_int, event: c_int, user_data: ?*anyopaque) callconv(.C) void;
/// Gamepad/controller hotplug events

pub const SituationStreamReadCallback = *const fn (pUserData: ?*anyopaque, pBufferOut: ?*anyopaque, bytesToRead: u64) callconv(.C) u64;
/// Return number of bytes actually written

pub const SituationStreamSeekCallback = *const fn (pUserData: ?*anyopaque, byteOffset: ma_int64, origin: ma_seek_origin) callconv(.C) c_int;
/// Return MA_SUCCESS on success

pub const SituationAudioCaptureCallback = *const fn (input_buffer: *f32, frame_count: u32, user_data: ?*anyopaque) callconv(.C) void;
/// Called from audio thread unless SITUATION_INIT_AUDIO_CAPTURE_MAIN_THREAD is set

pub const SituationAudioProcessorCallback = *const fn (buffer: *f32, frames: u32, channels: u32, sampleRate: u32, user_data: ?*anyopaque) callconv(.C) void;
/// Applied after built-in effects (filter → echo → reverb) but before final volume/pan

pub const GLFWerrorfunCallback = *const fn (error_code: c_int, description: [*:0]const u8) callconv(.C) void;
