// Auto-generated by tools/generate_zig_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.)
// Do not edit by hand.

const types = @import("situation_types.zig");

const ma_int64 = types.ma_int64;
const ma_seek_origin = types.ma_seek_origin;

// Callback typedefs from sit/situation_api.h — register with SituationSet* APIs.
