// Auto-generated by tools/generate_zig_bindings.py — Situation 2.4.218 (STL Model Loader, Demon Hunt Visual Bolster Fixes)
// Do not edit by hand.

const foreign = @import("situation_foreign.zig");
const types = @import("situation_types.zig");

// Helpers replacing C preprocessor macros from situation_api.h

pub fn situationBeginFrame() void {
    foreign.SituationPollInputEvents();
    foreign.SituationUpdateTimers();
}

pub fn situationSuccess(err: types.SituationError) bool {
    return err == .SITUATION_SUCCESS;
}
