-- Auto-generated by tools/generate_lua_bindings.py — Situation 2.4.366 (Vulkan shader cache Phase 6E/6C: async Layer A fast path, descriptor reload gate.)
-- Do not edit by hand.

local ffi = require('ffi')

local M = {}

M.SituationFileDropCallback = ffi.typeof("SituationFileDropCallback")

M.SituationFileLoadCallback = ffi.typeof("SituationFileLoadCallback")

M.SituationFileSaveCallback = ffi.typeof("SituationFileSaveCallback")

M.SituationFileTextLoadCallback = ffi.typeof("SituationFileTextLoadCallback")

M.SituationFocusCallback = ffi.typeof("SituationFocusCallback")

M.SituationMaximizeCallback = ffi.typeof("SituationMaximizeCallback")

M.SituationWindowCloseCallback = ffi.typeof("SituationWindowCloseCallback")

M.SituationKeyCallback = ffi.typeof("SituationKeyCallback")

M.SituationCharCallback = ffi.typeof("SituationCharCallback")

M.SituationMouseButtonCallback = ffi.typeof("SituationMouseButtonCallback")

M.SituationCursorPosCallback = ffi.typeof("SituationCursorPosCallback")

M.SituationScrollCallback = ffi.typeof("SituationScrollCallback")

M.SituationJoystickCallback = ffi.typeof("SituationJoystickCallback")

M.SituationStreamReadCallback = ffi.typeof("SituationStreamReadCallback")

M.SituationStreamSeekCallback = ffi.typeof("SituationStreamSeekCallback")

M.SituationAudioCaptureCallback = ffi.typeof("SituationAudioCaptureCallback")

M.SituationAudioProcessorCallback = ffi.typeof("SituationAudioProcessorCallback")

M.GLFWerrorfunCallback = ffi.typeof("GLFWerrorfunCallback")

return M
