-- Auto-generated by tools/generate_lua_bindings.py — Situation 2.4.366 (Vulkan shader cache Phase 6E/6C: async Layer A fast path, descriptor reload gate.)
-- Do not edit by hand.

local ffi = require('ffi')

local M = {}

M.SIT_OUTPUT_COLOR_AUTO = 0
M.SIT_OUTPUT_COLOR_8BIT = 1


function M.check(err)
    if err ~= 0 then
        error("SituationError(" .. tostring(err) .. ")", 2)
    end
end


function M.situation_success(err)
    return err == 0
end


function M.begin_frame(lib)
    lib.SituationPollInputEvents()
    lib.SituationUpdateTimers()
end


function M.window_should_close(lib)
    return lib.SituationWindowShouldClose() ~= 0
end


function M.key_pressed(lib, key)
    return lib.SituationIsKeyPressed(key) ~= 0
end


function M.init_info_window(width, height, title)
    local info = ffi.new("SituationInitInfo")
    ffi.fill(info, 0)
    -- 8-bit avoids stale-DLL glfwGetWindowAttrib(GLFW_*_BITS) spam during 10-bit probe.
    info.output_color_depth = M.SIT_OUTPUT_COLOR_8BIT
    info.window_width = width
    info.window_height = height
    info.window_title = title
    return info
end


return M
