-- Auto-generated by tools/generate_lua_bindings.py — Situation 2.4.366 (Vulkan shader cache Phase 6E/6C: async Layer A fast path, descriptor reload gate.)
-- Do not edit by hand.

local ffi = require('ffi')

local M = {}

M.types = {
    ColorRGBA = "ColorRGBA",
    SitRectangle = "SitRectangle",
    Vector2 = "Vector2",
    Vector3 = "Vector3",
    Vector4 = "Vector4",
    SituationTexture = "SituationTexture",
    SituationShader = "SituationShader",
    SituationMesh = "SituationMesh",
    SituationFont = "SituationFont",
    SituationPackedFont = "SituationPackedFont",
    SituationSound = "SituationSound",
    SituationBuffer = "SituationBuffer",
    SituationComputePipeline = "SituationComputePipeline",
    SituationTextureBlitRegion = "SituationTextureBlitRegion",
    SituationClearValue = "SituationClearValue",
    SituationImage = "SituationImage",
    SituationInitInfo = "SituationInitInfo",
}

function M.new_ColorRGBA(...)
    local obj = ffi.new("ColorRGBA")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SitRectangle(...)
    local obj = ffi.new("SitRectangle")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_Vector2(...)
    local obj = ffi.new("Vector2")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_Vector3(...)
    local obj = ffi.new("Vector3")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_Vector4(...)
    local obj = ffi.new("Vector4")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationTexture(...)
    local obj = ffi.new("SituationTexture")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationShader(...)
    local obj = ffi.new("SituationShader")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationMesh(...)
    local obj = ffi.new("SituationMesh")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationFont(...)
    local obj = ffi.new("SituationFont")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationPackedFont(...)
    local obj = ffi.new("SituationPackedFont")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationSound(...)
    local obj = ffi.new("SituationSound")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationBuffer(...)
    local obj = ffi.new("SituationBuffer")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationComputePipeline(...)
    local obj = ffi.new("SituationComputePipeline")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationTextureBlitRegion(...)
    local obj = ffi.new("SituationTextureBlitRegion")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationClearValue(...)
    local obj = ffi.new("SituationClearValue")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationImage(...)
    local obj = ffi.new("SituationImage")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_SituationInitInfo(...)
    local obj = ffi.new("SituationInitInfo")
    if select('#', ...) > 0 then
        local src = select(1, ...)
        if type(src) == 'table' then
            for k, v in pairs(src) do
                obj[k] = v
            end
        end
    end
    return obj
end

function M.new_mat4()
    return ffi.new("mat4")
end

return M
