! Auto-generated by tools/generate_fortran_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.)
! Do not edit by hand.

module situation_helpers
  use iso_c_binding
  use situation_types
  use situation_foreign, only: SituationPollInputEvents, SituationUpdateTimers
  implicit none

contains

  subroutine situation_begin_frame()
    call SituationPollInputEvents()
    call SituationUpdateTimers()
  end subroutine situation_begin_frame

  function sit_ok(err) result(ok)
    integer(c_int), intent(in), value :: err
    logical :: ok
    ok = (err == SITUATION_SUCCESS)
  end function sit_ok

end module situation_helpers
