! Auto-generated by tools/generate_fortran_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.)
! Do not edit by hand.

module situation_types
  use iso_c_binding
  implicit none

  ! Core math & color (ABI must match sit/situation_api.h)
  type, bind(C) :: ColorRGBA
    integer(c_int8_t) :: r, g, b, a
  end type ColorRGBA

  type, bind(C) :: SitRectangle
    real(c_float) :: x, y, width, height
  end type SitRectangle

  type, bind(C) :: Vector2
    real(c_float) :: x, y
  end type Vector2

  type, bind(C) :: Vector3
    real(c_float) :: x, y, z
  end type Vector3

  type, bind(C) :: Vector4
    real(c_float) :: x, y, z, w
  end type Vector4

  ! Generational GPU handles
  type, bind(C) :: SituationTexture
    integer(c_int32_t) :: slot_index, generation
    integer(c_int) :: width, height
  end type SituationTexture

  type, bind(C) :: SituationShader
    integer(c_int32_t) :: slot_index, generation
  end type SituationShader

  type, bind(C) :: SituationFont
    type(c_ptr) :: fontData, stbFontInfo, glyph_info
    type(SituationTexture) :: atlas_texture
    integer(c_int) :: atlas_width, atlas_height
    real(c_float) :: font_height_pixels
    logical(c_bool) :: is_bitmap
    type(c_ptr) :: bitmap_data
    integer(c_int) :: bitmap_width, bitmap_height, bitmap_count
    integer(c_int) :: first_char, chars_per_row, chars_per_col
    integer(c_int) :: display_cell_width, display_cell_height
    real(c_float) :: char_spacing, line_spacing
  end type SituationFont

  type, bind(C) :: SituationPackedFont
    integer(c_int) :: char_width, char_height, display_height
    integer(c_int) :: char_count, first_char, chars_per_row
    integer(c_int) :: bits_per_row, data_bits, data_bit_offset
    logical(c_bool) :: bit_order_msb_first
    integer(c_int) :: top_padding, bottom_padding, left_padding, right_padding
    integer(c_int) :: atlas_chars_per_row, atlas_chars_per_col
    logical(c_bool) :: enable_outline
    integer(c_int) :: outline_thickness
    integer(c_int8_t) :: outline_r, outline_g, outline_b, outline_a
    integer(c_int8_t) :: font_r, font_g, font_b, font_a
  end type SituationPackedFont

  ! Additional opaque/resource handles
  type, bind(C) :: SituationSound
    integer(c_int32_t) :: slot_index, generation
  end type SituationSound

  type, bind(C) :: SituationBuffer
    integer(c_int32_t) :: slot_index, generation
    integer(c_size_t) :: size_in_bytes
    integer(c_int32_t) :: usage_flags
  end type SituationBuffer

  type, bind(C) :: SituationMesh
    integer(c_int32_t) :: slot_index, generation
    integer(c_int) :: index_count, vertex_count
    integer(c_size_t) :: vertex_stride
  end type SituationMesh

  type, bind(C) :: ColorHSV
    real(c_float) :: h, s, v
  end type ColorHSV

  type, bind(C) :: ColorYPQA
    integer(c_int8_t) :: y, p, q, a
  end type ColorYPQA

  type, bind(C) :: ColorYPQf
    real(c_float) :: y, p, q, a
  end type ColorYPQf

  type, bind(C) :: ColorRGBA10
    integer(c_int16_t) :: r, g, b, a
  end type ColorRGBA10

  type, bind(C) :: SituationImage
    type(c_ptr) :: data
    integer(c_int) :: width, height, channels, color_encoding
  end type SituationImage

  type, bind(C) :: SituationModel
    integer(c_int32_t) :: slot_index, generation
    integer(c_int) :: mesh_count
    type(c_ptr) :: meshes
  end type SituationModel

  type, bind(C) :: SituationOSInfo
    character(kind=c_char) :: name(64)
    character(kind=c_char) :: version(64)
    integer(c_int32_t) :: build_number
  end type SituationOSInfo

  type, bind(C) :: SituationDeviceInfo
    character(kind=c_char) :: cpu_name(64)
    integer(c_int) :: cpu_cores
    real(c_float) :: cpu_clock_speed_ghz
    character(kind=c_char) :: gpu_name(64)
    integer(c_int64_t) :: gpu_dedicated_memory_bytes
    integer(c_int64_t) :: total_ram_bytes
    integer(c_int64_t) :: available_ram_bytes
    integer(c_int) :: storage_device_count
    character(kind=c_char) :: storage_device_names(8, 64)
    integer(c_int64_t) :: storage_capacity_bytes(8)
    integer(c_int64_t) :: storage_free_bytes(8)
    integer(c_int) :: network_adapter_count
    character(kind=c_char) :: network_adapter_names(8, 64)
    integer(c_int) :: input_device_count
    character(kind=c_char) :: input_device_names(8, 64)
    integer(c_int) :: display_count
    character(kind=c_char) :: display_names(8, 64)
    integer(c_int) :: display_widths(8)
    integer(c_int) :: display_heights(8)
    integer(c_int) :: display_refresh_rates(8)
  end type SituationDeviceInfo

  type, bind(C) :: SituationComputePipeline
    integer(c_int32_t) :: slot_index, generation
  end type SituationComputePipeline

  type, bind(C) :: SituationTextureBlitRegion
    integer(c_int) :: x, y, width, height
  end type SituationTextureBlitRegion

  ! cglm mat4 equivalent (linear 16 floats — row-major C layout)
  type, bind(C) :: Mat4
    real(c_float) :: m(16)
  end type Mat4

  type, bind(C) :: SituationInitInfo
    integer(c_int) :: window_width, window_height
    type(c_ptr) :: window_title
    integer(c_int32_t) :: initial_active_window_flags, initial_inactive_window_flags
    logical(c_bool) :: enable_vulkan_validation, force_single_queue
    integer(c_int32_t) :: max_frames_in_flight
    type(c_ptr) :: required_vulkan_extensions
    integer(c_int32_t) :: required_vulkan_extension_count, flags, max_audio_voices, io_queue_capacity
    logical(c_bool) :: disable_io_thread
    real(c_double) :: hot_reload_poll_rate
    integer(c_int64_t) :: staging_buffer_size
    integer(c_int64_t) :: thread_affinity_main, thread_affinity_render, thread_affinity_audio
    logical(c_bool) :: numa_prefer_local, worker_numa_spread
    integer(c_int32_t) :: io_thread_numa_node
    logical(c_bool) :: thread_pool_use_physical_cores
    integer(c_int32_t) :: thread_pool_reserved_threads
  end type SituationInitInfo

  ! Opaque handles — layout unknown; pass as type(c_ptr) at FFI boundaries.
  type :: SituationThreadPool
    private
    integer(c_int) :: opaque_stub
  end type SituationThreadPool

  type :: SituationAudioGraph
    private
    integer(c_int) :: opaque_stub
  end type SituationAudioGraph

  type :: SituationNode
    private
    integer(c_int) :: opaque_stub
  end type SituationNode

  type :: SituationCameraDesc
    private
    integer(c_int) :: opaque_stub
  end type SituationCameraDesc

  type :: SituationRenderPassInfo
    private
    integer(c_int) :: opaque_stub
  end type SituationRenderPassInfo

  ! --- SituationError ---
  integer(c_int), parameter :: SITUATION_SUCCESS = 0
  integer(c_int), parameter :: SITUATION_ERROR_GENERAL = -1
  integer(c_int), parameter :: SITUATION_ERROR_NOT_IMPLEMENTED = -2
  integer(c_int), parameter :: SITUATION_ERROR_NOT_INITIALIZED = -3
  integer(c_int), parameter :: SITUATION_ERROR_ALREADY_INITIALIZED = -4
  integer(c_int), parameter :: SITUATION_ERROR_INIT_FAILED = -5
  integer(c_int), parameter :: SITUATION_ERROR_SHUTDOWN_FAILED = -6
  integer(c_int), parameter :: SITUATION_ERROR_INVALID_PARAM = -7
  integer(c_int), parameter :: SITUATION_ERROR_MEMORY_ALLOCATION = -8
  integer(c_int), parameter :: SITUATION_ERROR_INTERNAL_STATE_CORRUPTED = -9
  integer(c_int), parameter :: SITUATION_ERROR_ASSERTION_FAILED = -10
  integer(c_int), parameter :: SITUATION_ERROR_UPDATE_AFTER_DRAW_VIOLATION = -11
  integer(c_int), parameter :: SITUATION_ERROR_MEMORY_ACCESS = -12
  integer(c_int), parameter :: SITUATION_ERROR_SHUTDOWN_INCOMPLETE = -13
  integer(c_int), parameter :: SITUATION_ERROR_INIT_STALE_DRIVER_STATE = -14
  integer(c_int), parameter :: SITUATION_ERROR_TIMER_SYSTEM = -20
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_QUEUE_FULL = -80
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_VIOLATION = -81
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_CYCLE = -82
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_CREATION_FAILED = -83
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_MUTEX_INIT_FAILED = -84
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_MUTEX_LOCK_FAILED = -85
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_MUTEX_UNLOCK_FAILED = -86
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_MUTEX_TIMEOUT = -87
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_JOIN_FAILED = -88
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_DETACH_FAILED = -89
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_NOT_AVAILABLE = -90
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_ATOMIC_FAILED = -91
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_STATE_INVALID = -92
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_BUFFER_OVERFLOW = -93
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_DEADLOCK_DETECTED = -94
  integer(c_int), parameter :: SITUATION_ERROR_RENDER_BACKPRESSURE_TIMEOUT = -95
  integer(c_int), parameter :: SITUATION_ERROR_RENDER_LIST_INCOMPLETE = -96
  integer(c_int), parameter :: SITUATION_ERROR_ARM_INTRINSICS_FAILED = -97
  integer(c_int), parameter :: SITUATION_ERROR_COMMAND_EXECUTION_FAILED = -98
  integer(c_int), parameter :: SITUATION_ERROR_THREAD_JOB_LOST = -99
  integer(c_int), parameter :: SITUATION_ERROR_GLFW_FAILED = -100
  integer(c_int), parameter :: SITUATION_ERROR_WINDOW_CREATION_FAILED = -101
  integer(c_int), parameter :: SITUATION_ERROR_WINDOW_FOCUS_FAILED = -102
  integer(c_int), parameter :: SITUATION_ERROR_CLIPBOARD_FAILED = -103
  integer(c_int), parameter :: SITUATION_ERROR_CURSOR_CREATION_FAILED = -104
  integer(c_int), parameter :: SITUATION_ERROR_WINDOW_STATE_FAILED = -105
  integer(c_int), parameter :: SITUATION_ERROR_WINDOW_PROPERTY_FAILED = -106
  integer(c_int), parameter :: SITUATION_ERROR_APP_STATE_FAILED = -107
  integer(c_int), parameter :: SITUATION_ERROR_FULLSCREEN_RELEASE_FAILED = -108
  integer(c_int), parameter :: SITUATION_ERROR_CONTEXT_RECLAIM_FAILED = -109
  integer(c_int), parameter :: SITUATION_ERROR_COM_INITIALIZATION_FAILED = -110
  integer(c_int), parameter :: SITUATION_ERROR_DXGI_QUERY_FAILED = -111
  integer(c_int), parameter :: SITUATION_ERROR_WINDOW_FOCUS = -120
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_QUERY = -121
  integer(c_int), parameter :: SITUATION_ERROR_COM_FAILED = -123
  integer(c_int), parameter :: SITUATION_ERROR_DXGI_FAILED = -124
  integer(c_int), parameter :: SITUATION_ERROR_INPUT_DEVICE_DISCONNECTED = -130
  integer(c_int), parameter :: SITUATION_ERROR_INPUT_MAPPING_INVALID = -131
  integer(c_int), parameter :: SITUATION_ERROR_INPUT_HAPTIC_FAILED = -132
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_QUERY = -200
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_SET = -201
  integer(c_int), parameter :: SITUATION_ERROR_VIRTUAL_DISPLAY_LIMIT = -202
  integer(c_int), parameter :: SITUATION_ERROR_VIRTUAL_DISPLAY_INVALID_ID = -203
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_QUERY_FAILED = -210
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_MODE_UNSUPPORTED = -211
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_MODE_SET_FAILED = -212
  integer(c_int), parameter :: SITUATION_ERROR_VIRTUAL_DISPLAY_LIMIT_REACHED = -213
  integer(c_int), parameter :: SITUATION_ERROR_VIRTUAL_DISPLAY_NOT_FOUND = -214
  integer(c_int), parameter :: SITUATION_ERROR_DISPLAY_MODE_SETTLING = -215
  integer(c_int), parameter :: SITUATION_ERROR_FILE_ACCESS = -300
  integer(c_int), parameter :: SITUATION_ERROR_PATH_NOT_FOUND = -301
  integer(c_int), parameter :: SITUATION_ERROR_PATH_INVALID = -302
  integer(c_int), parameter :: SITUATION_ERROR_PERMISSION_DENIED = -303
  integer(c_int), parameter :: SITUATION_ERROR_DISK_FULL = -304
  integer(c_int), parameter :: SITUATION_ERROR_FILE_LOCKED = -305
  integer(c_int), parameter :: SITUATION_ERROR_DIR_NOT_EMPTY = -306
  integer(c_int), parameter :: SITUATION_ERROR_FILE_ALREADY_EXISTS = -307
  integer(c_int), parameter :: SITUATION_ERROR_PATH_IS_DIRECTORY = -308
  integer(c_int), parameter :: SITUATION_ERROR_PATH_IS_FILE = -309
  integer(c_int), parameter :: SITUATION_ERROR_FILE_NOT_FOUND = -310
  integer(c_int), parameter :: SITUATION_ERROR_FILE_ACCESS_DENIED = -311
  integer(c_int), parameter :: SITUATION_ERROR_FILE_OPEN_FAILED = -312
  integer(c_int), parameter :: SITUATION_ERROR_FILE_READ_FAILED = -313
  integer(c_int), parameter :: SITUATION_ERROR_FILE_WRITE_FAILED = -314
  integer(c_int), parameter :: SITUATION_ERROR_FILE_TOO_LARGE = -315
  integer(c_int), parameter :: SITUATION_ERROR_DIRECTORY_CREATION_FAILED = -316
  integer(c_int), parameter :: SITUATION_ERROR_FILE_MODIFIED = -317
  integer(c_int), parameter :: SITUATION_ERROR_HOTRELOAD_WATCHER_FAILED = -320
  integer(c_int), parameter :: SITUATION_ERROR_HOTRELOAD_FILE_CHANGED_TOO_FAST = -321
  integer(c_int), parameter :: SITUATION_ERROR_HOTRELOAD_GPU_SYNC_FAILED = -322
  integer(c_int), parameter :: SITUATION_ERROR_ASSET_PARSE_FAILED = -330
  integer(c_int), parameter :: SITUATION_ERROR_ASSET_CORRUPTED = -331
  integer(c_int), parameter :: SITUATION_ERROR_ASSET_VERSION_MISMATCH = -332
  integer(c_int), parameter :: SITUATION_ERROR_ASSET_DECOMPRESSION_FAILED = -333
  integer(c_int), parameter :: SITUATION_ERROR_PLUGIN_LOAD_FAILED = -360
  integer(c_int), parameter :: SITUATION_ERROR_PLUGIN_SYMBOL_NOT_FOUND = -361
  integer(c_int), parameter :: SITUATION_ERROR_PLUGIN_ABI_MISMATCH = -362
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_CONTEXT = -400
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DEVICE = -401
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_SOUND_LIMIT = -402
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_CONVERTER = -403
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DECODING = -404
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_INVALID_OPERATION = -405
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_BACKEND_INIT_FAILED = -410
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DEVICE_INIT_FAILED = -411
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DEVICE_START_FAILED = -412
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DECODER_INIT_FAILED = -413
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DECODER_FORMAT_UNSUPPORTED = -414
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_STREAM_ENDED = -415
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_SOUND_LIMIT_REACHED = -420
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_CAPTURE_NOT_AVAILABLE = -430
  integer(c_int), parameter :: SITUATION_ERROR_AUDIO_DEVICE_TRANSITION_STALE = -431
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_NOT_INITIALIZED = -440
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_TRACK_LIMIT = -441
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_TRACK_INVALID = -442
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_BUS_LIMIT = -443
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_BUS_INVALID = -444
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_INSERT_INVALID = -445
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_INSERT_ALREADY_ATTACHED = -446
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_INSERT_NOT_ATTACHED = -447
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_ROUTING_CYCLE = -448
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_ROUTING_INVALID = -449
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_SEND_INVALID = -450
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_TOPOLOGY_LOCKED = -451
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_SCENE_LOAD_FAILED = -452
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_SCENE_SAVE_FAILED = -453
  integer(c_int), parameter :: SITUATION_ERROR_MIXER_SCENE_VERSION_MISMATCH = -454
  integer(c_int), parameter :: SITUATION_ERROR_NODE_GRAPH_NOT_INITIALIZED = -460
  integer(c_int), parameter :: SITUATION_ERROR_NODE_LIMIT_REACHED = -461
  integer(c_int), parameter :: SITUATION_ERROR_NODE_INVALID_HANDLE = -462
  integer(c_int), parameter :: SITUATION_ERROR_NODE_TYPE_INVALID = -463
  integer(c_int), parameter :: SITUATION_ERROR_NODE_ALREADY_EXISTS = -464
  integer(c_int), parameter :: SITUATION_ERROR_NODE_NOT_FOUND = -465
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PORT_INVALID = -466
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PORT_TYPE_MISMATCH = -467
  integer(c_int), parameter :: SITUATION_ERROR_NODE_CHANNEL_MISMATCH = -468
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PATCH_ALREADY_EXISTS = -469
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PATCH_NOT_FOUND = -470
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PATCH_CYCLE_DETECTED = -471
  integer(c_int), parameter :: SITUATION_ERROR_NODE_CONTROL_INVALID = -472
  integer(c_int), parameter :: SITUATION_ERROR_NODE_CONTROL_OUT_OF_RANGE = -473
  integer(c_int), parameter :: SITUATION_ERROR_NODE_CONTROL_TYPE_MISMATCH = -474
  integer(c_int), parameter :: SITUATION_ERROR_NODE_PROCESSING_FAILED = -475
  integer(c_int), parameter :: SITUATION_ERROR_NODE_SERIALIZATION_FAILED = -476
  integer(c_int), parameter :: SITUATION_ERROR_NODE_DESERIALIZATION_FAILED = -477
  integer(c_int), parameter :: SITUATION_ERROR_NODE_TOPOLOGY_INVALID = -478
  integer(c_int), parameter :: SITUATION_ERROR_NODE_ALLOCATION_FAILED = -479
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_REGISTRY_NOT_INITIALIZED = -480
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_TYPE_INVALID = -481
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_TYPE_NOT_REGISTERED = -482
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_TYPE_ALREADY_REGISTERED = -483
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_REGISTRY_FULL = -484
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_METADATA_INVALID = -485
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_CONTROL_INVALID = -486
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_PORT_INVALID = -487
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_CATEGORY_INVALID = -488
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_QUERY_FAILED = -489
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_FUNCTION_TABLE_INVALID = -490
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_CREATE_FAILED = -491
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_DESTROY_FAILED = -492
  integer(c_int), parameter :: SITUATION_ERROR_DEVICE_PROCESS_FAILED = -493
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_INIT_FAILED = -494
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_NO_DEVICES = -495
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_DEVICE_OPEN_FAILED = -496
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_NOT_SUPPORTED = -497
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_LEARN_NOT_ENABLED = -498
  integer(c_int), parameter :: SITUATION_ERROR_MIDI_LEARN_ALREADY_ENABLED = -499
  integer(c_int), parameter :: SITUATION_ERROR_RESOURCE_INVALID = -500
  integer(c_int), parameter :: SITUATION_ERROR_BUFFER_INVALID_SIZE = -501
  integer(c_int), parameter :: SITUATION_ERROR_RENDER_COMMAND_FAILED = -502
  integer(c_int), parameter :: SITUATION_ERROR_RENDER_PASS_ACTIVE = -503
  integer(c_int), parameter :: SITUATION_ERROR_INVALID_RESOURCE_HANDLE = -510
  integer(c_int), parameter :: SITUATION_ERROR_RESOURCE_ALREADY_DESTROYED = -511
  integer(c_int), parameter :: SITUATION_ERROR_BUFFER_MAP_FAILED = -512
  integer(c_int), parameter :: SITUATION_ERROR_BUFFER_OVERFLOW = -513
  integer(c_int), parameter :: SITUATION_ERROR_BUFFER_INVALID_USAGE = -514
  integer(c_int), parameter :: SITUATION_ERROR_MESH_DEVICE_ADDRESS_UNSUPPORTED = -515
  integer(c_int), parameter :: SITUATION_ERROR_TEXTURE_UPLOAD_FAILED = -520
  integer(c_int), parameter :: SITUATION_ERROR_TEXTURE_INVALID_USAGE = -521
  integer(c_int), parameter :: SITUATION_ERROR_TEXTURE_REGION_INVALID = -522
  integer(c_int), parameter :: SITUATION_ERROR_TEXTURE_FORMAT_UNSUPPORTED = -523
  integer(c_int), parameter :: SITUATION_ERROR_NO_ACTIVE_COMMAND_BUFFER = -530
  integer(c_int), parameter :: SITUATION_ERROR_COMMAND_BUFFER_FULL = -531
  integer(c_int), parameter :: SITUATION_ERROR_NO_RENDER_PASS_ACTIVE = -540
  integer(c_int), parameter :: SITUATION_ERROR_RENDER_PASS_ALREADY_ACTIVE = -541
  integer(c_int), parameter :: SITUATION_ERROR_BACKEND_MISMATCH = -550
  integer(c_int), parameter :: SITUATION_ERROR_BACKEND_SPECIFIC = -551
  integer(c_int), parameter :: SITUATION_ERROR_PIPELINE_BIND_FAIL = -552
  integer(c_int), parameter :: SITUATION_ERROR_SHADER_LOAD_IN_PROGRESS = -553
  integer(c_int), parameter :: SITUATION_ERROR_SPIRV_FILE_READ_FAILED = -554
  integer(c_int), parameter :: SITUATION_ERROR_SPIRV_INVALID_BINARY = -555
  integer(c_int), parameter :: SITUATION_ERROR_INDIRECT_COMMAND_INVALID = -556
  integer(c_int), parameter :: SITUATION_ERROR_SHADER_COMPILE_TIMEOUT = -557
  integer(c_int), parameter :: SITUATION_ERROR_FONT_LOAD_FAILED = -560
  integer(c_int), parameter :: SITUATION_ERROR_FONT_GLYPH_MISSING = -561
  integer(c_int), parameter :: SITUATION_ERROR_FONT_ATLAS_FULL = -562
  integer(c_int), parameter :: SITUATION_ERROR_IMAGE_OPERATION_FAILED = -580
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_GENERAL = -600
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_LOADER_FAILED = -601
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_UNSUPPORTED = -602
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SHADER_COMPILE = -610
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SHADER_LINK = -611
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_FBO_INCOMPLETE = -620
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_CONTEXT_CREATION_FAILED = -630
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_UNSUPPORTED_VERSION = -631
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SHADER_COMPILE_FAILED = -632
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SHADER_LINK_FAILED = -633
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_PROGRAM_VALIDATION_FAILED = -634
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_UNIFORM_NOT_FOUND = -635
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_UNAVAILABLE = -636
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_INVALID_BINARY = -637
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_VS_SPECIALIZE_FAILED = -638
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_FS_SPECIALIZE_FAILED = -639
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_CS_SPECIALIZE_FAILED = -640
  integer(c_int), parameter :: SITUATION_ERROR_OPENGL_SPIRV_PROGRAM_LINK_FAILED = -641
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_INIT_FAILED = -700
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_INSTANCE_FAILED = -701
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_DEVICE_FAILED = -702
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_UNSUPPORTED = -703
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SWAPCHAIN_FAILED = -710
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_COMMAND_FAILED = -720
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_COMMAND_BUFFER_FAILED = -721
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_RENDERPASS_FAILED = -730
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_FRAMEBUFFER_FAILED = -731
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_PIPELINE_FAILED = -732
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SYNC_OBJECT_FAILED = -733
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_MEMORY_ALLOC_FAILED = -734
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_DESCRIPTOR_FAILED = -735
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_INSTANCE_CREATION_FAILED = -740
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_PHYSICAL_DEVICE_UNSUITABLE = -741
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_DEVICE_CREATION_FAILED = -742
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SWAPCHAIN_CREATION_FAILED = -743
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SWAPCHAIN_INVALID = -744
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_IMAGE_ACQUIRE_FAILED = -745
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_QUEUE_SUBMIT_FAILED = -746
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_PIPELINE_CREATION_FAILED = -747
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SHADER_MODULE_FAILED = -748
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_DESCRIPTOR_POOL_EXHAUSTED = -749
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_MEMORY_ALLOCATION_FAILED = -750
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_VALIDATION_LAYER_ERROR = -751
  integer(c_int), parameter :: SITUATION_ERROR_SHADER_COMPILATION_FAILED = -752
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SPIRV_INVALID = -753
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SPIRV_VS_MODULE_FAILED = -754
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SPIRV_FS_MODULE_FAILED = -755
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_SPIRV_CS_MODULE_FAILED = -756
  integer(c_int), parameter :: SITUATION_ERROR_SHADER_COMPILER_REQUIRED = -757
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_PIPELINE_CACHE_INIT_FAILED = -758
  integer(c_int), parameter :: SITUATION_ERROR_VULKAN_RENDER_PASS_CACHE_FULL = -759
  integer(c_int), parameter :: SITUATION_ERROR_COMPUTE_PIPELINE_CREATION_FAILED = -800
  integer(c_int), parameter :: SITUATION_ERROR_COMPUTE_DISPATCH_FAILED = -801
  integer(c_int), parameter :: SITUATION_ERROR_COMPUTE_BUFFER_BINDING_MISSING = -802
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_INIT_FAILED = -900
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_SOCKET_CREATION_FAILED = -901
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_CONNECTION_FAILED = -902
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_SEND_FAILED = -903
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_RECEIVE_FAILED = -904
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_BIND_FAILED = -905
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_LISTEN_FAILED = -906
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_ACCEPT_FAILED = -907
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_TIMEOUT = -908
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_DNS_RESOLUTION_FAILED = -909
  integer(c_int), parameter :: SITUATION_ERROR_NETWORK_TLS_HANDSHAKE_FAILED = -910
  integer(c_int), parameter :: SITUATION_ERROR_UNKNOWN_ERROR = -999

  ! --- SituationInitState ---
  integer(c_int), parameter :: SITUATION_STATE_UNINITIALIZED = 0
  integer(c_int), parameter :: SITUATION_STATE_INITIALIZING = 1
  integer(c_int), parameter :: SITUATION_STATE_READY = 2
  integer(c_int), parameter :: SITUATION_STATE_SHUTTING_DOWN = 3

  ! --- SituationJobFlags ---
  integer(c_int), parameter :: SIT_SUBMIT_DEFAULT = 0
  integer(c_int), parameter :: SIT_SUBMIT_HIGH_PRIORITY = 1
  integer(c_int), parameter :: SIT_SUBMIT_BLOCK_IF_FULL = 2
  integer(c_int), parameter :: SIT_SUBMIT_RUN_IF_FULL = 4
  integer(c_int), parameter :: SIT_SUBMIT_POINTER_ONLY = 8

  ! --- SituationThreadCapability ---
  integer(c_int), parameter :: SITUATION_THREAD_CAP_NONE = 0
  integer(c_int), parameter :: SITUATION_THREAD_CAP_C11_THREADS = 1
  integer(c_int), parameter :: SITUATION_THREAD_CAP_C11_ATOMICS = 2
  integer(c_int), parameter :: SITUATION_THREAD_CAP_MUTEX = 4
  integer(c_int), parameter :: SITUATION_THREAD_CAP_SLEEP = 8
  integer(c_int), parameter :: SITUATION_THREAD_CAP_PLATFORM_SLEEP = 16

  ! --- SituationThreadRole ---
  integer(c_int), parameter :: SIT_THREAD_ROLE_UNKNOWN = 0
  integer(c_int), parameter :: SIT_THREAD_ROLE_MAIN = 1
  integer(c_int), parameter :: SIT_THREAD_ROLE_WORKER = 2
  integer(c_int), parameter :: SIT_THREAD_ROLE_IO = 3
  integer(c_int), parameter :: SIT_THREAD_ROLE_RENDER = 4
  integer(c_int), parameter :: SIT_THREAD_ROLE_AUDIO = 5

  ! --- SituationJobQueueMask ---
  integer(c_int), parameter :: SIT_JOB_QUEUE_LOW = 1
  integer(c_int), parameter :: SIT_JOB_QUEUE_HIGH = 2
  integer(c_int), parameter :: SIT_JOB_QUEUE_BOTH = 3

  ! --- SituationWindowStateFlags ---
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_ON_TOP = SITUATION_FLAG_WINDOW_TOPMOST
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_HIDDEN = SITUATION_FLAG_WINDOW_HIDDEN
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_FROZEN = SITUATION_FLAG_WINDOW_FROZEN
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_FULLSCREEN = SITUATION_FLAG_FULLSCREEN_MODE
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_UNDECORATED = SITUATION_FLAG_WINDOW_UNDECORATED
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_ALWAYS_RUN = SITUATION_FLAG_WINDOW_ALWAYS_RUN
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_MINIMIZED = SITUATION_FLAG_WINDOW_MINIMIZED
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_MAXIMIZED = SITUATION_FLAG_WINDOW_MAXIMIZED
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_RESIZABLE = SITUATION_FLAG_WINDOW_RESIZABLE
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_BORDERLESS = SITUATION_FLAG_BORDERLESS_WINDOWED_MODE
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_MSAA_4X_HINT = SITUATION_FLAG_MSAA_4X_HINT
  integer(c_int), parameter :: SITUATION_WINDOW_STATE_VSYNC_HINT = SITUATION_FLAG_VSYNC_HINT

  ! --- SituationOutputColorDepth ---
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_AUTO = 0
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_8BIT = 1
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_10BIT = 2
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_HDR10 = 3

  ! --- SituationOutputColorSpace ---
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_SPACE_UNKNOWN = 0
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_SPACE_SDR_SRGB = 1
  integer(c_int), parameter :: SIT_OUTPUT_COLOR_SPACE_HDR10_ST2084 = 2

  ! --- SituationRenderBackpressurePolicy ---
  integer(c_int), parameter :: SIT_RENDER_BACKPRESSURE_SPIN = 0
  integer(c_int), parameter :: SIT_RENDER_BACKPRESSURE_YIELD = 1
  integer(c_int), parameter :: SIT_RENDER_BACKPRESSURE_SLEEP = 2

  ! --- SituationBufferUsageFlags ---
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_VERTEX_BUFFER = 1
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_INDEX_BUFFER = 2
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_UNIFORM_BUFFER = 4
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_STORAGE_BUFFER = 8
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_INDIRECT_BUFFER = 16
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_TRANSFER_SRC = 32
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_TRANSFER_DST = 64
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_DEVICE_ADDRESS = 128
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_VERTEX_AND_STORAGE = 9
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_DYNAMIC_VERTEX = 65
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_DYNAMIC_UNIFORM = 68
  integer(c_int), parameter :: SITUATION_BUFFER_USAGE_STORAGE_COMPUTE = 232

  ! --- SituationColorEncoding ---
  integer(c_int), parameter :: SITUATION_COLOR_LINEAR = 0
  integer(c_int), parameter :: SITUATION_COLOR_SRGB = 1

  ! --- SituationRendererType ---
  integer(c_int), parameter :: SIT_RENDERER_OPENGL = 0
  integer(c_int), parameter :: SIT_RENDERER_VULKAN = 1

  ! --- SituationComputeLayoutType ---
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_ONE_SSBO = 0
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_TWO_SSBOS = 1
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_IMAGE_AND_SSBO = 2
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_PUSH_CONSTANT = 3
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_EMPTY = 4
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_BUFFER_IMAGE = 5
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_GRID = 6  ! canonical grid.comp layout
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_TERMINAL = 6  ! deprecated alias
  integer(c_int), parameter :: SIT_COMPUTE_LAYOUT_VECTOR = 7

  ! --- SituationSpirvLayoutProfile ---
  integer(c_int), parameter :: SIT_SPIRV_LAYOUT_PROFILE_MESH = 0
  integer(c_int), parameter :: SIT_SPIRV_LAYOUT_PROFILE_DUAL_SSBO = 1
  integer(c_int), parameter :: SIT_SPIRV_LAYOUT_PROFILE_UBO_SSBO = 2
  integer(c_int), parameter :: SIT_SPIRV_LAYOUT_PROFILE_UBO_SSBO_SAMPLER = 3

  ! --- SituationTextureUsageFlags ---
  integer(c_int), parameter :: SITUATION_TEXTURE_USAGE_SAMPLED = 1
  integer(c_int), parameter :: SITUATION_TEXTURE_USAGE_STORAGE = 2
  integer(c_int), parameter :: SITUATION_TEXTURE_USAGE_TRANSFER_SRC = 4
  integer(c_int), parameter :: SITUATION_TEXTURE_USAGE_TRANSFER_DST = 8
  integer(c_int), parameter :: SITUATION_TEXTURE_USAGE_COMPUTE_SAMPLED = 16

  ! --- SituationTextureFormat ---
  integer(c_int), parameter :: SIT_TEXTURE_FORMAT_UNKNOWN = 0
  integer(c_int), parameter :: SIT_TEXTURE_FORMAT_RGBA8_UNORM = 1
  integer(c_int), parameter :: SIT_TEXTURE_FORMAT_RGBA8_SRGB = 2

  ! --- SituationTextureFilter ---
  integer(c_int), parameter :: SIT_TEXTURE_FILTER_NEAREST = 0
  integer(c_int), parameter :: SIT_TEXTURE_FILTER_LINEAR = 1

  ! --- SituationTextureWrap ---
  integer(c_int), parameter :: SIT_TEXTURE_WRAP_CLAMP_TO_EDGE = 0
  integer(c_int), parameter :: SIT_TEXTURE_WRAP_REPEAT = 1

  ! --- SituationTextureReadFormat ---
  integer(c_int), parameter :: SIT_TEXTURE_READ_RGBA8 = 0
  integer(c_int), parameter :: SIT_TEXTURE_READ_RGB10_PACKED = 1

  ! --- SituationBlitFilter ---
  integer(c_int), parameter :: SITUATION_BLIT_FILTER_NEAREST = 0
  integer(c_int), parameter :: SITUATION_BLIT_FILTER_LINEAR = 1

  ! --- SituationBlendMode ---
  integer(c_int), parameter :: SITUATION_BLEND_ALPHA = 0
  integer(c_int), parameter :: SITUATION_BLEND_ADDITIVE = 1
  integer(c_int), parameter :: SITUATION_BLEND_MULTIPLY = 2
  integer(c_int), parameter :: SITUATION_BLEND_SCREEN = 3
  integer(c_int), parameter :: SITUATION_BLEND_NONE = 4
  integer(c_int), parameter :: SITUATION_BLEND_OVERLAY = 5
  integer(c_int), parameter :: SITUATION_BLEND_SOFT_LIGHT = 6
  integer(c_int), parameter :: SITUATION_BLEND_HARD_LIGHT = 7
  integer(c_int), parameter :: SITUATION_BLEND_COLOR_DODGE = 8
  integer(c_int), parameter :: SITUATION_BLEND_COLOR_BURN = 9
  integer(c_int), parameter :: SITUATION_BLEND_DARKEN = 10
  integer(c_int), parameter :: SITUATION_BLEND_LIGHTEN = 11
  integer(c_int), parameter :: SITUATION_BLEND_DIFFERENCE = 12
  integer(c_int), parameter :: SITUATION_BLEND_EXCLUSION = 13

  ! --- SituationScalingMode ---
  integer(c_int), parameter :: SITUATION_SCALING_STRETCH = 0
  integer(c_int), parameter :: SITUATION_SCALING_FIT = 1
  integer(c_int), parameter :: SITUATION_SCALING_INTEGER = 2

  ! --- SituationVDFlags ---
  integer(c_int), parameter :: SITUATION_VD_FLAG_NONE = 0
  integer(c_int), parameter :: SITUATION_VD_FLAG_COMPUTE_TARGET = 1

  ! --- SituationVirtualDisplayColorFormat ---
  integer(c_int), parameter :: SIT_VD_FORMAT_RGBA8_UNORM = 0
  integer(c_int), parameter :: SIT_VD_FORMAT_RGBA8_SRGB = 1

  ! --- SituationVirtualDisplayDepthStencilMode ---
  integer(c_int), parameter :: SIT_VD_DEPTH_NONE = 0
  integer(c_int), parameter :: SIT_VD_DEPTH_D24 = 1
  integer(c_int), parameter :: SIT_VD_DEPTH_D24S8 = 2

  ! --- SituationVDFallbackMode ---
  integer(c_int), parameter :: SITUATION_VD_FALLBACK_SOLID = 0
  integer(c_int), parameter :: SITUATION_VD_FALLBACK_COLORBURST = 1
  integer(c_int), parameter :: SITUATION_VD_FALLBACK_PATTERN = 2

  ! --- SitVdStandbyLayer ---
  integer(c_int), parameter :: SIT_VD_STANDBY_SMPTE_BARS = 0
  integer(c_int), parameter :: SIT_VD_STANDBY_CHECKERBOARD = 1
  integer(c_int), parameter :: SIT_VD_STANDBY_CONVERGENCE = 2
  integer(c_int), parameter :: SIT_VD_STANDBY_GRADIENTS = 3
  integer(c_int), parameter :: SIT_VD_STANDBY_GRID_ONLY = 4
  integer(c_int), parameter :: SIT_VD_STANDBY_PLUGE = 5
  integer(c_int), parameter :: SIT_VD_STANDBY_CROSSHATCH = 6
  integer(c_int), parameter :: SIT_VD_STANDBY_MULTIBURST = 7
  integer(c_int), parameter :: SIT_VD_STANDBY_3D_GRID = 8

  ! --- SituationAttachmentLoadOp ---
  integer(c_int), parameter :: SIT_LOAD_OP_LOAD = 0
  integer(c_int), parameter :: SIT_LOAD_OP_CLEAR = 1
  integer(c_int), parameter :: SIT_LOAD_OP_DONT_CARE = 2

  ! --- SituationAttachmentStoreOp ---
  integer(c_int), parameter :: SIT_STORE_OP_STORE = 0
  integer(c_int), parameter :: SIT_STORE_OP_DONT_CARE = 1

  ! --- SituationClearFlags ---
  integer(c_int), parameter :: SIT_CLEAR_COLOR_BIT = 1
  integer(c_int), parameter :: SIT_CLEAR_DEPTH_BIT = 2
  integer(c_int), parameter :: SIT_CLEAR_STENCIL_BIT = 4

  ! --- SituationUniformType ---
  integer(c_int), parameter :: SIT_UNIFORM_FLOAT = 0
  integer(c_int), parameter :: SIT_UNIFORM_VEC2 = 1
  integer(c_int), parameter :: SIT_UNIFORM_VEC3 = 2
  integer(c_int), parameter :: SIT_UNIFORM_VEC4 = 3
  integer(c_int), parameter :: SIT_UNIFORM_INT = 4
  integer(c_int), parameter :: SIT_UNIFORM_IVEC2 = 5
  integer(c_int), parameter :: SIT_UNIFORM_IVEC3 = 6
  integer(c_int), parameter :: SIT_UNIFORM_IVEC4 = 7
  integer(c_int), parameter :: SIT_UNIFORM_MAT4 = 8

  ! --- SituationRenderFeature ---
  integer(c_int), parameter :: SIT_FEATURE_GEOMETRY_SHADER = 1
  integer(c_int), parameter :: SIT_FEATURE_TESSELLATION_SHADER = 2
  integer(c_int), parameter :: SIT_FEATURE_WIDE_LINES = 4
  integer(c_int), parameter :: SIT_FEATURE_FILL_MODE_NON_SOLID = 8
  integer(c_int), parameter :: SIT_FEATURE_SAMPLER_ANISOTROPY = 16
  integer(c_int), parameter :: SIT_FEATURE_MULTI_VIEWPORT = 32
  integer(c_int), parameter :: SIT_FEATURE_COMPUTE_SHADER = 64
  integer(c_int), parameter :: SIT_FEATURE_INT64 = 128
  integer(c_int), parameter :: SIT_FEATURE_FLOAT64 = 256
  integer(c_int), parameter :: SIT_FEATURE_FLOAT16 = 512
  integer(c_int), parameter :: SIT_FEATURE_SUBGROUP_OPERATIONS = 1024
  integer(c_int), parameter :: SIT_FEATURE_BINDLESS_BUFFERS = 2048
  integer(c_int), parameter :: SIT_FEATURE_BINDLESS_TEXTURES = 4096
  integer(c_int), parameter :: SIT_FEATURE_DRAW_INDIRECT_COUNT = 8192
  integer(c_int), parameter :: SIT_FEATURE_MULTI_DRAW_INDIRECT = 16384
  integer(c_int), parameter :: SIT_FEATURE_MESH_SHADER = 32768
  integer(c_int), parameter :: SIT_FEATURE_RAY_TRACING = 65536
  integer(c_int), parameter :: SIT_FEATURE_VARIABLE_RATE_SHADING = 131072
  integer(c_int), parameter :: SIT_FEATURE_ATOMIC_FLOAT = 262144
  integer(c_int), parameter :: SIT_FEATURE_TEXTURE_COMPRESSION_BC = 524288
  integer(c_int), parameter :: SIT_FEATURE_TEXTURE_COMPRESSION_ASTC = 1048576
  integer(c_int), parameter :: SIT_FEATURE_HDR_OUTPUT = 2097152
  integer(c_int), parameter :: SIT_FEATURE_10BIT_SDR_OUTPUT = 4194304

  ! --- SituationDataType ---
  integer(c_int), parameter :: SIT_DATA_BYTE = 0
  integer(c_int), parameter :: SIT_DATA_UNSIGNED_BYTE = 1
  integer(c_int), parameter :: SIT_DATA_SHORT = 2
  integer(c_int), parameter :: SIT_DATA_UNSIGNED_SHORT = 3
  integer(c_int), parameter :: SIT_DATA_INT = 4
  integer(c_int), parameter :: SIT_DATA_UNSIGNED_INT = 5
  integer(c_int), parameter :: SIT_DATA_FLOAT = 6
  integer(c_int), parameter :: SIT_DATA_DOUBLE = 7

  ! --- SituationGLShaderSourceType ---
  integer(c_int), parameter :: SITUATION_GL_SHADER_SOURCE_TYPE_GLSL = 0
  integer(c_int), parameter :: SITUATION_GL_SHADER_SOURCE_TYPE_SPIRV = 1

  ! --- SituationBarrierSrcFlags ---
  integer(c_int), parameter :: SITUATION_BARRIER_VERTEX_SHADER_WRITE = 1
  integer(c_int), parameter :: SITUATION_BARRIER_FRAGMENT_SHADER_WRITE = 2
  integer(c_int), parameter :: SITUATION_BARRIER_COMPUTE_SHADER_WRITE = 4
  integer(c_int), parameter :: SITUATION_BARRIER_TRANSFER_WRITE = 8

  ! --- SituationBarrierDstFlags ---
  integer(c_int), parameter :: SITUATION_BARRIER_VERTEX_SHADER_READ = 1
  integer(c_int), parameter :: SITUATION_BARRIER_FRAGMENT_SHADER_READ = 2
  integer(c_int), parameter :: SITUATION_BARRIER_COMPUTE_SHADER_READ = 4
  integer(c_int), parameter :: SITUATION_BARRIER_TRANSFER_READ = 8
  integer(c_int), parameter :: SITUATION_BARRIER_INDIRECT_COMMAND_READ = 16

  ! --- SituationPipelineStageFlags ---
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_TOP = 1
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_INDIRECT_COMMAND = 2
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_VERTEX_INPUT = 4
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_VERTEX_SHADER = 8
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_FRAGMENT_SHADER = 16
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_COLOR_ATTACHMENT = 32
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_DEPTH_STENCIL = 64
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_COMPUTE_SHADER = 128
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_TRANSFER = 256
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_HOST = 512
  integer(c_int), parameter :: SITUATION_PIPELINE_STAGE_BOTTOM = 1024

  ! --- SituationAccessFlags ---
  integer(c_int), parameter :: SITUATION_ACCESS_INDIRECT_COMMAND_READ = 1
  integer(c_int), parameter :: SITUATION_ACCESS_VERTEX_READ = 2
  integer(c_int), parameter :: SITUATION_ACCESS_INDEX_READ = 4
  integer(c_int), parameter :: SITUATION_ACCESS_UNIFORM_READ = 8
  integer(c_int), parameter :: SITUATION_ACCESS_SHADER_READ = 16
  integer(c_int), parameter :: SITUATION_ACCESS_SHADER_WRITE = 32
  integer(c_int), parameter :: SITUATION_ACCESS_COLOR_ATTACHMENT_READ = 64
  integer(c_int), parameter :: SITUATION_ACCESS_COLOR_ATTACHMENT_WRITE = 128
  integer(c_int), parameter :: SITUATION_ACCESS_DEPTH_STENCIL_READ = 256
  integer(c_int), parameter :: SITUATION_ACCESS_DEPTH_STENCIL_WRITE = 512
  integer(c_int), parameter :: SITUATION_ACCESS_TRANSFER_READ = 1024
  integer(c_int), parameter :: SITUATION_ACCESS_TRANSFER_WRITE = 2048
  integer(c_int), parameter :: SITUATION_ACCESS_HOST_READ = 4096
  integer(c_int), parameter :: SITUATION_ACCESS_HOST_WRITE = 8192

  ! --- SituationTextureLayout ---
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_UNDEFINED = 0
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_GENERAL = 1
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_SHADER_READ = 2
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_TRANSFER_SRC = 3
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_TRANSFER_DST = 4
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_COLOR_ATTACHMENT = 5
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_DEPTH_STENCIL_ATTACHMENT = 6
  integer(c_int), parameter :: SITUATION_TEXTURE_LAYOUT_PRESENT = 7

  ! --- SituationGraphicsBackend ---
  integer(c_int), parameter :: SIT_GRAPHICS_BACKEND_UNKNOWN = 0
  integer(c_int), parameter :: SIT_GRAPHICS_BACKEND_OPENGL = 1
  integer(c_int), parameter :: SIT_GRAPHICS_BACKEND_VULKAN = 2

  ! --- SituationCullMode ---
  integer(c_int), parameter :: SIT_CULL_NONE = 0
  integer(c_int), parameter :: SIT_CULL_BACK = 1
  integer(c_int), parameter :: SIT_CULL_FRONT = 2

  ! --- SituationFrontFace ---
  integer(c_int), parameter :: SIT_FRONT_FACE_CCW = 0
  integer(c_int), parameter :: SIT_FRONT_FACE_CW = 1

  ! --- SituationPrimitiveTopology ---
  integer(c_int), parameter :: SIT_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 0
  integer(c_int), parameter :: SIT_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 1
  integer(c_int), parameter :: SIT_PRIMITIVE_TOPOLOGY_LINE_LIST = 2
  integer(c_int), parameter :: SIT_PRIMITIVE_TOPOLOGY_LINE_STRIP = 3
  integer(c_int), parameter :: SIT_PRIMITIVE_TOPOLOGY_POINT_LIST = 4

  ! --- SituationPolygonMode ---
  integer(c_int), parameter :: SIT_POLYGON_MODE_FILL = 0
  integer(c_int), parameter :: SIT_POLYGON_MODE_LINE = 1
  integer(c_int), parameter :: SIT_POLYGON_MODE_POINT = 2

  ! --- SituationIndexType ---
  integer(c_int), parameter :: SIT_INDEX_UINT32 = 0
  integer(c_int), parameter :: SIT_INDEX_UINT16 = 1

  ! --- SituationDepthCompareOp ---
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_ALWAYS = 0
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_LESS = 1
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_LEQUAL = 2
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_GREATER = 3
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_GEQUAL = 4
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_EQUAL = 5
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_NOTEQUAL = 6
  integer(c_int), parameter :: SIT_DEPTH_COMPARE_NEVER = 7

  ! --- SituationStencilOp ---
  integer(c_int), parameter :: SIT_STENCIL_OP_KEEP = 0
  integer(c_int), parameter :: SIT_STENCIL_OP_ZERO = 1
  integer(c_int), parameter :: SIT_STENCIL_OP_REPLACE = 2
  integer(c_int), parameter :: SIT_STENCIL_OP_INCREMENT_CLAMP = 3
  integer(c_int), parameter :: SIT_STENCIL_OP_DECREMENT_CLAMP = 4
  integer(c_int), parameter :: SIT_STENCIL_OP_INVERT = 5
  integer(c_int), parameter :: SIT_STENCIL_OP_INCREMENT_WRAP = 6
  integer(c_int), parameter :: SIT_STENCIL_OP_DECREMENT_WRAP = 7

  ! --- SituationBlendFactor ---
  integer(c_int), parameter :: SIT_BLEND_ZERO = 0
  integer(c_int), parameter :: SIT_BLEND_ONE = 1
  integer(c_int), parameter :: SIT_BLEND_SRC_COLOR = 2
  integer(c_int), parameter :: SIT_BLEND_ONE_MINUS_SRC_COLOR = 3
  integer(c_int), parameter :: SIT_BLEND_DST_COLOR = 4
  integer(c_int), parameter :: SIT_BLEND_ONE_MINUS_DST_COLOR = 5
  integer(c_int), parameter :: SIT_BLEND_SRC_ALPHA = 6
  integer(c_int), parameter :: SIT_BLEND_ONE_MINUS_SRC_ALPHA = 7
  integer(c_int), parameter :: SIT_BLEND_DST_ALPHA = 8
  integer(c_int), parameter :: SIT_BLEND_ONE_MINUS_DST_ALPHA = 9

  ! --- SituationMeshVertexLayout ---
  integer(c_int), parameter :: SIT_MESH_LAYOUT_POS_NRM_TEX = 0
  integer(c_int), parameter :: SIT_MESH_LAYOUT_POS_ONLY = 1
  integer(c_int), parameter :: SIT_MESH_LAYOUT_POS_TEX = 2
  integer(c_int), parameter :: SIT_MESH_LAYOUT_POS_NRM = 3
  integer(c_int), parameter :: SIT_MESH_LAYOUT_POS_NRM_TAN_TEX = 4
  integer(c_int), parameter :: SIT_MESH_LAYOUT_PULL = 5

  ! --- SituationCameraFlags ---
  integer(c_int), parameter :: SIT_CAMERA_FLAG_NONE = 0
  integer(c_int), parameter :: SIT_CAMERA_FLAG_ORTHOGRAPHIC = 1
  integer(c_int), parameter :: SIT_CAMERA_FLAG_REVERSE_Z = 2
  integer(c_int), parameter :: SIT_CAMERA_FLAG_INFINITE_PROJECTION = 4

  ! --- SituationAudioDeviceType ---
  integer(c_int), parameter :: SIT_AUDIO_DEVICE_TYPE_UNKNOWN = 0
  integer(c_int), parameter :: SIT_AUDIO_DEVICE_TYPE_PLAYBACK = 1
  integer(c_int), parameter :: SIT_AUDIO_DEVICE_TYPE_CAPTURE = 2
  integer(c_int), parameter :: SIT_AUDIO_DEVICE_TYPE_DUPLEX = 3
  integer(c_int), parameter :: SIT_AUDIO_DEVICE_TYPE_LOOPBACK = 4

  ! --- SituationDeviceCategory ---
  integer(c_int), parameter :: SITUATION_DEVICE_EFFECT = 0
  integer(c_int), parameter :: SITUATION_DEVICE_SOURCE = 1
  integer(c_int), parameter :: SITUATION_DEVICE_CAPTURE = 2
  integer(c_int), parameter :: SITUATION_DEVICE_UTILITY = 3
  integer(c_int), parameter :: SITUATION_DEVICE_MODULATOR = 4
  integer(c_int), parameter :: SITUATION_DEVICE_ANALYZER = 5
  integer(c_int), parameter :: SITUATION_DEVICE_CUSTOM = 6

  ! --- SituationControlType ---
  integer(c_int), parameter :: SITUATION_CONTROL_FLOAT = 0
  integer(c_int), parameter :: SITUATION_CONTROL_INT = 1
  integer(c_int), parameter :: SITUATION_CONTROL_BOOL = 2
  integer(c_int), parameter :: SITUATION_CONTROL_ENUM = 3

  ! --- SituationNodeType ---
  integer(c_int), parameter :: SITUATION_NODE_REVERB = 0
  integer(c_int), parameter :: SITUATION_NODE_ECHO = 1
  integer(c_int), parameter :: SITUATION_NODE_CHORUS = 2
  integer(c_int), parameter :: SITUATION_NODE_PHASER = 3
  integer(c_int), parameter :: SITUATION_NODE_OVERDRIVE = 4
  integer(c_int), parameter :: SITUATION_NODE_EXCITER = 5
  integer(c_int), parameter :: SITUATION_NODE_MAXIMIZER = 6
  integer(c_int), parameter :: SITUATION_NODE_SPRING_REVERB = 7
  integer(c_int), parameter :: SITUATION_NODE_STUDIO_REVERB = 8
  integer(c_int), parameter :: SITUATION_NODE_SST282 = 9
  integer(c_int), parameter :: SITUATION_NODE_DYNAMICS = 10
  integer(c_int), parameter :: SITUATION_NODE_COMPANDER = 11
  integer(c_int), parameter :: SITUATION_NODE_EQ_4BAND = 12
  integer(c_int), parameter :: SITUATION_NODE_FILTER = 13
  integer(c_int), parameter :: SITUATION_NODE_MASTERING_AMP = 14
  integer(c_int), parameter :: SITUATION_NODE_DEAFMAX = 15
  integer(c_int), parameter :: SITUATION_NODE_ISA110 = 16
  integer(c_int), parameter :: SITUATION_NODE_PANNER = 17
  integer(c_int), parameter :: SITUATION_NODE_GAIN = 18
  integer(c_int), parameter :: SITUATION_NODE_MIXER = 19
  integer(c_int), parameter :: SITUATION_NODE_SOUND_SOURCE = 20
  integer(c_int), parameter :: SITUATION_NODE_TONE_SYNTH = 21
  integer(c_int), parameter :: SITUATION_NODE_PCM_INPUT = 22
  integer(c_int), parameter :: SITUATION_NODE_MIC_CAPTURE = 23
  integer(c_int), parameter :: SITUATION_NODE_LFO = 24
  integer(c_int), parameter :: SITUATION_NODE_ENVELOPE_FOLLOWER = 25
  integer(c_int), parameter :: SITUATION_NODE_SPECTRUM_ANALYZER = 26
  integer(c_int), parameter :: SITUATION_NODE_PEAK_METER = 27
  integer(c_int), parameter :: SITUATION_NODE_CUSTOM = 1000

  ! --- SituationAudioLoadMode ---
  integer(c_int), parameter :: SITUATION_AUDIO_LOAD_AUTO = 0
  integer(c_int), parameter :: SITUATION_AUDIO_LOAD_FULL = 1
  integer(c_int), parameter :: SITUATION_AUDIO_LOAD_STREAM = 2

  ! --- SituationWaveType ---
  integer(c_int), parameter :: SIT_WAVE_SINE = 0
  integer(c_int), parameter :: SIT_WAVE_SQUARE = 1
  integer(c_int), parameter :: SIT_WAVE_TRIANGLE = 2
  integer(c_int), parameter :: SIT_WAVE_SAW = 3
  integer(c_int), parameter :: SIT_WAVE_NOISE = 4

  ! --- SituationFilterType ---
  integer(c_int), parameter :: SITUATION_FILTER_NONE = 0
  integer(c_int), parameter :: SITUATION_FILTER_LOWPASS = 1
  integer(c_int), parameter :: SITUATION_FILTER_HIGHPASS = 2

  ! --- SituationLogLevel ---
  integer(c_int), parameter :: SIT_LOG_ALL = 0
  integer(c_int), parameter :: SIT_LOG_TRACE = 1
  integer(c_int), parameter :: SIT_LOG_DEBUG = 2
  integer(c_int), parameter :: SIT_LOG_INFO = 3
  integer(c_int), parameter :: SIT_LOG_WARNING = 4
  integer(c_int), parameter :: SIT_LOG_ERROR = 5
  integer(c_int), parameter :: SIT_LOG_FATAL = 6
  integer(c_int), parameter :: SIT_LOG_NONE = 7

  ! --- SituationImageFlipMode ---
  integer(c_int), parameter :: SIT_FLIP_VERTICAL = 0
  integer(c_int), parameter :: SIT_FLIP_HORIZONTAL = 1
  integer(c_int), parameter :: SIT_FLIP_BOTH = 2

  ! --- SituationScreenshotFormat ---
  integer(c_int), parameter :: SIT_SCREENSHOT_BMP = 0
  integer(c_int), parameter :: SIT_SCREENSHOT_PNG = 1
  integer(c_int), parameter :: SIT_SCREENSHOT_JPG = 2
  integer(c_int), parameter :: SIT_SCREENSHOT_TGA = 3
  integer(c_int), parameter :: SIT_SCREENSHOT_FORMAT_COUNT = 4

  ! --- SituationCursor ---
  integer(c_int), parameter :: SIT_CURSOR_DEFAULT = 0
  integer(c_int), parameter :: SIT_CURSOR_ARROW = 1
  integer(c_int), parameter :: SIT_CURSOR_IBEAM = 2
  integer(c_int), parameter :: SIT_CURSOR_CROSSHAIR = 3
  integer(c_int), parameter :: SIT_CURSOR_HAND = 4
  integer(c_int), parameter :: SIT_CURSOR_HRESIZE = 5
  integer(c_int), parameter :: SIT_CURSOR_VRESIZE = 6

  ! --- Auto-generated opaque type stubs ---
  ! These types are referenced by the API but their layout is internal.
  ! Pass them as type(c_ptr) at FFI boundaries.

  type :: SituationThreadingStatus
    private
    integer(c_int) :: opaque_stub
  end type SituationThreadingStatus

end module situation_types
