(* Auto-generated by tools/generate_modula2_bindings.py — Situation 2.4.357 (Consolidate color-space math into situation_impl_color.h; trace table regenerated.) *)
(* Do not edit by hand. *)

(* Implementation companion for SituationHelpers.def *)

IMPLEMENTATION MODULE SituationHelpers;

FROM SituationForeign IMPORT SituationPollInputEvents, SituationUpdateTimers;
FROM SituationTypes IMPORT SituationError;

CONST
  SITUATION_SUCCESS = 0;

PROCEDURE situationBeginFrame;
BEGIN
  SituationPollInputEvents();
  SituationUpdateTimers()
END situationBeginFrame;

PROCEDURE situationSuccess (err: SituationError): BOOLEAN;
BEGIN
  RETURN err = SITUATION_SUCCESS
END situationSuccess;

END SituationHelpers.
