"""Shared utilities for Situation language binding generators."""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path

from situation_api_parser import ROOT, ApiEntry, parse_enums, parse_errno_enum

MANUAL_FUNCTIONS = {
    "SituationLog",
    "SituationLogWarning",
    "SituationImageDrawTextFormatted",
}


def split_params(param_str: str) -> list[str]:
    params: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in param_str:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            p = "".join(current).strip()
            if p and p != "void":
                params.append(p)
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail and tail != "void":
        params.append(tail)
    return params


def normalize_c_type(ctype: str) -> str:
    ctype = ctype.strip()
    ctype = re.sub(r"\bconst\s+", "", ctype)
    ctype = re.sub(r"\bvolatile\s+", "", ctype)
    ctype = re.sub(r"__attribute__\s*\(\([^)]*\)\)", "", ctype)
    ctype = re.sub(r"__declspec\s*\([^)]*\)", "", ctype)
    return re.sub(r"\s+", " ", ctype).strip()


def parse_param(param: str, c_type_to_lang: Callable[[str], str]) -> tuple[str, str] | None:
    param = param.strip()
    if not param or param == "...":
        return None
    if "(*" in param:
        return None
    m = re.match(r"^(?:const\s+)?(.+?)\s+(\w+)$", param)
    if not m:
        m = re.match(r"^(.+?)\s+(\w+)$", param)
    if not m:
        return None
    ctype, pname = m.group(1).strip(), m.group(2).strip()
    return pname, c_type_to_lang(ctype)


def parse_function_signature(
    sig: str,
    c_type_to_lang: Callable[[str], str],
) -> tuple[str, str, list[tuple[str, str]]] | None:
    m = re.match(r"^(const\s+)?(.+?)\s+(\w+)\s*\((.*)\)\s*;?\s*$", sig.strip())
    if not m:
        return None
    ret = c_type_to_lang(m.group(2).strip())
    name = m.group(3)
    params: list[tuple[str, str]] = []
    for p in split_params(m.group(4)):
        parsed = parse_param(p, c_type_to_lang)
        if parsed:
            params.append(parsed)
    return ret, name, params


def build_define_map() -> dict[str, str]:
    text = (ROOT / "sit" / "situation_api.h").read_text(encoding="utf-8", errors="replace")
    dmap: dict[str, str] = {}
    for m in re.finditer(r"^#define\s+(\w+)\s+(0x[\da-fA-F]+|\d+)", text, re.MULTILINE):
        dmap[m.group(1)] = m.group(2)
    return dmap


def resolve_enum_value(value: str, define_map: dict[str, str]) -> str:
    resolved = value.strip()
    if resolved in define_map:
        return define_map[resolved]
    if "|" in resolved:
        parts = [p.strip() for p in resolved.split("|")]
        parts = [define_map.get(p, p) for p in parts]
        return " | ".join(parts)
    return resolved


def foreign_entries(entries: list[ApiEntry]) -> list[ApiEntry]:
    return [e for e in entries if not e.manual_only and e.name not in MANUAL_FUNCTIONS]


def gen_banner(tool_name: str, version: str, lang_comment: str = "//") -> str:
    return (
        f"{lang_comment} Auto-generated by tools/{tool_name} — Situation {version}\n"
        f"{lang_comment} Do not edit by hand.\n\n"
    )
