#!/usr/bin/env python3
"""Generate backend-specific force-link C and export .def from a Situation static archive.

Usage:
  python tools/gen_lua_force_link.py <static.a> <out_force_link.c> <out_exports.def>
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FOREIGN_LIST = ROOT / "wrappers" / "lua" / "situation" / "foreign.lua"


def read_foreign_names() -> list[str]:
    text = FOREIGN_LIST.read_text(encoding="utf-8")
    return re.findall(r'"((?:Situation|glfw)[^"]+)"', text)


def read_defined_symbols(archive: Path) -> set[str]:
    proc = subprocess.run(["nm", str(archive)], capture_output=True, text=True, check=True)
    defined: set[str] = set()
    for line in proc.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[1] in {"T", "D", "B"}:
            defined.add(parts[2])
    return defined


def render_force_link(names: list[str]) -> str:
    lines = [
        "/* Auto-generated by tools/gen_lua_force_link.py */",
        "#include <stdint.h>",
        "",
    ]
    for name in names:
        lines.append(f"extern void {name}(void);")
    lines.append("")
    lines.append("void sit_lua_force_link_anchor(void)")
    lines.append("{")
    for name in names:
        lines.append(f"    (void)(uintptr_t)&{name};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_def(names: list[str]) -> str:
    return "EXPORTS\n" + "\n".join(names) + "\n"


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(
            "usage: python tools/gen_lua_force_link.py <static.a> <out_force_link.c> <out_exports.def>"
        )

    archive = Path(sys.argv[1]).resolve()
    out_c = Path(sys.argv[2]).resolve()
    out_def = Path(sys.argv[3]).resolve()

    if not archive.is_file():
        raise SystemExit(f"archive not found: {archive}")
    if not FOREIGN_LIST.is_file():
        raise SystemExit(f"foreign list not found: {FOREIGN_LIST}")

    defined = read_defined_symbols(archive)
    names = [name for name in read_foreign_names() if name in defined]
    if not names:
        raise SystemExit(f"no Situation API symbols found in {archive}")

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text(render_force_link(names), encoding="utf-8")
    out_def.write_text(render_def(names), encoding="utf-8")
    print(f"Lua static link: {len(names)} symbols from {archive.name}")


if __name__ == "__main__":
    main()