#!/usr/bin/env python3
"""Generate GNU Modula-2 (gm2) FFI bindings from Situation public C headers.

Outputs (under wrappers/Modula2/src/):
  SituationTypes.def      — RECORD types, INTEGER enum aliases, opaque handles
  SituationCallbacks.def  — PROCEDURE type aliases for callbacks
  SituationForeign.def    — EXTERN procedure declarations
  SituationConstants.def  — CONST values from parse_defines
  SituationHelpers.def    — frame macro helper declarations
  SituationHelpers.mod    — helper implementations (IMPLEMENTATION MODULE)
  API_INDEX.md            — categorized binding index
  MANUAL_BINDINGS.md      — symbols requiring hand-written wrappers

Usage:
  python tools/generate_modula2_bindings.py
  python tools/generate_modula2_bindings.py --lib situation_opengl
"""

from __future__ import annotations

import argparse
import re
from datetime import datetime, timezone
from pathlib import Path

from binding_common import (
    MANUAL_FUNCTIONS,
    build_define_map,
    foreign_entries,
    normalize_c_type,
    parse_function_signature,
    strip_c_api_attributes,
    parse_param,
    resolve_enum_value,
    split_params,
)
from situation_api_parser import (
    ROOT,
    ApiEntry,
    parse_api_header,
    parse_callbacks,
    parse_defines,
    parse_enums,
    parse_errno_enum,
    read_version,
)

OUT_DIR = ROOT / "wrappers" / "Modula2" / "src"
OUT_ROOT = ROOT / "wrappers" / "Modula2"

VOID_RETURN = "__VOID__"

CTYPE_MAP: dict[str, str] = {
    "void": VOID_RETURN,
    "bool": "BOOLEAN",
    "char": "CHAR",
    "int": "INTEGER",
    "unsigned int": "CARDINAL",
    "unsigned char": "CARDINAL8",
    "signed char": "INTEGER8",
    "short": "INTEGER16",
    "unsigned short": "CARDINAL16",
    "long": "LONGINT",
    "unsigned long": "LONGCARD",
    "long long": "LONGINT",
    "unsigned long long": "LONGCARD",
    "float": "REAL",
    "double": "LONGREAL",
    "size_t": "ADDRESS",
    "uint8_t": "CARDINAL8",
    "uint16_t": "CARDINAL16",
    "uint32_t": "CARDINAL",
    "uint64_t": "LONGCARD",
    "int8_t": "INTEGER8",
    "int16_t": "INTEGER16",
    "int32_t": "INTEGER",
    "int64_t": "LONGINT",
    "SituationError": "SituationError",
    "SituationCommandBuffer": "SituationCommandBuffer",
    "SituationInitState": "SituationInitState",
    "SituationLogLevel": "SituationLogLevel",
    "ColorRGBA": "ColorRGBA",
    "Color": "ColorRGBA",
    "Vector2": "Vector2",
    "Vector3": "Vector3",
    "Vector4": "Vector4",
    "SitRectangle": "SitRectangle",
    "SituationInitInfo": "SituationInitInfo",
    "SituationImage": "SituationImage",
    "SituationFont": "SituationFont",
    "SituationPackedFont": "SituationPackedFont",
    "SituationTexture": "SituationTexture",
    "SituationShader": "SituationShader",
    "SituationMesh": "SituationMesh",
    "SituationBuffer": "SituationBuffer",
    "SituationSound": "SituationSound",
    "SituationThreadPool": "SituationThreadPool",
    "SituationAudioGraph": "SituationAudioGraph",
    "SituationNode": "SituationNode",
    "SituationVirtualDisplay": "SituationVirtualDisplay",
    "SituationRenderPassInfo": "SituationRenderPassInfo",
    "SituationClearValue": "SituationClearValue",
    "SituationTimerSystem": "SituationTimerSystem",
    "ma_result": "INTEGER",
    "ma_uint64": "LONGCARD",
    "mat4": "Mat4",
}


def gen_m2_banner(version: str) -> str:
    return (
        f"(* Auto-generated by tools/generate_modula2_bindings.py — Situation {version} *)\n"
        f"(* Do not edit by hand. *)\n\n"
    )


def m2_return_suffix(ret: str) -> str:
    if ret == VOID_RETURN:
        return ""
    return f" : {ret}"


def render_manual_types() -> str:
    return """(* Core math & color (ABI must match sit/situation_api.h) *)
TYPE
  ColorRGBA = RECORD
    r, g, b, a: CARDINAL8;
  END;

  SitRectangle = RECORD
    x, y, width, height: REAL;
  END;

  Vector2 = RECORD
    x, y: REAL;
  END;

  Vector3 = RECORD
    x, y, z: REAL;
  END;

  Vector4 = RECORD
    x, y, z, w: REAL;
  END;

  (* Generational GPU handles *)
  SituationTexture = RECORD
    slot_index, generation: CARDINAL;
    width, height: INTEGER;
  END;

  SituationShader = RECORD
    slot_index, generation: CARDINAL;
  END;

  SituationMesh = RECORD
    slot_index, generation: CARDINAL;
    index_count, vertex_count: INTEGER;
    vertex_stride: LONGCARD;
  END;

  SituationFont = RECORD
    font_data, stb_font_info, glyph_info: ADDRESS;
    atlas_texture: SituationTexture;
    atlas_width, atlas_height: INTEGER;
    font_height_pixels: REAL;
    is_bitmap: BOOLEAN;
    bitmap_data: ADDRESS;
    bitmap_width, bitmap_height, bitmap_count: INTEGER;
    first_char, chars_per_row, chars_per_col: INTEGER;
    display_cell_width, display_cell_height: INTEGER;
    char_spacing, line_spacing: REAL;
  END;

  SituationPackedFont = RECORD
    char_width, char_height, display_height: INTEGER;
    char_count, first_char, chars_per_row: INTEGER;
    bits_per_row, data_bits, data_bit_offset: INTEGER;
    bit_order_msb_first: BOOLEAN;
    top_padding, bottom_padding, left_padding, right_padding: INTEGER;
    atlas_chars_per_row, atlas_chars_per_col: INTEGER;
    enable_outline: BOOLEAN;
    outline_thickness: INTEGER;
    outline_r, outline_g, outline_b, outline_a: CARDINAL8;
    font_r, font_g, font_b, font_a: CARDINAL8;
  END;

  (* Opaque handles (layout unknown — pass as pointer) *)
  SituationCommandBuffer = ADDRESS;
  SituationThreadPool = POINTER TO SituationThreadPoolOpaque;
  SituationAudioGraph = POINTER TO SituationAudioGraphOpaque;
  SituationNode = POINTER TO SituationNodeOpaque;

  SituationThreadPoolOpaque = RECORD END;
  SituationAudioGraphOpaque = RECORD END;
  SituationNodeOpaque = RECORD END;

  (* Scalar type aliases for C/miniaudio interop *)
  SituationJobId = CARDINAL;
  SituationNodeHandle = CARDINAL;
  SituationModifiers = INTEGER;
  SituationStreamSize = LONGCARD;
  SituationStreamResult = INTEGER;
  SituationSeekOrigin = INTEGER;
  ma_int64 = LONGINT;
  ma_seek_origin = INTEGER;
  FILE = ADDRESS;

  (* Additional opaque/resource handles *)
  SituationSound = RECORD
    slot_index, generation: CARDINAL;
  END;

  SituationBuffer = RECORD
    slot_index, generation: CARDINAL;
  END;

  SituationComputePipeline = RECORD
    slot_index, generation: CARDINAL;
  END;

  (* Structs referenced by the API but defined internally *)
  SituationCameraDesc = POINTER TO SituationCameraDescOpaque;
  SituationRenderPassInfo = POINTER TO SituationRenderPassInfoOpaque;
  SituationCameraDescOpaque = RECORD END;
  SituationRenderPassInfoOpaque = RECORD END;

  SituationTextureBlitRegion = RECORD
    x, y, width, height: INTEGER;
  END;

  (* cglm mat4 equivalent *)
  Mat4 = ARRAY [0..3], [0..3] OF REAL;

  (* Layout must match MSVC x64 / MinGW C ABI in sit/situation_api.h (v2.4.336+).
     Use SituationGlue.SituationM2InitInfoWindow to populate — do not hand-fill. *)
  SituationInitInfo = RECORD
    window_width, window_height: INTEGER;
    window_title: ADDRESS;
    initial_active_window_flags, initial_inactive_window_flags: CARDINAL;
    enable_vulkan_validation, force_single_queue: BOOLEAN;
    _pad_after_vulkan_bools: ARRAY [0..1] OF CARDINAL8;
    max_frames_in_flight: CARDINAL;
    required_vulkan_extensions: ADDRESS;
    required_vulkan_extension_count, flags: CARDINAL;
    output_color_depth: INTEGER;
    max_audio_voices: CARDINAL;
    render_thread_count, backpressure_policy: INTEGER;
    io_queue_capacity: CARDINAL;
    disable_io_thread: BOOLEAN;
    _pad_before_hot_reload: ARRAY [0..6] OF CARDINAL8;
    hot_reload_poll_rate: LONGREAL;
    staging_buffer_size: LONGCARD;
    main_thread_name: ADDRESS;
    thread_affinity_main, thread_affinity_render, thread_affinity_audio: LONGCARD;
    numa_prefer_local, worker_numa_spread: BOOLEAN;
    _pad_before_io_numa: ARRAY [0..1] OF CARDINAL8;
    io_thread_numa_node: INTEGER;
    thread_pool_use_physical_cores: BOOLEAN;
    _pad_before_pool_reserved: ARRAY [0..2] OF CARDINAL8;
    thread_pool_reserved_threads: CARDINAL;
  END;
"""


def render_enum(e_name: str, members: list[tuple[str, str | None]], define_map: dict[str, str]) -> str:
    member_values: dict[str, int] = {}
    for name, value in members:
        if value is None:
            continue
        try:
            resolved = resolve_enum_value(value, define_map)
            expr = resolved
            for mname, mval in member_values.items():
                expr = re.sub(r"\b" + re.escape(mname) + r"\b", str(mval), expr)
            member_values[name] = eval(expr)  # noqa: S307 — controlled input
        except Exception:
            pass

    lines = [f"  {e_name} = INTEGER;"]
    const_lines: list[str] = []
    for name, value in members:
        if value is None:
            continue
        resolved = resolve_enum_value(value, define_map)
        expanded = resolved
        for mname, mval in member_values.items():
            expanded = re.sub(r"\b" + re.escape(mname) + r"\b", str(mval), expanded)
        try:
            numeric = eval(expanded)  # noqa: S307 — controlled input
            const_lines.append(f"  {name} = {numeric};")
        except Exception:
            const_lines.append(f"  {name} = {expanded};")

    if not const_lines:
        return f"  {e_name} = INTEGER;\n"

    return "\n".join(lines) + "\n\nCONST\n" + "\n".join(const_lines) + "\n"


def render_enums() -> str:
    define_map = build_define_map()
    type_parts: list[str] = []
    const_parts: list[str] = []

    errno = parse_errno_enum()
    type_parts.append(f"  {errno.name} = INTEGER;")
    for name, value in errno.members:
        if value is None:
            continue
        resolved = resolve_enum_value(value, define_map)
        const_parts.append(f"  {name} = {resolved};")

    for e in parse_enums():
        if e.name == "SituationError":
            continue
        if len(e.members) < 2:
            continue
        type_parts.append(f"  {e.name} = INTEGER;")
        member_values: dict[str, int] = {}
        for name, value in e.members:
            if value is None:
                continue
            try:
                resolved = resolve_enum_value(value, define_map)
                expr = resolved
                for mname, mval in member_values.items():
                    expr = re.sub(r"\b" + re.escape(mname) + r"\b", str(mval), expr)
                member_values[name] = eval(expr)  # noqa: S307 — controlled input
            except Exception:
                pass
        for name, value in e.members:
            if value is None:
                continue
            resolved = resolve_enum_value(value, define_map)
            expanded = resolved
            for mname, mval in member_values.items():
                expanded = re.sub(r"\b" + re.escape(mname) + r"\b", str(mval), expanded)
            try:
                numeric = eval(expanded)  # noqa: S307 — controlled input
                const_parts.append(f"  {name} = {numeric};")
            except Exception:
                const_parts.append(f"  {name} = {expanded};")

    lines = ["TYPE", "\n".join(type_parts)]
    if const_parts:
        lines.extend(["", "CONST", "\n".join(const_parts)])
    return "\n".join(lines) + "\n"


def wrap_def_module(
    name: str,
    body: str,
    imports: list[str] | None = None,
    *,
    for_linkage: str | None = None,
) -> str:
    if for_linkage:
        lines = [f'DEFINITION MODULE FOR "{for_linkage}" {name};', ""]
    else:
        lines = [f"DEFINITION MODULE {name};", ""]
    if imports:
        for imp in imports:
            lines.append(imp)
        lines.append("")
    lines.append(body.rstrip())
    lines.append("")
    lines.append(f"END {name}.")
    return "\n".join(lines) + "\n"


PRIMITIVE_NAMES = {
    "BOOLEAN", "CHAR", "INTEGER", "CARDINAL", "LONGINT", "LONGCARD",
    "REAL", "LONGREAL", "ADDRESS", "CARDINAL8", "INTEGER8",
    "CARDINAL16", "INTEGER16", "VOID", "PROCEDURE", "RECORD", "ARRAY", "OF",
    "POINTER", "TO", "END", "NIL", "EXPORT", "UNQUALIFIED", "EXTERN",
}

# SituationTypes names that already denote a pointer type (do not wrap again).
ALREADY_POINTER_TYPES = {
    "SituationThreadPool", "SituationAudioGraph", "SituationNode",
    "SituationCameraDesc", "SituationRenderPassInfo",
    "ColorHSV", "ColorRGBA10", "ColorYPQA", "ColorYPQf", "GLFWwindow",
    "SituationAudioDeviceInfo", "SituationAudioFormat",
    "SituationBufferBarrierDesc", "SituationCPUInfo", "SituationClearValue",
    "SituationCpuTopology", "SituationDeviceFunctions", "SituationDeviceInfo",
    "SituationDeviceMetadata", "SituationDisplayInfo", "SituationDisplayMode",
    "SituationGPUInfo", "SituationGraphicsCaps", "SituationImage",
    "SituationMemoryInfo", "SituationMidiDeviceInfo",
    "SituationModel", "SituationMultisampleState", "SituationNumaTopology",
    "SituationOSInfo", "SituationPipelineBarrierDesc", "SituationProcessInfo",
    "SituationReadPixelsDesc", "SituationRenderList",
    "SituationShaderStorageBlockInfo", "SituationSoundHandle",
    "SituationStencilState", "SituationTextureBarrierDesc",
    "SituationTextureCopyRegion", "SituationTextureInfo",
    "SituationTextureReadbackDesc", "SituationThreadPoolMetrics",
    "SituationThreadPoolSnapshot", "SituationThreadingStatus",
    "SituationToneHandle", "SituationUniformExpectation",
    "SituationVirtualDisplay", "SituationVirtualDisplayAttachmentDefaults",
    "SituationVirtualDisplayDesc", "SituationYpqRgbMappingStats",
    "VkDevice", "VkInstance", "VkPhysicalDevice", "VkRenderPass",
}


def m2_scalar_base(ctype: str) -> str:
    """Map a C scalar/struct name to a Modula-2 type (no pointer suffix)."""
    ctype = normalize_c_type(ctype)
    if "(*" in ctype or ctype.endswith("Callback"):
        base = ctype.split("(")[0].strip().replace("*", "").strip()
        if not base.endswith("Callback"):
            base += "Callback"
        return base

    base = ctype.replace("*", "").strip()

    if base == "void":
        return VOID_RETURN

    if base == "char":
        return "CHAR"

    if base in CTYPE_MAP:
        return CTYPE_MAP[base]
    if base.startswith("Situation") or base in (
        "ColorRGBA", "Vector2", "Vector3", "Vector4", "SitRectangle", "Mat4",
    ):
        return base
    return base if base else "ADDRESS"


def pointer_alias_name(base: str) -> str:
    """Named pointer alias required for -fpim procedure formals."""
    if base in ALREADY_POINTER_TYPES:
        return base
    return f"{base}Ptr"


def c_type_to_m2(ctype: str) -> str:
    ctype = normalize_c_type(ctype)

    if "(*" in ctype or ctype.endswith("Callback"):
        return m2_scalar_base(ctype)

    ptr_depth = ctype.count("*")
    base_raw = ctype.replace("*", "").strip()

    if base_raw == "void":
        return VOID_RETURN if ptr_depth == 0 else "ADDRESS"
    if base_raw == "char":
        return "CHAR" if ptr_depth == 0 else "ADDRESS"

    base = m2_scalar_base(ctype)
    if ptr_depth == 0:
        return base
    if ptr_depth == 1:
        return pointer_alias_name(base)
    inner = pointer_alias_name(base)
    for _ in range(ptr_depth - 2):
        inner = pointer_alias_name(inner)
    return inner


def consider_pointer_alias(ctype: str, aliases: dict[str, str]) -> None:
    norm = normalize_c_type(ctype)
    if "(*" in norm or norm.endswith("Callback"):
        return
    ptr_depth = norm.count("*")
    if ptr_depth == 0:
        return
    base_raw = norm.replace("*", "").strip()
    if base_raw in ("void", "char"):
        return
    base = m2_scalar_base(norm)
    alias = pointer_alias_name(base)
    if alias != base:
        aliases[alias] = base


def collect_pointer_aliases(entries: list[ApiEntry]) -> dict[str, str]:
    aliases: dict[str, str] = {}
    api_text = (ROOT / "sit" / "situation_api.h").read_text(encoding="utf-8", errors="replace")
    base_text = (ROOT / "sit" / "situation_base_callbacks.h").read_text(encoding="utf-8", errors="replace")
    for cb in parse_callbacks(api_text + "\n" + base_text):
        m = re.match(r"(.+?)\s*\(\*\s*\w+\s*\)\s*\((.*)\)", cb.signature)
        if not m:
            continue
        consider_pointer_alias(m.group(1).strip(), aliases)
        for p in split_params(m.group(2)):
            parsed = parse_param(p, lambda t: t)
            if parsed:
                consider_pointer_alias(parsed[1], aliases)
    for e in foreign_entries(entries):
        m = re.match(
            r"^(const\s+)?(.+?)\s+(\w+)\s*\((.*)\)\s*;?\s*$",
            strip_c_api_attributes(e.signature),
        )
        if not m:
            continue
        consider_pointer_alias(m.group(2).strip(), aliases)
        for p in split_params(m.group(4)):
            parsed = parse_param(p, lambda t: t)
            if parsed:
                consider_pointer_alias(parsed[1], aliases)
    return aliases


def render_pointer_aliases(aliases: dict[str, str]) -> str:
    if not aliases:
        return ""
    lines = [
        "(* Named pointer aliases (-fpim forbids POINTER TO in procedure formals) *)",
        "",
        "TYPE",
    ]
    for alias in sorted(aliases):
        lines.append(f"  {alias} = POINTER TO {aliases[alias]};")
    lines.append("")
    return "\n".join(lines)

TYPE_PATTERN = re.compile(r"\b([A-Z][A-Za-z0-9_]*)\b")


def scan_types_from_m2_type(type_str: str) -> set[str]:
    referenced: set[str] = set()
    cleaned = type_str
    while "POINTER TO " in cleaned:
        cleaned = cleaned.replace("POINTER TO ", "")
    for m in TYPE_PATTERN.finditer(cleaned):
        name = m.group(1)
        if name not in PRIMITIVE_NAMES:
            referenced.add(name)
    return referenced


def format_type_imports(
    referenced: set[str],
    module: str = "SituationTypes",
    *,
    include_common_extras: bool = False,
) -> list[str]:
    extras: set[str] = set()
    if include_common_extras:
        extras = {"Mat4", "ma_int64", "ma_seek_origin", "FILE"}
    names = sorted((referenced - PRIMITIVE_NAMES - {""}) | extras)
    if not names:
        return []
    return [f"FROM {module} IMPORT {', '.join(names)};"]


def render_callbacks() -> str:
    api_text = (ROOT / "sit" / "situation_api.h").read_text(encoding="utf-8", errors="replace")
    base_text = (ROOT / "sit" / "situation_base_callbacks.h").read_text(encoding="utf-8", errors="replace")
    cbs = parse_callbacks(api_text + "\n" + base_text)

    lines = [
        "(* Callback typedefs from sit/situation_api.h and sit/situation_base_callbacks.h *)",
        "",
        "TYPE",
    ]
    referenced: set[str] = set()
    seen: set[str] = set()
    for cb in cbs:
        m2_name = cb.name if cb.name.endswith("Callback") else cb.name + "Callback"
        if m2_name in seen:
            continue
        seen.add(m2_name)
        m = re.match(r"(.+?)\s*\(\*\s*\w+\s*\)\s*\((.*)\)", cb.signature)
        params: list[str] = []
        ret = VOID_RETURN
        if m:
            ret_str = m.group(1).strip()
            if ret_str != "void":
                ret = c_type_to_m2(ret_str)
                referenced |= scan_types_from_m2_type(ret)
            for p in split_params(m.group(2)):
                parsed = parse_param(p, c_type_to_m2)
                if parsed:
                    params.append(parsed[1])
                    referenced |= scan_types_from_m2_type(parsed[1])
        param_str = ", ".join(params)
        ret_suffix = m2_return_suffix(ret)
        lines.append(f"  {m2_name} = PROCEDURE ({param_str}){ret_suffix};")
        if cb.comment:
            lines.append(f"  (* {cb.comment} *)")
    body = "\n".join(lines)
    imports = ["FROM SYSTEM IMPORT ADDRESS;"]
    imports.extend(format_type_imports(referenced))
    return wrap_def_module("SituationCallbacks", body, imports)


def render_foreign(entries: list[ApiEntry]) -> str:
    NULLABLE_OVERRIDES: dict[str, str] = {
        "SituationSetActiveGraph.0": "SituationAudioGraph",
    }

    proc_names: list[str] = []
    proc_lines: list[str] = []
    type_refs: set[str] = set()
    callback_refs: set[str] = set()

    seen_names: set[str] = set()
    for e in sorted(entries, key=lambda x: x.name):
        if e.manual_only or e.name in MANUAL_FUNCTIONS:
            continue
        if e.name in seen_names:
            continue
        seen_names.add(e.name)
        parsed = parse_function_signature(e.signature, c_type_to_m2)
        if not parsed:
            proc_lines.append(f"(* SKIP (unparsed): {e.name} *)")
            continue
        ret, name, params = parsed
        proc_names.append(name)
        if ret != VOID_RETURN:
            bucket = callback_refs if ret.endswith("Callback") else type_refs
            bucket |= scan_types_from_m2_type(ret)
        param_parts = []
        for idx, (pn, pt) in enumerate(params):
            override_key = f"{name}.{idx}"
            if override_key in NULLABLE_OVERRIDES:
                pt = NULLABLE_OVERRIDES[override_key]
            param_parts.append(f"{pn}: {pt}")
            bucket = callback_refs if pt.endswith("Callback") else type_refs
            bucket |= scan_types_from_m2_type(pt)
        param_str = "; ".join(param_parts)
        ret_suffix = m2_return_suffix(ret)
        if e.comment:
            proc_lines.append(f"(* {e.comment} *)")
        proc_lines.append(f"PROCEDURE {name} ({param_str}){ret_suffix};")
        if e.comment:
            proc_lines.append("")

    export_block = "EXPORT UNQUALIFIED\n  " + ",\n  ".join(proc_names) + ";\n\n" if proc_names else ""
    body = export_block + "\n".join(proc_lines)
    imports = ["FROM SYSTEM IMPORT ADDRESS, CARDINAL8, INTEGER16;"]
    imports.extend(format_type_imports(type_refs, include_common_extras=True))
    imports.extend(format_type_imports(callback_refs, "SituationCallbacks"))
    return wrap_def_module("SituationForeign", body, imports, for_linkage="C")


def render_constants() -> str:
    names: list[str] = []
    const_lines = ["(* Selected constants from sit/situation_base_etc.h *)", "", "CONST"]
    for d in parse_defines():
        val = d.value
        if val.endswith("f"):
            val = val[:-1]
        val = re.sub(r"\s*/\*.*?\*/\s*$", "", val).strip()
        val = re.sub(r"\s*//.*$", "", val).strip()
        names.append(d.name)
        const_lines.append(f"  {d.name} = {val};")
    export_block = "EXPORT UNQUALIFIED\n  " + ",\n  ".join(names) + ";\n\n" if names else ""
    body = export_block + "\n".join(const_lines)
    return wrap_def_module("SituationConstants", body)


def render_helpers_def() -> str:
    body = """EXPORT UNQUALIFIED
  situationBeginFrame,
  situationSuccess;

(* Helpers replacing C preprocessor macros from situation_api.h *)

PROCEDURE situationBeginFrame;

PROCEDURE situationSuccess (err: SituationError): BOOLEAN;
"""
    imports = [
        "FROM SituationTypes IMPORT SituationError;",
    ]
    return wrap_def_module("SituationHelpers", body, imports)


def render_helpers_mod() -> str:
    return """(* Implementation companion for SituationHelpers.def *)

IMPLEMENTATION MODULE SituationHelpers;

FROM SituationForeign IMPORT SituationPollInputEvents, SituationUpdateTimers;
FROM SituationTypes IMPORT SituationError;

CONST
  SITUATION_SUCCESS = 0;

PROCEDURE situationBeginFrame;
BEGIN
  SituationPollInputEvents();
  SituationUpdateTimers()
END situationBeginFrame;

PROCEDURE situationSuccess (err: SituationError): BOOLEAN;
BEGIN
  RETURN err = SITUATION_SUCCESS
END situationSuccess;

END SituationHelpers.
"""


def render_types(entries: list[ApiEntry]) -> str:
    pointer_aliases = collect_pointer_aliases(entries)
    body = (
        render_manual_types()
        + "\n"
        + render_pointer_aliases(pointer_aliases)
        + render_enums()
        + render_opaque_stubs(entries, pointer_aliases)
    )
    imports = ["FROM SYSTEM IMPORT ADDRESS, CARDINAL8, INTEGER16;"]
    return wrap_def_module("SituationTypes", body, imports)


def render_manual_md(entries: list[ApiEntry]) -> str:
    manual = [e for e in entries if e.manual_only or e.name in MANUAL_FUNCTIONS]
    lines = [
        "# Situation Modula-2 — Manual bindings",
        "",
        "These symbols are **not** emitted in `SituationForeign.def`. Add hand-written Modula-2 wrappers as needed.",
        "",
        "| Function | Reason |",
        "|----------|--------|",
    ]
    for e in sorted(manual, key=lambda x: x.name):
        reason = e.manual_reason or "listed in MANUAL_FUNCTIONS"
        lines.append(f"| `{e.name}` | {reason} |")
    lines.append("")
    return "\n".join(lines)


def render_api_index(entries: list[ApiEntry], version: str) -> str:
    lines = [
        "# Situation Modula-2 bindings — API index",
        "",
        f"_Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} from `sit/situation_api.h` — Situation **{version}**._",
        "",
        f"**Foreign imports:** {len(foreign_entries(entries))}",
        "",
        "| Function | Section | Modula-2 | Notes |",
        "|----------|---------|----------|-------|",
    ]
    for e in sorted(entries, key=lambda x: x.name):
        if e.manual_only or e.name in MANUAL_FUNCTIONS:
            m2 = "manual"
            note = e.manual_reason or "manual wrapper"
        else:
            m2 = "auto"
            note = e.comment[:80] + ("..." if len(e.comment) > 80 else "")
        lines.append(f"| `{e.name}` | {e.section} | {m2} | {note or '—'} |")
    lines.append("")
    return "\n".join(lines)


def collect_referenced_types(entries: list[ApiEntry]) -> set[str]:
    referenced: set[str] = set()
    type_pattern = re.compile(r"\b([A-Z][A-Za-z0-9_]*)\b")
    for e in foreign_entries(entries):
        parsed = parse_function_signature(e.signature, c_type_to_m2)
        if not parsed:
            continue
        ret, _name, params = parsed
        if ret != VOID_RETURN:
            for m in type_pattern.finditer(ret):
                referenced.add(m.group(1))
        for _pname, ptype in params:
            for m in type_pattern.finditer(ptype):
                referenced.add(m.group(1))
    return referenced


def render_opaque_stubs(entries: list[ApiEntry], pointer_aliases: dict[str, str] | None = None) -> str:
    referenced = collect_referenced_types(entries)
    known_types = {
        "BOOLEAN", "CHAR", "INTEGER", "CARDINAL", "LONGINT", "LONGCARD",
        "REAL", "LONGREAL", "ADDRESS", "CARDINAL8", "INTEGER8",
        "CARDINAL16", "INTEGER16",
        "ColorRGBA", "SitRectangle", "Vector2", "Vector3", "Vector4",
        "SituationTexture", "SituationShader", "SituationMesh", "SituationFont", "SituationPackedFont",
        "SituationCommandBuffer", "SituationThreadPool",
        "SituationAudioGraph", "SituationNode",
        "SituationJobId", "SituationNodeHandle",
        "SituationModifiers", "SituationStreamSize", "SituationStreamResult",
        "SituationSeekOrigin", "FILE",
        "SituationSound", "SituationBuffer", "SituationComputePipeline",
        "SituationCameraDesc", "SituationRenderPassInfo",
        "SituationTextureBlitRegion",
        "SituationInitInfo", "SituationError",
        "SituationThreadPoolOpaque", "SituationAudioGraphOpaque", "SituationNodeOpaque",
        "SituationCameraDescOpaque", "SituationRenderPassInfoOpaque",
        "ma_int64", "ma_seek_origin", "Mat4", "mat4",
        "SituationLogLevel", "SituationInitState",
    }
    for e in parse_enums():
        known_types.add(e.name)
    errno = parse_errno_enum()
    known_types.add(errno.name)
    if pointer_aliases:
        known_types.update(pointer_aliases.keys())
        known_types.update(pointer_aliases.values())

    api_text = (ROOT / "sit" / "situation_api.h").read_text(encoding="utf-8", errors="replace")
    base_text = (ROOT / "sit" / "situation_base_callbacks.h").read_text(encoding="utf-8", errors="replace")
    for cb in parse_callbacks(api_text + "\n" + base_text):
        name = cb.name if cb.name.endswith("Callback") else cb.name + "Callback"
        known_types.add(name)

    missing = sorted(referenced - known_types)
    if not missing:
        return ""

    lines = [
        "",
        "(* --- Auto-generated opaque type stubs --- *)",
        "(* These types are referenced by the API but their layout is internal. *)",
        "(* Pass them by pointer. If you need field access, define them manually. *)",
        "",
        "TYPE",
    ]
    for t in missing:
        if len(t) <= 2 or t in ("Select", "First", "String", "POINTER", "TO"):
            continue
        lines.append(f"  {t} = POINTER TO {t}Opaque;")
        lines.append(f"  {t}Opaque = RECORD END;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate GNU Modula-2 FFI bindings for Situation")
    parser.add_argument(
        "--lib",
        default="situation_opengl",
        help="Library name for linking (without .lib extension)",
    )
    args = parser.parse_args()
    _ = args.lib  # Reserved for future build script integration.

    version = read_version()
    entries = parse_api_header()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    banner = gen_m2_banner(version)

    written: list[Path] = []
    files = {
        OUT_DIR / "SituationTypes.def": banner + render_types(entries),
        OUT_DIR / "SituationCallbacks.def": banner + render_callbacks(),
        OUT_DIR / "SituationForeign.def": banner + render_foreign(entries),
        OUT_DIR / "SituationConstants.def": banner + render_constants(),
        OUT_DIR / "SituationHelpers.def": banner + render_helpers_def(),
        OUT_DIR / "SituationHelpers.mod": banner + render_helpers_mod(),
        OUT_ROOT / "API_INDEX.md": render_api_index(entries, version),
        OUT_ROOT / "MANUAL_BINDINGS.md": render_manual_md(entries),
    }

    errors: list[str] = []
    for path, content in files.items():
        try:
            path.write_text(content, encoding="utf-8")
            written.append(path)
        except OSError as exc:
            errors.append(f"{path}: {exc}")

    auto = len(foreign_entries(entries))
    print(f"Situation {version}")
    print(f"Modula-2 bindings: {auto} EXTERN procedures, {len(entries)} total SITAPI")
    for path in written:
        rel = path.relative_to(ROOT)
        print(f"Wrote {rel}")
    print(f"Files written: {len(written)}")
    if errors:
        print("Errors:")
        for err in errors:
            print(f"  {err}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()