# Auto-generated by tools/generate_python_bindings.py — Situation 2.4.366 (Vulkan shader cache Phase 6E/6C: async Layer A fast path, descriptor reload gate.)
# Do not edit by hand.

"""Callback CFUNCTYPE aliases from sit/situation_base_callbacks.h."""

from ctypes import (
    CFUNCTYPE,
    POINTER,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int64,
    c_size_t,
    c_uint32,
    c_uint64,
    c_void_p,
)

from . import types as T

SituationFileDropCallback = CFUNCTYPE(None, c_int, POINTER(c_char_p), c_void_p)

SituationFileLoadCallback = CFUNCTYPE(None, c_void_p, c_size_t, c_void_p)

SituationFileSaveCallback = CFUNCTYPE(None, c_bool, c_void_p)

SituationFileTextLoadCallback = CFUNCTYPE(None, c_char_p, c_void_p)

SituationFocusCallback = CFUNCTYPE(None, c_bool, c_void_p)

SituationMaximizeCallback = CFUNCTYPE(None, c_bool, c_void_p)

SituationWindowCloseCallback = CFUNCTYPE(None, c_void_p)

SituationKeyCallback = CFUNCTYPE(None, c_int, c_int, c_int, c_void_p, c_void_p)

SituationCharCallback = CFUNCTYPE(None, c_void_p, c_void_p)

SituationMouseButtonCallback = CFUNCTYPE(None, c_int, c_int, c_void_p, c_void_p)

SituationCursorPosCallback = CFUNCTYPE(None, c_void_p, c_void_p)

SituationScrollCallback = CFUNCTYPE(None, c_void_p, c_void_p)

SituationJoystickCallback = CFUNCTYPE(None, c_int, c_int, c_void_p)

SituationStreamReadCallback = CFUNCTYPE(c_int, c_void_p, c_void_p, c_void_p)

SituationStreamSeekCallback = CFUNCTYPE(c_int, c_void_p, c_void_p, c_void_p)

SituationAudioCaptureCallback = CFUNCTYPE(None, POINTER(c_float), c_uint32, c_void_p)

SituationAudioProcessorCallback = CFUNCTYPE(None, POINTER(c_float), c_uint32, c_uint32, c_uint32, c_void_p)

GLFWerrorfunCallback = CFUNCTYPE(None, c_int, c_char_p)
