# Auto-generated by tools/generate_python_bindings.py — Situation 2.4.366 (Vulkan shader cache Phase 6E/6C: async Layer A fast path, descriptor reload gate.)
# Do not edit by hand.

"""Helpers replacing C preprocessor macros and safe init patterns."""

from __future__ import annotations

from ctypes import byref, c_char_p, c_int, c_void_p

from . import types as T

SIT_OUTPUT_COLOR_AUTO = 0


class SituationError(Exception):
    """Raised when a Situation API call returns a non-success SituationError code."""

    def __init__(self, code: int):
        self.code = code
        super().__init__(f"SituationError({code})")


def check(err: int) -> None:
    if err != 0:
        raise SituationError(err)


def situation_success(err: int) -> bool:
    return err == 0


def situation_begin_frame(dll) -> None:
    dll.SituationPollInputEvents()
    dll.SituationUpdateTimers()


def init_info_zero(info: T.SituationInitInfo) -> None:
    """Zero-fill init info and set output_color_depth = AUTO."""
    from ctypes import addressof, memset, sizeof

    memset(addressof(info), 0, sizeof(info))
    info.output_color_depth = SIT_OUTPUT_COLOR_AUTO


def init_info_window(width: int, height: int, title: str | bytes) -> T.SituationInitInfo:
    """Populate SituationInitInfo the same way as SituationM2InitInfoWindow / Rust Default."""
    info = T.SituationInitInfo()
    init_info_zero(info)
    info.window_width = width
    info.window_height = height
    if isinstance(title, str):
        title = title.encode("utf-8")
    info.window_title = c_char_p(title)
    return info
